### ISSUE TITLE
Archive mislabels TPF descriptions

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#108]
![image](https://user-images.githubusercontent.com/14965634/38704308-bd50e07a-3e5a-11e8-9fc9-6476963c5d31.png)

We rely on these descriptions to get the campaign numbers for from archive. But instead, we could use the filenames. The file names are less likely to be incorrect than the descriptions.

**Comment by christinahedges** [comment]
The only problem for this is we can't do it for Kepler quarters

**Comment by JeffLCoughlin** [comment]
Where in the archive is this listing of filenames and descriptions?

**Comment by barentsen** [comment]
@JeffLCoughlin These are values of the `productFilename` and `description` fields returned by the MAST Portal API.  (cf. https://mast.stsci.edu/api/ )

**Comment by JeffLCoughlin** [comment]
Ah gotcha. I put in on the MAST tag-up agenda for next meeting (unless you already have or want to tackle it through their API ticket/feedback system).  At least I'm assuming it'd be ideal to try getting the API-end correct before having to make a client-side fix.

**Comment by scfleming** [comment]
Oops, we can fix this!  I'm on it.

**Comment by scfleming** [comment]
This should be fixed in the database if you want to verify.

**Comment by barentsen** [comment]
Assigning to @christinahedges to verify that the issue has been resolved!

**Comment by barentsen** [comment]
I verified that the example reported at the start of this issue is resolved at MAST.  Thanks @scfleming!!
