### ISSUE TITLE
Bad priors do not produce error message in PRF-fitting

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#110]
We (intentionally) mis-specified the prior as being completely outside the bounds of the TPF window to see what would happen.  `phot.fit(tpf.flux)` returns the an array of prior.mean with no indication that the fit failed.

**Comment by barentsen** [comment]
Closing this issue because it is >1 year old and the PRF-fitting module is not actively being used/advertised/developed at this time.  (Turns out PRF photometry is really hard!)
