### ISSUE TITLE
Here's an example of using lightkurve to do asteroseismology

### ISSUE THREAD

**Issue by dfm** [KeplerGO/lightkurve#114]
As requested by @christinahedges 

https://gist.github.com/dfm/0fba6dae50bbbe110417b0a249ae78d5

**Comment by mirca** [comment]
👏 👏 👏

**Comment by barentsen** [comment]
A dedicated `lightkurve.seismology` sub-package is now available in Lightkurve (since v1.1), in part based on the fabulous example posted by @dfm.  We can close this issue!
