### ISSUE TITLE
NaN times are possible for certain quality masks.

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#116]
I see NaN times when I use a quality_bitmask=None:

```python
tpf = KeplerTargetPixelFile.from_archive(201572338, quality_bitmask=None)
nan_times = tpf.time != tpf.time
nan_times.sum()

145
```

Many of these NaN times have quality values of 98304, which indicates *'No fine point', 'No data'*.
The possibility of NaN times is not necessarily a bug, and will likely only occur when quality_bitmask=None, since these quality flags are masked by default.  However, their presence does raise the question of whether we want to build in resilience to the possibility of NaN times.  They *do* have cadence numbers.

This question arose while designing `tpf.interact()`, which has so-far safely assumed times are all finite, but gets broken when NaN times are present.  I suspect it affects other places in the code that assume finite times.

**Comment by mirca** [comment]
It would be nice to have tasks that can handles NaNs properly. In the meanwhile,
I think expanding the documentation a bit would help with this issue. Something like:
```
quality_bitmask : str or int
        Bitmask specifying quality flags of cadences that should be ignored.
        If `None` is passed, then no cadences are ignored. Note that,
        in this case, there might be candences with NaN values in either time, flux, or both.
```

**Comment by christinahedges** [comment]
Why are these not taken care of by the `remove_nans()` function?

`remove_nans()` should remove cadences where `time` and/or `flux` are nans.

It could optionally have a keyword to drop the nans in the `flux_err` as well. @andytza, try this one out instead.

* Fix the remove_nans() function to remove nans in time
* Add a unit test to test_lightcurve.py to verify that nans in time are removed.
