### ISSUE TITLE
Can not create a new KeplerLightCurve object

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#117]
I used to be able to create KeplerLightCurve objects, but this now breaks.

![image](https://user-images.githubusercontent.com/14965634/39596424-2aa782f6-4ec7-11e8-8be9-02d57e9b5a5c.png)

**Comment by christinahedges** [comment]
I think this might actually be better, I should be using the blank `LightCurve` object, `KeplerLightCurve` object is something more specific?

**Comment by barentsen** [comment]
I cannot reproduce this bug.  Plus there are several unit tests that do the same and don't fail. @christinahedges can you double-check that this happens for you on the master branch?

![image](https://user-images.githubusercontent.com/817669/39668127-0a907a9a-507a-11e8-80f6-d7b75a900bba.png)

**Comment by christinahedges** [comment]
@AndyTza I'm going to ask you to test this and find out of it is still a real error. If it is a real error, post it here with a screen cap and come up with a fix.

C
