### ISSUE TITLE
lightkurve interact() crashes when calling ipywidgets

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#127]
I've tried to use interact() on two different linux machines (Linux Mint 17.3 in one and 18.3 in the other), and am getting this error in both. Both using v1.0.b5 of lightkurve, both installed via pip. Traceback and other info is below - happy to provide anything else that's useful. Thanks!

jeff@jeff-msi ~ $ python
Python 2.7.13 |Anaconda custom (64-bit)| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import lightkurve
>>> lightkurve.__version__
'1.0.b5'
>>> from lightkurve import KeplerTargetPixelFile
>>> tpf = KeplerTargetPixelFile.from_archive(249928278, campaign=15) # WASP 104 for example
Found 1 File(s)
INFO: Found cached file ./mastDownload/K2/ktwo249928278-c15_lc/ktwo249928278-c15_lpd-targ.fits.gz with expected size 6996829. [astroquery.query]
>>> tpf.interact()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/home/jeff/anaconda2/lib/python2.7/site-packages/ipywidgets/widgets/interaction.pyc in observer(change)
     72         with out:
     73             clear_output(wait=True)
---> 74             f(**kwargs)
     75             show_inline_matplotlib_plots()
     76     for k,w in controls.items():

/home/jeff/anaconda2/lib/python2.7/site-packages/lightkurve/targetpixelfile.pyc in update(cadence, log_stretch)
    767                 vert.update(line_alpha=0)
    768                 fig2_dat.data_source.data['image'] = [self.flux[0, :, :] * np.NaN]
--> 769             push_notebook()
    770 
    771         # Define the widgets that enable the interactivity

/home/jeff/anaconda2/lib/python2.7/site-packages/bokeh/io/notebook.pyc in push_notebook(document, state, handle)
    254     msg = Protocol("1.0").create("PATCH-DOC", events)
    255 
--> 256     handle.comms.send(msg.header_json)
    257     handle.comms.send(msg.metadata_json)
    258     handle.comms.send(msg.content_json)

/home/jeff/anaconda2/lib/python2.7/site-packages/ipykernel/comm/comm.pyc in send(self, data, metadata, buffers)
    119         """Send a message to the frontend-side version of this comm"""
    120         self._publish_msg('comm_msg',
--> 121             data=data, metadata=metadata, buffers=buffers,
    122         )
    123 

/home/jeff/anaconda2/lib/python2.7/site-packages/ipykernel/comm/comm.pyc in _publish_msg(self, msg_type, data, metadata, buffers, **keys)
     64         metadata = {} if metadata is None else metadata
     65         content = json_clean(dict(data=data, comm_id=self.comm_id, **keys))
---> 66         self.kernel.session.send(self.kernel.iopub_socket, msg_type,
     67             content,
     68             metadata=json_clean(metadata),

AttributeError: 'NoneType' object has no attribute 'session'
HBox(children=(Play(value=149142, description=u'Press play', interval=10, max=153449, min=149142, show_repeat=…
Output()
In :

**Comment by JeffLCoughlin** [comment]
Just a note I upgraded all my packages to latest versions via conda and pip, and the error still occurs.

**Comment by JeffLCoughlin** [comment]
I fell victim to not RTFM. I wasn't running in a Jupyter Notebook and the interact page clearly says " This method can only be run in a Jupyter Notebook at the moment, and is limited to lightcurves with fewer than 30000 cadences."   Maybe it could be bolded for people like me heh. Closing issue.

**Comment by barentsen** [comment]
This is a bug.  We need to make sure that a helpful error message is printed when a user tries to use `interact()` in the terminal.  @gully can you look into this?

**Comment by barentsen** [comment]
I made a new issue to make sure we add a friendly error message (#154) so we can close this.
