### ISSUE TITLE
[DOC]: some maths are not being rendered correctly in the SFF tutorial

### ISSUE THREAD

**Issue by mirca** [KeplerGO/lightkurve#128]
The arclength integral is not correctly rendered

![screen shot 2018-05-22 at 9 56 34 am](https://user-images.githubusercontent.com/13077051/40363656-8cada6f4-5da6-11e8-9f74-d1af55069433.png)

**Comment by mirca** [comment]
I don't think it's your fault, I tried to build the docs as well and got the same error

**Comment by mirca** [comment]
Ok, fixed that in https://github.com/KeplerGO/lightkurve/commit/7ea99d532041118a99630014ce70c858d5854c46

**Comment by barentsen** [comment]
Thank you @mirca!! :+1:
