### ISSUE TITLE
The LightCurve remove_nans method functionality changed --- now breaks a tutorial

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#129]
**The LightCurve remove_nans method functionality changed --- now breaks a tutorial** 

Short version:

The "Science with lightkurve" tutorial "How to perform aperture photometry with custom apertures" 
is now broken after using the LightCurve remove_nans method.

Long version:

In the "Science with lightkurve" tutorial "How to perform aperture photometry with custom apertures" an attempt is made to clean up a combined light curve using the LightCurve remove_nans method:

![screen shot 2018-05-29 at 9 29 47 am](https://user-images.githubusercontent.com/17578185/40673081-908dec3c-6325-11e8-93f7-416c13589e0a.png)

![screen shot 2018-05-29 at 9 30 10 am](https://user-images.githubusercontent.com/17578185/40673047-768249b4-6325-11e8-8915-54868f63c8d9.png)

It appears that the remove_nans method now works with single quarter light curves
(see cell#5 above) and but **not** with  *combined light curves created using the append method*.

-Ken Mighell
mighell@noao.edu

**Comment by KenMighell** [comment]
Looks like the error is  not in the remove_nans method but rather in the append method.

![screen shot 2018-05-29 at 12 42 44 pm](https://user-images.githubusercontent.com/17578185/40681397-db2fbd70-633d-11e8-849a-d3cd3556dc4e.png)

This is the source for the append method:

![screen shot 2018-05-29 at 12 43 51 pm](https://user-images.githubusercontent.com/17578185/40681458-020c273a-633e-11e8-8c8c-ee678c616bff.png)

Note that the cadenceno array is not appended with np.append like all the other arrays.

-Ken Mighell
mighell@noao.edu

**Comment by KenMighell** [comment]
The new one-line addition of 

    new_lc.cadenceno = np.append(new_lc.cadenceno, others[i].cadenceno)

in the LightCurve append method given in the lightcurve.py file in my 
pull request #130 should probably be replaced with the following:

    if hasattr(new_lc, 'cadenceno'):
        new_lc.cadenceno = np.append(new_lc.cadenceno, others[i].cadenceno)

I did not realize that only some (not all) LightCurve objects have a cadenceno array.

-Ken Mighell
mighell at noao dot edu

**Comment by KenMighell** [comment]
Pull request https://github.com/KeplerGO/lightkurve/pull/132 implements this suggested addition to the LightCurve append method:

    if hasattr(new_lc, 'cadenceno'):
        new_lc.cadenceno = np.append(new_lc.cadenceno, others[i].cadenceno)

This 2-line change is more general than the 1-line change of Pull request https://github.com/KeplerGO/lightkurve/pull/130 and should work for Kepler **and** generic LightCurve objects.

-Ken Mighell
mighell at noao dot edu

**Comment by mirca** [comment]
Thanks for the contribution @KenMighell!
