### ISSUE TITLE
Implement breakpoints method in SFFCorrector

### ISSUE THREAD

**Issue by mirca** [KeplerGO/lightkurve#134]
This issue is just to add a minor note that this method currently raises a ``NotImplementedError``.

**Comment by christinahedges** [comment]
@mirca this docstring is kind of opaque:

`     Return a break point as a function of the campaign number.
        The intention of this function is to implement a smart way to determine
        the boundaries of the windows on which the SFF algorithm is applied
        independently. However, this is not implemented yet in this version. `

What exactly do you want this function to do?

**Comment by mirca** [comment]
Usually the data within a given campaign experiences different profiles of motion systematics. Splitting the lightcurve on those times where the systematics are different would help to infer the motion profile more accurately. This process is done, albeit hard-coded, in K2SC.

**Comment by christinahedges** [comment]
Ok, cool. How would a 'break point function' work or what it would do? Will it return the point where the motion vectors change (roughly the middle of the campaign), or will it break a light curve at the best point and apply SFF?

**Comment by mirca** [comment]
> Will it return the point where the motion vectors change (roughly the middle of the campaign)

I believe that would do the trick. Data gaps, for example, could also be used as breakpoints.

**Comment by barentsen** [comment]
I'm closing this issue due to ~1 year of inactivity.  Of course improvements to SFF continue to be welcome as part of new issues and PRs!
