### ISSUE TITLE
Automagically generate priors using Gaia

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#137]
Priors are currently a pain in PSF photometry with lightkurve. I would like a function that automagically creates uniform priors for the

* RA
* Dec
* Flux

based on Gaia values. The flux priors may have to be quite wide, to allow for any source variability and errors in zeropointing Kepler to Gaia. 

This will be satisfying, as this is really prior information. 

We will then use the work from #111 to create priors on the motion of the spacecraft.

This has the added benefit of knowing how many sources are in a given target pixel file, as we will know from Gaia how many will be above the noise floor.

- [ ] Investigate the zero-point for Gaia G to Kepler magnitude.
- [ ] Create a tool that silently queries Gaia 
- [ ]  Find out how many sources are in the target pixel file (return only those that are above the noise floor of Kepler.)
- [ ] Use the pmra and pmdec from Gaia to ensure the RA Decs are correct for the Kepler epoch
- [ ] Use Gaia RA/Dec/pmra/pmdec errors to and flux zeropoint to return an `oktopus.UniformPrior` object. (For background you can use an average background value)

**Comment by christinahedges** [comment]
@gully, what are your thoughts?

**Comment by gully** [comment]
Let's separate out the "Create a tool that silently queries Gaia", to be its own atomic feature / issue, since that functionality is applicable to other purposes like the interactive "TPF sky view" tool we have on the (metaphorical and literal) drawing board.  The presently proposed function--a good idea-- hinges on such a tool existing.

**Comment by barentsen** [comment]
I'm closing this issue because it is >1 year old and we are not actively working on PRF photometry at this time.  Automatically generating priors from Gaia is a very good idea and hopefully it will be part of future revisions to the prf sub-package some day.
