### ISSUE TITLE
from_archive() should return a new 'Collection' class instead of a list.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#138]
@barentsen:

>  ...`from_archive` should return instances of a new `LightCurveFileCollection` or `TargetPixelFileCollection` class.  The class would behave exactly like a list (we can subclass a class from the collections module), but have an extra method called `plot` to quickly plot all the lightcurves or tpfs in a quicklook plot, so the code would look like this:
> 
> lcfiles = KeplerLightCurveFile(blabla, radius=blabla)
> lcfiles.plot()

This sounds great to me. Much better than a list. We can make sure it has a clear repr and if people try to use methods (e.g. to lightcurve) it provides a clear warning error.

How do we want to index the collection though? It might be nice if we're able to specify the keplerid to get back the right tpf:

`tpfc.205189451`
`tpfc[0]`

**Comment by barentsen** [comment]
This begs the question, should cone searches be supported via `KeplerLightCurveFileCollection.from_archive()` or `KeplerLightCurveFile.from_archive()`.  The advantage of the former is that you always know what `from_archive` returns, the disadvantage is that it is yet another class that users need to remember and import.

**Comment by christinahedges** [comment]
Yeah...it's true. I don't know what the answer is here. Perhaps we need KeplerLightCurveFileCollection.from_archive() and tpf.conesearch? 

tpf.conesearch would return a KeplerLightCurveFileCollection

**Comment by barentsen** [comment]
I like `KeplerTargetPixelFile.conesearch()`.  Alternatively, it could be a module-level function (i.e. `from lightkurve import keplertpfsearch`).  The choice between the two depends on readability and ease of use. I guess the former wins in that regard.

**Comment by barentsen** [comment]
Noting here that if we move the conesearch functionality from `from_archive()` to `conesearch()`, we have to update the rolling band tutorial (#113), and possibly other tutorials.

**Comment by barentsen** [comment]
We can close this issue because `from_archive` has now been deprecated in favor of `search_targetpixelfile` and `search_lightcurvefile`, and this new interface supports returning a collection class.

For example: `search_targetpixelfile("Kepler-10").download_all()` returns a `TargetPixelFileCollection` object.
