### ISSUE TITLE
from_archive() returns two target pixel files if you ask for quarter 11 K2 data

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#139]
This is actually expected behavior because there are two campaigns. Similarly if you use

`KeplerTargetPixelFile.from_archive('K2TargetName', quarter=9)`

You will get back two TPFs, one from 9a and one from 9b. If you want just one of them you have to ask for 

`KeplerTargetPixelFile.from_archive('K2TargetName', quarter=91)`

I think this is good behavior but it's not what people expect when they do from_archive, they're expecting just one TPF? 

I think this will be alleviated by #138 which will throw an error if people try to e.g. use to_lightcurve() on a collection.

**Comment by christinahedges** [comment]
@barentsen how do you feel about this behavior?

**Comment by barentsen** [comment]
I'm getting ever more convinced that the Right Way forward is to have `from_archive` always return either 1 file or a helpful error message, and require the use of `conesearch` for multiple files. It's going to be less confusing!

**Comment by christinahedges** [comment]
Yep I think that sounds good to me.
