### ISSUE TITLE
pytest-cov should be a dependency

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#140]
Tests don't run unless users have pytest-cov installed. This should be a dependency? @barentsen can you fix this?

**Comment by mirca** [comment]
It's already there: https://github.com/KeplerGO/lightkurve/blob/master/setup.py#L31

**Comment by christinahedges** [comment]
That's weird the interns couldn't run the unit tests because they didn't have py.test-cov installed. Why is that?

**Comment by christinahedges** [comment]
I care @mirca.

Alright no problem then, closing! Thanks!

**Comment by barentsen** [comment]
We should explain this in the docs!
