### ISSUE TITLE
PRFPhotometry can fit values outside of uniform priors.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#142]
PRFPhotometry is trying to fit a PRF outside of the priors I've specified.

![screen shot 2018-06-06 at 4 06 38 pm](https://user-images.githubusercontent.com/14965634/41069646-bda94aa2-69a3-11e8-991a-416179629bfc.png)

**Comment by christinahedges** [comment]
Lower bound and upper bounds were flipped around. Whoops.

**Comment by mirca** [comment]
I fixed that on oktopus side. Now, a ``ValueError`` is raised in this case.

**Comment by christinahedges** [comment]
@mirca. You hero.
