### ISSUE TITLE
MAST Portal does not return light curve files for K2 Campaign 2

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#143]
Siegfried Vanaverbeke reported the unexpected error below via e-mail.  I diagnosed the issue to be the fact that K2 Campaign 2 lightcurves (released at K2 MAST on 5/4/18) are not accessible via the MAST Portal API yet.

@scfleming or @mustaric can you have a look?  Thanks++.

```
In [1]: from lightkurve import KeplerLightCurveFile
In [2]: lcf = KeplerLightCurveFile.from_archive(205483258)
   ...: 
WARNING:root:Target return limit set to 1 but only 0 unique targets found. Try increasing the search radius. (Radius currently set to 1.0 arcseconds)
---------------------------------------------------------------------------
ArchiveError                              Traceback (most recent call last)
<ipython-input-2-6f79dc2d1334> in <module>()
----> 1 lcf = KeplerLightCurveFile.from_archive(205483258)

/home/gb/dev/lightkurve/lightkurve/lightcurvefile.py in from_archive(target, cadence, quarter, month, campaign, radius, targetlimit, verbose, **kwargs)
    141                     target=target, filetype='Lightcurve', cadence=cadence,
    142                     quarter=quarter, campaign=campaign, month=month, verbose=verbose,
--> 143                     radius=radius, targetlimit=targetlimit)
    144         if len(path) == 1:
    145             return KeplerLightCurveFile(path[0], **kwargs)

/home/gb/dev/lightkurve/lightkurve/mast.py in download_kepler_products(target, filetype, cadence, quarter, month, campaign, radius, targetlimit, verbose, **kwargs)
    272                                       radius=radius, targetlimit=targetlimit)
    273     if len(products) == 0:
--> 274         raise ArchiveError("No {} File found for {} at MAST.".format(filetype, target))
    275 
    276     # For Kepler short cadence data there are additional rules, so find anywhere

ArchiveError: No Lightcurve File found for 205483258 at MAST.
```

**Comment by scfleming** [comment]
Hi Geert,

Yep, I caught this a little while ago and is literally being done now and in testing very soon, should be out in a matter of days.  This is mostly on me, the data may have been public while I was on travel or busy and forgot to initiate the whole process for getting them updated.

**Comment by barentsen** [comment]
Thanks @scfleming!

Note: I believe this may be the first K2 Campaign for which we released short-cadence lightcurves (in addition to long cadence ones).  This may or may not be a caveat!

Thanks+++

**Comment by scfleming** [comment]
Yep, also adding short cadence for c2, c15 and c16 with this incoming update.

**Comment by svaverbe** [comment]
How do we have to choose between long cadence and short cadence in Lightkurve ?

**Comment by barentsen** [comment]
@svaverbe: the syntax is

`lcf = KeplerLightCurveFile.from_archive(target, cadence='long')`

or

`... cadence='short'`

**Comment by scfleming** [comment]
@svaverbe @barentsen Campaigns 2, 15, and 16 (both long and short) and now in the Portal and also should be available in the API.  Please let me know if you encounter any problems!

**Comment by barentsen** [comment]
@scfleming Awesome!!  I confirm the issue posted above has been resolved! :tada::balloon:

**Comment by svaverbe** [comment]
Indeed the issue seems to have been solved. 

 

Thanks,

 

Siegfried

 

Van: Geert Barentsen [mailto:notifications@github.com] 
Verzonden: donderdag 14 juni 2018 00:05
Aan: KeplerGO/lightkurve <lightkurve@noreply.github.com>
CC: svaverbe <sigfried.vanaverbeke@telenet.be>; Mention <mention@noreply.github.com>
Onderwerp: Re: [KeplerGO/lightkurve] MAST Portal does not return light curve files for K2 Campaign 2 (#143)

 

@scfleming <https://github.com/scfleming>  Awesome!! I confirm the issue posted above has been resolved! 🎉🎈
