### ISSUE TITLE
lightkurve should have a logger

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#145]
There should be a lightkurve logger that we can use to print error messages and warnings to the users.

**Comment by barentsen** [comment]
Agreed!  I think it should be a very lightweight wrapper around Pythons built-in `logging` module.

**Comment by christinahedges** [comment]
Yeah I recommend we use logging too, it doesn't even really need a wrapper you just need to great an object and then use it for warnings/info/debug messages

**Comment by christinahedges** [comment]
Fixed in #150
