### ISSUE TITLE
Downloading target from archive returns data for a different, nearby star

### ISSUE THREAD

**Issue by benmontet** [KeplerGO/lightkurve#148]
It's trying so hard to do a good job, but accidentally grabs a star 4 arcsec away (both have defined and downlinked apertures, which happen to touch each other)

```
from lightkurve import KeplerTargetPixelFile, LightCurve
tpf = KeplerTargetPixelFile.from_archive(6507433, quarter=8)


> Found 1 File(s)
> Downloading URL https://mast.stsci.edu/api/v0/download/file?uri=mast:Kepler/url/missions/kepler/target_pixel_files/0065/006507427/kplr006507427-2011073133259_lpd-targ.fits.gz to ./mastDownload/Kepler/kplr006507427_lc_Q011111111111111111/kplr006507427-2011073133259_lpd-targ.fits.gz ...

```
The star it gets is one pixel away from the one I want. My guess is that there's a radius search behind the scenes, and there's some bad conversations to and from RA and Dec and it's not accounting for the fact that it knows the true KIC of the target I want? But that's just a guess on my part.

Still <3 Lightkurve!

**Comment by barentsen** [comment]
Thank you for reporting this @benmontet!  I believe your diagnosis is spot on.

We may be able to solve this by explicitely passing `target_name` to the `astroquery.mast` interface when something looks like an EPIC or KIC id. I believe we didn't do this because we thought this may never be an issue.  Identifying an EPIC for which this is an issue is super helpful. Let's make it a unit test!

**Comment by barentsen** [comment]
@benmontet This bug fix is now live on pypi as part of `lightkurve v1.0b7`.  Can you let us know whether you are, indeed, a happy Ben?

**Comment by benmontet** [comment]
It is working for me locally on v1.0b7. I am indeed a happy Ben. But let's be honest, I am already happy every time I get a chance to interact with your lovely team!

**Comment by barentsen** [comment]
True!  I am happy every day I get to interact with our lovely team!
