### ISSUE TITLE
Docstrings need to clarify that Kepler times are in TDB

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#149]
The times in the Kepler data products are in the Barycentric Dynamical Time frame (TDB), which is a time system that does not include the leap seconds.  We need to make sure that lightkurve clarifies this in the docstrings that relate to times.  We can refer to Section 2.1.2 of the Kepler Archive Manual for details.

**Comment by JeffLCoughlin** [comment]
Yes it's good to be specific that BKJD given in the FITS files is BJD_TDB and has been corrected to account for leap seconds from UTC, as opposed to BJD_UTC which would include visible leaps in the data.

**Comment by barentsen** [comment]
This has been fixed as part of #159!  Closing ...
