### ISSUE TITLE
tpf should have a method to output the time in human date.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#15]
It would be useful for people to be able to see light curves with dates instead of MJD. We can use astropy.time.Time and datetime to create a tpf.time_readable or something similar. These objects also plot up nicely.

**Comment by barentsen** [comment]
Agreed!  `k2flix` has three useful BKJD<>BJD<>JD conversion functions which we may want to port to `lightkurve` (and test thoroughly), here:

https://github.com/barentsen/k2flix/blob/master/k2flix/core.py#L59

Other conversion can indeed be done using Astropy (which doesn't support BKJD).
