### ISSUE TITLE
Injection and recovery tool for lightkurve

### ISSUE THREAD

**Issue by ssagear** [KeplerGO/lightkurve#161]
Instrumental artifacts often make it difficult to distinguish real astrophysical phenomena on long timescales. Lightkurve could include a tool for injection and recovery to quantify the extent of instrumental artifacts on astrophysical signals of interest. These signals could include supernovae, transits, rotation and flares.

I propose a method in the `lightcurve` class called `.inject` that will inject a known astrophysical signal, e.g. a supernova light curve from [sncosmo](http://sncosmo.readthedocs.io/en/v1.6.x/) or a planetary transit from [ktransit](https://github.com/mrtommyb/ktransit).  One could also add a `.recover` method.

**Comment by ssagear** [comment]
**Discovery of Available Parameters**

.inject_sn right now allows the user to choose the source of the supernova model (if it is built into sncosmo), but it depends on the user already knowing what parameters are taken by that source.  The method should be able to tell the user what parameters a certain source takes.

**Synthetic Light Curve Class**

It might also be good to have a "synthetic lightcurve" class that will inherit from the lightcurve class:
```python 
class SyntheticLightCurve(LightCurve):
```
This class would inherit from LightCurve and also include attributes specific to a synthetic lightcurve, e.g. planet period/radius, supernova type, etc.  This will specify that the synthetic light curve is **not** real data.

**Comment by ssagear** [comment]
**Normalization of Light Curves**

All light curves will be normalized to 1.0 - supernova signals will be added, and transit signals will be multiplied. This assumes no background flux (background flux is additive) - maybe add a flag.

**Units of Supernova amplitude**

Convert the model output from sncosmo from [photons/s/cm^2] to [electrons/s]
([electrons/s] must then be converted to counts).

**Comment by ssagear** [comment]
**Implementation of Inject Methods**

We might include methods like .inject.supernova() or .inject.transit() instead of different methods for each astrophysical signal we want to inject.  

@barentsen raises the possibility of supporting adding models to lightcurves:
```python
model = some_func(parameters)
synth_lc = model + data_lc
```
`model` only possesses a functional form, but is not actually a model light curve.
We have decided to revisit these abstractions after some experimentation with building directly into the `LightCurve` class.

We would do so by overriding the `__add__` method like so:

```python
def __add__(self, other):
        copy_self = copy.copy(self)
        if other.is_instance(SpecialModelClass):
             #evaluate the model at these time points
             synth_flux = other.create(self.time)
             merged_flux = copy_self.flux + synth_flux
             return merged_flux
        else:
             copy_self.flux = copy_self.flux + other
             return copy_self       
```

**Comment by barentsen** [comment]
Closing this issue because it hasn't been active for >12 months.  Improved injection/recovery tools remain a very good idea however.
