### ISSUE TITLE
TargetPixelFileFactory automatically sets WCS to wrong coordinates

### ISSUE THREAD

**Issue by Emmavt** [KeplerGO/lightkurve#166]
Hi all,
#### Problem description
I have run into some issues when using the Kepler TargetPixelFileFactory to cut out TPFs from superstamp images, namely that the WCS is taken from a template file. The WCS is still there in the TPF object, but it is incorrect, as it has been taken from this template file. Christina and I discussed the issue, and think that in order to resolve it, either the WCS needs to be passed along or no WCS should be in the resultant TPF. Thank you very much. 

#### Example
<img width="763" alt="screen shot 2018-06-20 at 16 17 40" src="https://user-images.githubusercontent.com/40405209/41689459-836d3ce2-74a5-11e8-8982-87cd0247f779.png">

**Comment by christinahedges** [comment]
This can be fixed by just removing the WCS from the template. We could also fix TPFFactory to pass along the WCS to the final file, that may be harder.

**Comment by Emmavt** [comment]
I have found that this is also an issue with the column and row, which are also being taken from the template file.

**Comment by amcody** [comment]
I have solved this problem in my local version of the code (err, the code that TPFfactory originated from, TPFmaker). It's still a bit of a kludge, but I can share when I'm in next. I think what I did was to rewrite the row, column, and RA/Dec solution in the template so that they're correct. We can explore other options. Also need TPFfactory to calculate and save pos_corr values.

**Comment by barentsen** [comment]
When we added `TargetPixelFileFactory` just before the tess.ninja meeting, we did not have time to implement proper treatment of the WCS.

@amcody could you or @Emmavt work on preparing a PR that provides a more permanent solution in lightkurve?  I wonder if the solution is to adjust the CRPIX1 and CRPIX2 keywords to reflect the fact that an area has been cut out?

**Comment by amcody** [comment]
Yes, CRPIX1,2 and some other header keywords are what I changed. I am going to upload my revised TPFmaker code to github, and then @Emmavt can take a look and see if she can port the changes over to TargetPixelFileFactory.

**Comment by barentsen** [comment]
This issue was resolved by #243.  Closing!
