### ISSUE TITLE
Lightkurve tutorial uses deprecated plot functions

### ISSUE THREAD

**Issue by johnnyzhang295** [KeplerGO/lightkurve#170]
The current matplotlib plot() function defaults to a linestyle which makes it difficult to see individual plotted points. As a result, the plots that new users create will look different than the tutorial images.

Use  `.plot(linestyle=' ')` to get plots that match the tutorial.

**Comment by barentsen** [comment]
We overhauled the plotting as part of #228, so this will be addressed once we re-compile all the tutorials as part of #268.  Closing for now!
