### ISSUE TITLE
Add instructions for running unit tests to the docs

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#171]
The instructions should also explain the difference between running `pytest` and `pytest --remote-data`.

**Comment by texadactyl** [comment]
I added --remote-data as a command line parameter to setup.cfg:
```
[aliases]
test=pytest

[tool:pytest]
addopts = -x --doctest-modules --ignore=setup.py --cov=lightkurve --remote-data
```

Is that the recommended way to run tests dependent on remote data?

**Comment by brennv** [comment]
Running `python setup.py test` seems like it's raising two issues:

```
_____________________ ERROR collecting docs/source/conf.py _____________________
docs/source/conf.py:23: in <module>
    import sphinx_rtd_theme
E   ModuleNotFoundError: No module named 'sphinx_rtd_theme'
=========================== 1 error in 0.08 seconds ============================
```

Which can be resolved by adding another `--ignore` to `setup.cfg` for `docs/source/conf.py`.

The second issue is:

```
==================================== ERRORS ====================================
___________________ ERROR collecting lightkurve/__init__.py ____________________
lightkurve/__init__.py:14: in <module>
    from .prf import *
lightkurve/prf/__init__.py:1: in <module>
    from .prfmodel import *
lightkurve/prf/prfmodel.py:11: in <module>
    from ..utils import channel_to_module_output, plot_image
lightkurve/utils.py:13: in <module>
    import matplotlib.pyplot as plt
../venvtest/lib/python3.7/site-packages/matplotlib/pyplot.py:2374: in <module>
    switch_backend(rcParams["backend"])
../venvtest/lib/python3.7/site-packages/matplotlib/pyplot.py:207: in switch_backend
    backend_mod = importlib.import_module(backend_name)
/usr/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
../venvtest/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py:1: in <module>
    from . import _backend_tk
../venvtest/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py:5: in <module>
    import tkinter as Tk
/usr/lib/python3.7/tkinter/__init__.py:36: in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
E   ImportError: libtk8.6.so: cannot open shared object file: No such file or directory
=========================== 1 error in 0.99 seconds ============================
```

Which might be resolved by using a `matplolib.use('Agg')` [workaround](https://stackoverflow.com/a/4935945/6085135).

**Comment by barentsen** [comment]
Thank you for trying this and offering workarounds, @brennv!

Right now we are testing lightkurve using the command `pytest --remote-data`, however I think it would be good to fix the bugs you encountered while running `python setup.py test`.  Any takers?

**Comment by texadactyl** [comment]
The pip and pip3 libraries have been in flux.  I got some weird package version failures yesterday and this morning.  Just now, running `python3 setup.py test`:

without `--remote-data`
TOTAL Stmts   Miss  Cover 4037    951    76%
113 passed, 42 skipped, 15 warnings in 38.57 seconds

with `--remote-data`
TOTAL  Stmts   Miss  Cover 4037    360    91%
152 passed, 3 skipped, 18 warnings in 175.98 seconds

Running on Xubuntu Linux 18.0.1 on an x64 platform.

**Comment by texadactyl** [comment]
I use python3 so that I can employ the Spyder IDE.  Once you execute a downloaded version of lightkurve (or any other multi-source collection), you should stick to the same Python version since the compiled pyc files are imprinted with the characteristics of that particular version of Python.  E.g. Executing Python 2 after running Python 3 gets some interesting Super() failed assertions - which make sense.

Of course, normal use of lightkurve through the pip (Python 2) or pip3 repositories will not run into what I described above.

**Comment by barentsen** [comment]
Thanks everyone for the insights you shared above!  I revisited this issue and have two improvements to report:
1. The fabulous @christinahedges recently added a `How to run the unit tests?` page to our online docs, i.e. `docs/source/about/testing.rst` which is visible at https://docs.lightkurve.org/about/testing.html
2. `setup.py` was recently improved such that `python setup.py test` now works, though the preferred way of running the tests is explained in the new docs page.

Thanks everyone!  I think this issue can be closed, but please do open a new one if new issues arise!
