### ISSUE TITLE
Docs: demonstrate how to load a local target pixel file

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#172]
Both the quickstart guide and the "what are target pixel files?" tutorials in the docs only use `KeplerTargetPixelFile.from_archive()`.  We need to add an example of opening a local file from disk.

(I just received a query from a user who couldn't figure out how to open a local file.)

**Comment by IsFlwrs** [comment]
I'd like to take this on. Can you provide some details on the issue please?

**Comment by barentsen** [comment]
@IsFlwrs Hi!  The source of our documentation lives under the `docs` directory of this repository.  We compile it by running `make html` in that directory (using the `sphinx` documentation framework), and for every release we upload the new version to http://lightkurve.keplerscience.org

Recently a few users contacted me to ask how they can read a local target pixel file using lightkurve.  This can be done using `tpf = KeplerTargetPixelFile(path)`, however our quickstart and many of the examples in our current documentation only show the feature to download the data directly from the archive, i.e. `tpf = KeplerTargetPixelFile.from_archive(targetid)`.

We should simply add the standard version of reading a file locally, i.e. `tpf = KeplerTargetPixelFile(path)`, to the quickstart and 1 or 2 places in the basic tutorials, to make it more clear that this is an alternative way of loading data!

Does that help?
