### ISSUE TITLE
We should add Guy Davies code too!

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#178]
For @christinahedges and @johnnyzhang295, here is Guy Davies astro code! We should get some mash up of this and the code from #114 implemented!

https://gist.github.com/christinahedges/2de4a94fc192e4ff193b733e42d219a4

**Comment by barentsen** [comment]
@ojhall94 is working on this as part of #266.  I believe he will be aware of Guy's code.  Closing!
