### ISSUE TITLE
Add a from_file() function to load FITS lightcurve file

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#192]
#### Problem description
Attempting to use lightkurve to read in a FITS lightcurve file (e.g., ktwo246802680-c13_llc.fits), it was not straightforward in the documentation/tutorials how to do it. I suggest adding a from_file() function to mirror the well-documented w/ example from_archive() function.

#### Example

By asking staff, I was able to use the following commands to load a lightcurve file, but I did not see it as an example in the documentation.

```python
from lightkurve import KeplerLightCurveFile
lcf = KeplerLightCurveFile("ktwo246802680-c13_llc.fits")
```

I think if there was a from_file() function, it would be more obvious that a user that could load using from_archive() or from_file():

```python
from lightkurve import KeplerLightCurveFile
lcf = KeplerLightCurveFile.from_file("ktwo246802680-c13_llc.fits")
```

#### Expected behavior
Expect intro tutorial to show how to load from a local file as well as the archive.

#### Environment:
Linux
1.0b9
pip

**Comment by barentsen** [comment]
Agreed this can make it more obvious!  Regarding the name, options I can think of include `from_file`, `from_fits`, `from_url`, `from_path`?

Also see #172 and #176 which improve the docs regarding this issue.

**Comment by JeffLCoughlin** [comment]
Now that you mention it, I like from_fits to differentiate from other possible formats (CSV file or even matlab or who knows what down the road...)

**Comment by JeffLCoughlin** [comment]
I pip installed lasted version, and confirm KeplerLightCurveFile.from_fits() works like a charm. Many thanks!
