### ISSUE TITLE
Tutorial Not Straightforward On Plotting From Non-Notebook Python

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#193]
#### Problem description

After loading a lightcurve file, I followed the tutorial to make a plot. However, the plot never displayed, and no error message was shown. After talking to staff I had issue additional matplotlib commands that were not in the tutorial. Admittedly I am a python neophyte, but I suggest adding a message to the tutorial about reccomeding to run in a notebook, or that additional set-up may be required for plots to show if not in a notebook.

#### Example

Issuing these commands:

```python
from lightkurve import KeplerLightCurveFile
lcf = KeplerLightCurveFile("ktwo246802680-c13_llc.fits")
lcf.plot()
```

produces only the message:

```<bound method KeplerLightCurveFile.plot of KeplerLightCurveFile(EPIC: 246802680)>```

And no plot shows up. It turns out I neeed to issue the additonal commands:

```
import matplotlib.pyplot as plt
lcf.plot()
plt.show()
```

And then the plot window shows up.

#### Expected behavior
Excepted to be able to open regular python, follow the tutorial, and get the same results. Turns out I needed to issue additional commands that weren't specified, or be in an iPython notebook enviroment.

#### Environment:
Linux
1.0b9
pip

**Comment by gully** [comment]
Note, this issue just arose with Jim Davenport also.
