### ISSUE TITLE
Lightkurve should include a vetting tool that finds FFI images of the opposite region of the focal plane to look for saturated stars that might cause cross talk. 

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#199]
Lightkurve should include a vetting tool that finds FFI images of the opposite region of the focal plane to look for saturated stars that might cause cross talk. This would enable unusual signals to be quickly vetted against bright contaminant stars.

There's no easy way to currently 'find' the opposing modules.

**Comment by JeffLCoughlin** [comment]
Great idea!

Just to be pedantic, across the field of view (reflection off the field-flattener lens) is traditionally referred to as 'anti-podal reflection'.  CCD cross-talk is contamintation from an object at the same row and column on other output of the same module. A tool to look for both, or a tool for each, would be very cool (although cross-talk is far more common than anti-podal reflection.)

**Comment by barentsen** [comment]
Closing this issue because it is 1+ years old.  Please do re-open if someone wants to work on this!! :+1:
