### ISSUE TITLE
Use interact() with Short-Cadence Data

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#201]
#### Problem description
When attempting to use intereact() on short-cadence TPF file, a RunTimeError comes up due to having more than 20,000 cadences. 

#### Example

```
from lightkurve import KeplerTargetPixelFile
tpf=KeplerTargetPixelFile("ktwo212460519-c17_spd-targ.fits")
tpf.pipeline_mask
tpf.interact()
```

```
 BokehJS 0.12.16 successfully loaded.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-141-79d3753be6aa> in <module>()
      4 tpf=KeplerTargetPixelFile("ktwo212460519-c17_spd-targ.fits")
      5 tpf.pipeline_mask
----> 6 tpf.interact()
      7 

/home/jeff/anaconda2/lib/python2.7/site-packages/lightkurve/targetpixelfile.pyc in interact(self, lc)
    459         # https://github.com/bokeh/bokeh/issues/7490
    460         if len(lc.cadenceno) > 30000:
--> 461             raise RuntimeError('Interact cannot display more than 20000 cadences.')
    462 
    463         # Map cadence to index for quick array slicing.

RuntimeError: Interact cannot display more than 20000 cadences.
```

#### Expected behavior
Ideally either a TPF could be trimmed to only include a certain cadence or time range, or interact() could have a variable that controls only including every Nth data point, or intereact() could have a cadence or time range as an input. Any of these options could get cadences < 20000 to allow interact() to work and perform smoothly.

#### Environment:
- Linx
- 1.0b9
- pip

**Comment by gully** [comment]
At the CoolStars20 hack day, @nattieg and @rrpastro worked on this Issue alongside the "pixel selector" functionality.  Pull Request  #216 contains a Jupyter notebook demoing some of the approaches we tried.

**Comment by gully** [comment]
Some additional comments from @nattieg provided by email:

>Looks like other folks are interested in a range slider widget that I envisioned on Saturday:
https://github.com/jupyter-widgets/ipywidgets/issues/1351

> In particular the implementation shown here is pretty perfect: http://jsfiddle.net/omnosis/Swd9S/

> If this also allows for a max range to be set, it would be a super slick implementation of what we were doing at the hack day. A reminder, that we wanted to make the interact function usable for short or long-cadence light curves, but we have to limit the amount of the short cadence curve shown due to memory issues. So, if the maximum range allowed was, say, 10000, with a range slider the user could look at any range up to that value and drag the bar back and forth to see different regions of the light curve.

> To make what is currently there a little more user-friendly, this morning I pushed a change making the range setting optional. If the ranges aren't defined by the user they default to 0-3000, which covers most of the range for long-cadence targets.

**Comment by barentsen** [comment]
Nice!!  Thank you @nattieg and @rrpastro !! :+1:

**Comment by gully** [comment]
The new `.interact()` tool that is about to be released ( #216 ) does not support short cadence yet.  The next step for interact is to add a module that detects whether the input TargetPixelFile is short cadence and, if so, adds a slider like the one @nattieg made at cool stars.  Using bokeh widgets makes this task much easier now, so I am confident we will be able to resolve this issue soon.

**Comment by gully** [comment]
Hooray!  The recent TPF slicing feature has made it possible to use interact in short cadence! 

### Before-- without TPF slicing
```python
len(tpf.cadenceno)
115213

tpf.interact() # Does not work -- too many cadences!
RuntimeError: Interact cannot display more than 30000 cadences.
```

### New behavior with TPF slicing


```python
# works with manual index slicing
tpf[1000:4500].interact()  # This works!


# works with boolean masking 
mask = (tpf.time > 3298) & (tpf.time < 3300)
len(tpf[mask].cadenceno)
2919

tpf[mask].interact() # This also works!
```

### Known Limitations

- It'd be nice to be able to define the slicing windows *on the fly*, i.e. with the range sliders suggested above.  That's possible!  We can do it if there's user interest.
- Slicing with non-unit steps has undesired effect of "greying-out" the missing cadences, for example if you want to show every 30th cadence, the other 29 are shown as gray postage stamps, instead of dropped.

**undesired behavior**
```python
tpf[::30].interact() # Does not work!
```

**Comment by gully** [comment]
I'm going to close this issue since Short Cadence interact is now possible, albeit with some loss of the "big picture".  If anyone out there wants a *range slider* for interactively defining the short cadence data window size, please open an issue requesting this feature.  

Note that this slicing should work for both Kepler/K2 and TESS data!  Enjoy!
