### ISSUE TITLE
Cadences with NaN Timestamps are Being Removed by from_archive() Without Readily Apparent Warning or Documentation

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#222]
#### Problem description
KeplerLightCurve is apparently removing cadences that have NaN values for time, without warning the user. There does not appear to be an option to import a lightcurve and preserve these cadences. This does not appear to be documented (or at least readily visible).

#### Example
This target is known to have NaN timestamps. No cadences are identified with NaN timestamps after importing it.

```jupyter notebook
from lightkurve import KeplerLightCurveFile, LightCurve
target = 7672940
lc = KeplerLightCurveFile.from_archive(target, quarter=1).PDCSAP_FLUX
for q in range(2,17):
    lc = lc.append(KeplerLightCurveFile.from_archive(target, quarter=q).PDCSAP_FLUX)
import numpy as np
lc.time[np.isnan(lc.time)]

array([], dtype=float64)
```

Reading the documentation at https://lightkurve.keplerscience.org/api/lightkurve.lightcurvefile.KeplerLightCurveFile.html  there does not appear to be an option to recover the NaN timestamps, and there does not appear to be any mention of removing cadences with NaN timestamps.

#### Expected behavior
If fetching data from the archive, I expect to get the exact set of data that is publicly available without modification. If any modification is done, the user should be informed.

#### Environment:
Linux
1.0b13
pip

**Comment by barentsen** [comment]
A default quality bitmask is applied when opening a `KeplerLightCurveFile`.  The default mask filters out cadences with the flags which are listed here: https://github.com/KeplerGO/lightkurve/blob/master/lightkurve/utils.py#L45

In this case, cadences with time equal to NaN are flagged by the `NO DATA` quality flag.  A user can configure the bitmask that is applied using the `quality_bitmask` parameter.  For example, here is how you maintain the NaN times in your example:
```
from lightkurve import KeplerLightCurveFile, LightCurve
target = 7672940
lc = KeplerLightCurveFile.from_archive(target, quarter=1, quality_bitmask=0).PDCSAP_FLUX
for q in range(2,17):
    lc = lc.append(KeplerLightCurveFile.from_archive(target, quarter=q, quality_bitmask=0).PDCSAP_FLUX)
import numpy as np
lc.time[np.isnan(lc.time)]
```
Returns:
```
array([nan, nan, nan, ..., nan, nan, nan])
```

I don't think we should bother users with warning messages about cadences that have no value, however it is true that the docs should be more explicit about the default quality mask that is applied.  Does that make sense @JeffLCoughlin?

**Comment by JeffLCoughlin** [comment]
Ah I confirm that works nicely with quality_bitmask=0.  Excellent.

I note though that setting quality_bitmask="none" as the documentation suggests does not appear to work.  quality_bitmask="none" returns "KeyError: 'none'"

I confirm quality_bitmask="default"  does work fine.

Should I open a separate issue for this? Or am I doing something silly?

```
from lightkurve import KeplerLightCurveFile
target = 7672940
lc = KeplerLightCurveFile.from_archive(target, quarter=1, quality_bitmask="none").PDCSAP_FLUX
for q in range(2,17):
    lc = lc.append(KeplerLightCurveFile.from_archive(target, quarter=q, quality_bitmask="none").PDCSAP_FLUX)
import numpy as np
lc.time[np.isnan(lc.time)]

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)
<ipython-input-22-cd72082aa8f5> in <module>()
      1 from lightkurve import KeplerLightCurveFile, LightCurve
      2 target = 7672940
----> 3 lc = KeplerLightCurveFile.from_archive(target, quarter=1, quality_bitmask="none").PDCSAP_FLUX
      4 for q in range(2,17):
      5     lc = lc.append(KeplerLightCurveFile.from_archive(target, quarter=q, quality_bitmask="none").PDCSAP_FLUX)

/home/jeff/anaconda2/lib/python2.7/site-packages/lightkurve/lightcurvefile.pyc in from_archive(target, cadence, quarter, month, campaign, radius, targetlimit, **kwargs)
    206                 radius=radius, targetlimit=targetlimit)
    207         if len(path) == 1:
--> 208             return KeplerLightCurveFile(path[0], **kwargs)
    209         return [KeplerLightCurveFile(p, **kwargs) for p in path]
    210 

/home/jeff/anaconda2/lib/python2.7/site-packages/lightkurve/lightcurvefile.pyc in __init__(self, path, quality_bitmask, **kwargs)
    152         super(KeplerLightCurveFile, self).__init__(path, **kwargs)
    153         self.quality_bitmask = quality_bitmask
--> 154         self.quality_mask = self._quality_mask(quality_bitmask)
    155 
    156     @staticmethod

/home/jeff/anaconda2/lib/python2.7/site-packages/lightkurve/lightcurvefile.pyc in _quality_mask(self, bitmask)
    234 
    235         if isinstance(bitmask, str):
--> 236             bitmask = KeplerQualityFlags.OPTIONS[bitmask]
    237         return (self.hdu[1].data['SAP_QUALITY'] & bitmask) == 0
    238 

KeyError: 'none'
'''

**Comment by JeffLCoughlin** [comment]
Ah I just saw on another comment

> As part of 7dc76ac <https://github.com/KeplerGO/lightkurve/commit/7dc76acd32e5b86079f434e164920e52889324e9> I have added support for the string 'none', and listed this more explicitely as an option in the docstrings.

So if that's the case that commit will fix my 'none' issue, then you can ignore my comment above not working, as it looks like this will go live in the next release, and this can be closed.

**Comment by barentsen** [comment]
@JeffLCoughlin Right, `quality_bitmask="none"` will only work if you are using the current `master` branch of the git repository (and pulled in the last day or so).

Thanks for checking!!
