### ISSUE TITLE
`quality_bitmask` should have an option to mask no cadences

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#224]
New feature request for KeplerTargetPixelFile

#### Problem description

The quality_bitmask parameter of KeplerTargetPixelFile
should have the option of "raw" or "all" to allow the user to
see the actual QUALITY values in the TPF FITS file.

**Comment by barentsen** [comment]
It is already the case that passing `quality_bitmask=None` or `quality_bitmask=0` has the effect of returning all cadences, i.e. nothing is masked out.

As part of 7dc76acd32e5b86079f434e164920e52889324e9 I have added support for the string `'none'`, and listed this more explicitely as an option in the docstrings.

Please re-open the issue if you feel further improvements to the docs are needed to clarify that this option exists!

**Comment by KenMighell** [comment]
Hi Geert,

> On Aug 12, 2018, at 1:32 PM, Geert Barentsen <notifications@github.com> wrote:
> 
> It is already the case that passing quality_bitmask=None or quality_bitmask=0 has the effect of returning all cadences, i.e. nothing is masked out.
> 
> As part of 7dc76ac <https://github.com/KeplerGO/lightkurve/commit/7dc76acd32e5b86079f434e164920e52889324e9> I have added support for the string 'none', and listed this more explicitely as an option in the docstrings.
> 
> Please re-open the issue if you feel further improvements to the docs are needed to clarify that this option exists!
> 
That was an easy fix!

Cheers,

-Ken
