### ISSUE TITLE
Unable to Open Fits Lightcurve Files

### ISSUE THREAD

**Issue by johnnyzhang295** [KeplerGO/lightkurve#233]
I get this error 
`KeyError: "Key 'SAP_QUALITY' does not exist."`
when trying to read in a lightcurve .fits file using the path initialization, i.e. 
`lc = KeplerLightCurveFile('my_lightcurve.fits')`

**Comment by barentsen** [comment]
I can't reproduce this using a random Kepler light curve file from MAST.   How did you create `my_lightcurve.fits`?

**Comment by johnnyzhang295** [comment]
@barentsen  I used lightcurve's `to_fits()` function!

**Comment by johnnyzhang295** [comment]
After opening my .fits file with astropy, it looks like lightcurve's `to_fits()` function only saved `[('TIME', '>f8'), ('FLUX', '>f4'), ('FLUX_ERR', '>f4'), ('CADENCENO', '>i4')]` in my BinTableHDU.
