### ISSUE TITLE
a way to know the un-phase-folded time in a folded light curve

### ISSUE THREAD

**Issue by zkbt** [KeplerGO/lightkurve#237]
#### Enhancement description
Thanks to @christinahedges's updates in #228, we'll be able to color individual data points in a `lc.scatter()`. One extra feature that would be nice, for pedagogical (and maybe scientific) purposes, would be to be able to say something like
```
folded = lc.fold(period)
folded.scatter(c=lc.time)
```
so that the colors indicate the un-phase-folded time. 

#### Proposed solution 
Right now, `lc.fold` sorts the data by their phase-folded time. This is necessary to make line plots look sensible, but it means you don't have an easy way to figure out what the original time was for each phase-folded point. I suggest modifying the `FoldedLightCurve` class so that it can keep track of an `original_time` attribute, as well as the phase-folded `time` attribute. Then, we'd be able to do
```
folded = lc.fold(period)
folded.scatter(c=folded.original_time)
```
with lots of delightful colors.

I'm happy to write this change + test and submit it as a PR, if y'all think this sounds OK. Any proposals for a different attribute name than `original_time`?

**Comment by barentsen** [comment]
Thanks @zkbt!  I agree that adding an `original_time` attribute is a good solution.  I don't particularly like the name `original_time` but I can't think of a better suggestion!

You'd be very welcome to submit a PR if you wanted to! :heart:

**Comment by barentsen** [comment]
I wonder if *every* LightCurve object should have a `parent` attribute which contains the original LightCurve object from which the current object was created (or `None` otherwise).

The `parent` attribute would be set by all methods that create a new LightCurve from an existing one, including `fold`, `bin`, `flatten`, `correct`, etc.

The main drawback I see is that it will increase the memory cost of a LightCurve object significantly upon each operation. This may not stop us, but it will be useful to check how expensive this change would be.

**Comment by christinahedges** [comment]
I like the idea of keeping history, but I'm not sold about keeping a lightcurve after every new method. Can we keep the "original" once and then a record of every command applied to it in the `lc.history` string?

**Comment by barentsen** [comment]
But if we only keep `original` then the color-plotting issue won't be resolved, e.g. this won't work:
```
folded = lc.bin().fold()
folded.scatter(c=folded.original.time)
````
(of course binning a lightcurve before folding is a silly thing to do, but other operations may alter the `time` attribute as well)

I do quite like `parent`; it can exist in addition to a `history` attribute of course.

**Comment by barentsen** [comment]
Of course the merit of the `original` attribute is that you can get back to the true, original lightcurve very easily, without having to do `lc.parent.parent.parent.parent`.  Let's brainstorm in person and report back on this issue!

**Comment by barentsen** [comment]
I opened PR #348 which makes the original time array available in a folded lightcurve as `lc.time_original`.  (Or should it be `lc.original_time`?  I could easily be convinced! =))

**Comment by barentsen** [comment]
PR #348 has been merged.  @zkbt I believe we resolved your issue (shout if not), thank you for reporting!!
