### ISSUE TITLE
TPF Factory has real value defaults 

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#241]
#### Problem description

When we create a TPF using the TPFFactory, the template file has default values for e.g. column, row, the WCS. This means that any file created with the factory has these values set.

#### Example

e.g. Here is a new asteroid TPF, which has a wrong column and row number from being created with the TPF factory.
![image](https://user-images.githubusercontent.com/14965634/45325616-4234fc00-b506-11e8-9e44-2ad9e093c4d2.png)

#### Expected behavior

There shouldn't be any defaults in the template file.

**Comment by barentsen** [comment]
Issue should have been fixed as part of #243.  Closing!
