### ISSUE TITLE
Explain the notion of a `quarter` in the starter tutorials

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#247]
Currently the quickstart tutorial uses data from a specific quarter without explaining what a quarter is or why we chose that specific quarter.  I think we should add a short sentence to the quickstart to acknowledge this, and explain the notion of quarters in more detail in a later tutorial.

(This was originally reported by @GiantSable in #246.)

**Comment by JoseALermaIII** [comment]
I also found a decent explanation of quarters on the [Kepler Data Product Page](https://keplerscience.arc.nasa.gov/data-products.html#kepler-data-release-notes)
