### ISSUE TITLE
Trigger a warning if time=NaN are present

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#252]
If a `TargetPixelFile` is opened with `quality_bitmask=None`, it is likely that some of time values are NaN  (usually these are cadences that have the NO DATA quality flag set).

The presence of cadences with time=NaN break several of the methods on the LightCurve class.  I do think it is valuable to allow the user to not mask out any cadences at all, but we should add a warning, likely in the constructors of LightCurve and TargetPixelFile, to warn users!

**Comment by barentsen** [comment]
For anyone who wants to work on this: warnings can simply be issues using the `log.warning(text)` command!

**Comment by JoseALermaIII** [comment]
I'll see what I can do!
What should the warning say? For now, I'm adding `Warning: NaN times are present` using `log.warning(msg)`; however, should it be more specific?

Like, `Warning; NaN times are present. Use a quality_bitmask != None`?
