### ISSUE TITLE
remove_nans doesn't work

### ISSUE THREAD

**Issue by decaelus** [KeplerGO/lightkurve#256]
#### Problem description

lightkurve.lightcurve.FoldedLightCurve.remove_nans doesn't seem to remove nans at all.

#### Example

```python
import numpy as np
from lightkurve import KeplerLightCurveFile

KIC = 4570949
lc = KeplerLightCurveFile.from_archive(str(KIC), quarter=3, verbose=False).PDCSAP_FLUX
print(len(lc.flux[np.isnan(lc.flux)]))
lc.remove_nans()
print(len(lc.flux[np.isnan(lc.flux)]))
```
The result prints as 
6
6
which suggests to me that there are as many nans before as after applying remove_nans.

#### Expected behavior

I expected the flux array to no longer contain nans.

#### Environment:
- platform (e.g. Linux, OSX, Windows): OSx
- lightkurve version (e.g. 1.0b6): 1.0b15
- installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thank you for reporting this issue @decaelus!  We'll look into this asap.

**Comment by decaelus** [comment]
Apologies for my confusion. It might be good to say that the changes are not made in place in the documentation, but this helps clear things up for me.

Thanks again for the great package.

**Comment by barentsen** [comment]
Fair point, the docs could be more explicit about it!

**Comment by gully** [comment]
We could also consider adding an `inplace` operator.  I am inclined to keep the current behavior for the purpose of method chaining.
