### ISSUE TITLE
Update the `interact` tutorial to reflect the new interface

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#258]
The `interact()` tool now allows pixel masks to be selected using the mouse (PR #216).  We need to update our `interact` tutorial to reflect this:

http://lightkurve.keplerscience.org/tutorials/1.05-interact-with-lightcurves-and-tpf.html

Assigning to @gully!

**Comment by gully** [comment]
Here is a proposed gif for this revised tutorial:

![20180924_interact_hltau](https://user-images.githubusercontent.com/860227/45974317-dff3f500-bff5-11e8-8bb1-6754ac9b35bc.gif)

**Comment by barentsen** [comment]
This has been resolved by #262!
