### ISSUE TITLE
Add a way to have interact export the mask

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#265]
The new `.interact()` is great!  It would be even better to have an option that allows reuse of the mask that was generated in the process.  Issue #264 addresses conceivable ways that the mask could be saved.

**Comment by gully** [comment]
Currently thinking about default names for saving the mask:

```
import os

fn = tpf.hdu.filename()
base = os.path.basename(fn)
outname = base.rsplit('_')[0] + '_custom_mask.fits'
```

results in: `ktwo210690913-c13_custom_mask.fits`

Demerit: makes strong assumption for TPF file names (there is exactly one underscore).

**Comment by JeffLCoughlin** [comment]
Maybe replace the .fits on the end with _custom_mask.fits ?  Then there's no assumption on delimeters in the filename.

outname = base.rsplit('.fits')[0] + '_custom_mask.fits'

**Comment by barentsen** [comment]
At the risk of being verbose, I like `base.rsplit('.fits')[0] + '-custom-aperture-mask.fits'`

Real-world example:
```Python
> from lightkurve import search_targetpixelfile
> tpf = search_targetpixelfile("TRAPPIST-1").download()
> print(os.path.basename(tpf.path).rsplit('.fits')[0] + '-custom-aperture-mask.fits')
ktwo246199087-c12_lpd-targ-custom-aperture-mask.fits
```

**Comment by gully** [comment]
Do you think it's misleading to include `targ`, since the output file is no longer a target pixel file?

**Comment by barentsen** [comment]
I'm not worried about that, personally!

**Comment by barentsen** [comment]
The `interact()` tool now has a `Save lightcurve` button which saves both the custom light curve and the aperture mask as a FITS file (cf. #329).  Closing!
