### ISSUE TITLE
Tutorial overhaul

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#268]
As lightkurve has grown, our docs have become outdated.  I propose a bit of an overhaul of the tutorials to bring them up to date with the most recent version.  

lightkurve contributor @ojhall94 has identified some specific bugs, below:

### How to recover a known planet in Kepler data?
 - Plots are no longer scatterplots as depicted in the tutorial
 - The package transit_periodogram, used in this tutorial, has been depricated according to its Github page.
 - In the plot function, need to define ax = ax as a kwarg, the tutorial just lists it as an arg. (This one crops up a lot)

### How to use lightkurve for asteroseismology?
- Do not get identical results to the tutorial, but the differences are negligible.
- Some unexplained terms: CDPP?
- Direct code copied from the tutorial doesn't work anymore: aperture_mask = aper required as a keyword when creating a light curve with a slightly larger aperture.

### How to make a supernova lightcurve?
- A second observation has been made of KSN2015k since the tutorial was made, campaign should be specified to 6.
- tpf interact is commented out in the tutorial example
- tpf interact doesn't seem to work for me, but could be my machine (we've discussed this already, it was the localhost issue)
- tpf interact doesn't work with lc_clean because lc_clean has had frames removed, and so has fewer cadences than the tpf
- None of the tqdm progress bars shown in the tutorial output are in the code anymore

### How to combine lightcurves from different Kepler quarters
- Window length of the flatten() method risks imposing systematics if its not set manually. Might be useful to clarify the meaning of this kwarg in the tutorial so people (like me!) don't learn to use it blindly

My two cents-- I'd like to see the figures rendered high dpi for retina displays, and we should decide whether it's desirable to show `%matplotlib inline` and other configuration lines on every single tutorial.  I propose that we do not, and instead make a new "Troubleshooting" tutorial that introduces how to make those sorts of configuration changes, and addresses questions about how to run demos outside the Jupyter notebook, etc.  We may also want to revisit the notebook naming convention moving forward.

**Comment by gully** [comment]
Idea: should we add a conda `environment.yml` file for lightkurve?  The virtue of such a file resides primarily as a common quick-start environment for tutorials and developers.  

For example, if we want to aid students in running the documentation locally, they would need to clone this repo, then have Jupyter installed, the right bokeh version, etc.  It would be helpful to instruct students to simply run:

```
conda env create -f environment.yml
conda activate lightkurve
```

**Comment by barentsen** [comment]
I'm going to close this issue because it is >1 yr old and the tutorials have undergone a lot of revisions since. Please do open a new issue if further improvements are needed!
