### ISSUE TITLE
Lightkurve should have better names

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#286]
The lightkurve API should have better names. Methods should take the form either `lc.verb()` or `lc.verb_noun()`. Properties should take the form `lc.noun`. This will make it easier for users to understand the API.

**We should use as few different verbs as possible**. More verbs is confusing when you're trying to search for the functions you want. Acceptable verbs:

1. `to_` : indicates a conversion of type
2. `from_` :indicates a new object will be created
3. `estimate_`: indicates values will be built using a method that does not always produce the exact answer.
4. `extract_`: indicates values will be built using a method that **does** always produce the exact answer
5. `show_`: indicates information will be printed
6. `remove_`: indicates cadences/values/properties will be removed from the object

![image](https://user-images.githubusercontent.com/14965634/46705795-fef1aa00-cbe5-11e8-840f-3f87b588e623.png)

**Comment by barentsen** [comment]
This was resolved in #287. Yay!
