### ISSUE TITLE
Retrieve all TPFs per chip

### ISSUE THREAD

**Issue by exowanderer** [KeplerGO/lightkurve#295]
#### Issue description
Is it possible to call for the TPFs as a function of the chip? Or even "all per campaign"

#### Example
```python
import lightkurve
TPFs = lightkurve.KeplerTargetPixelFile.from_archive(chip=42, campaign=0)
```

#### Expected behavior
I expected that the `chip` kwarg is would exist and that the `target` kwarg would not be required; much like `campaign` vs `quarter`, I was expecting `chip` to replace `target`.

I would like to download the TPF files from every target observed, per chip per campaign. Or at least be able to list the EPIC numbers for each TPF per chip per campaign.

#### Environment:
- platform: OSX
- lightkurve version: 1.0b19
- installation method: pip

**Comment by barentsen** [comment]
Unfortunately the MAST Portal API does not support queries on mission-specific meta data at this, such as Kepler CCD identifier.  So far the only work-around is to query targets manually using e.g. the web-based Kepler or CasJobs interfaces at MAST, or to use the older MAST web services (cf. https://archive.stsci.edu/vo/mast_services.html).

Supporting CCD-based searches is on our wish list but we are waiting for the MAST Portal API to support such queries.  Until then, I am going to close this issue.

/cc @mustaric @scfleming

**Comment by exowanderer** [comment]
I wrote this code snippet to do the job; but it requires downloading the entire K2 database from 

`https://exoplanetarchive.ipac.caltech.edu/cgi-bin/TblSearch/nph-tblSearchInit?app=ExoTbls&config=k2targets`

I stored the csv file [updated as of 10/14/2018] on my personal website for me + others to wget:
```bash
# full exoplanetarchive download: 44MB
wget http://www.astro.umd.edu/~jfraine/k2targets.csv

# Only the 2 columns in the full exoplanetarchive download required for this script: 7.3MB
wget http://www.astro.umd.edu/~jfraine/k2targets_campaigns_and_epicIDs_only.csv
```
```python
import pandas as pd
import numpy as np
import lightkurve as lk

try:
    from tqdm import tqdm # progress bar
except:
    print('`pip install tqdm` to make this procedure prettier')
    tqdm = lambda iterable, total=None: iterable

try:
    k2targets = pd.read_csv('k2targets.csv')
except:
    k2targets = pd.read_csv('k2targets_campaigns_and_epicIDs_only.csv')

# Array of possible campaign values in the `k2_campaign` column
campaign_options = np.array(list(set(k2targets['k2_campaign'].values)))

# Array of campaign values in the `k2_campaign` column in order
campaigns_ = k2targets['k2_campaign'].values

c_start = 14 # arbitrary # Campaign start for iterable list
n_campaigns = 1 # number of campaigns to download: set to 1, just to get the ball rolling
n_IDs = 10  # number of EPIC ids to download; set to 10 for test case

# This list can be set to `campaign_options` if all campaigns are desired
campaign_list = campaign_options[c_start:c_start+n_campaigns]

# Setup dict to store values if desired -- not required
k2_lightkurves = {}

# Here we loop over the `campaign_list`, which is defined above as just 1 campaign;
#    but this can be expanded to any number of campaigns (in sequence of not)
for campaign in tqdm(campaign_list, total=len(campaign_list):
    # Allocate the exact EPIC ids to download in the next for loop
    EPIC_ids = k2targets['epic_number'][campaigns_ == campaign].values
    k2_lightkurves[campaign] = {}
    for epic_id in tqdm(EPIC_ids[:n_IDs], total=len(EPIC_ids[:n_IDs])):
        # loop of the allocated EPIC ids and download them one-by-one
        k2_lightkurves[campaign][epic_id] = lk.KeplerTargetPixelFile.from_archive(target=epic_id);
```

**Comment by scfleming** [comment]
Some good news on this front: we have made a new column to CAOM called "sequence_number" available in the table.  This is an integer column that, when populated, will contain the K2 Campaign number and the TESS sector number, meaning you will be able to do a direct query on Campaign/Sector.

Note that the sequence_number *values* aren't populated yet for K2 or K2 HLSP, but they will be in the future.

We are planning on splitting up the Kepler data to so you could then do a filter on Quarter number, but that work is further in the future.

**Comment by barentsen** [comment]
@exowanderer Thank you for sharing this snippet!  Perhaps we should add support for querying the old API.

@scfleming Do you expect queries based on CCD number will be possible in the future, or would you encourage us to script around the old API?

**Comment by barentsen** [comment]
(Also: @scfleming thank you for the fantastic news about the extra CAOM column for campaign/quarter number!!)

**Comment by scfleming** [comment]
I would script around for CCD number at this point, that's less likely to be included as part of the data model, at least in the near future.

**Comment by barentsen** [comment]
@scfleming Do you expect the old API be supported indefinitely?

**Comment by scfleming** [comment]
At this point, my best guess is that the old API will be supported until and unless that functionality is made available in the new API.  So I guess my answer is "no", since it's possible that functionality moves into the new API, and at that point we would almost certainly shut down the old API.

**Comment by barentsen** [comment]
Thanks for the info @scfleming!

**Comment by exowanderer** [comment]
This is all very useful. Thank you both for the helpful conversation.

At this point, does the information that `lightkurve` grabs (even if not in the TPF class) include the chip number? I see `channel`; but I don't know what that means.

If `tpf.channel` is the chip number, then I'm perfectly happy to reconfigure the above script to store the `lightkurve` output as `k2_lightkurves[campaign][channel][epic_id]`.
