### ISSUE TITLE
Plotting KeplerLightCurveFile makes my ipython session unresponsive

### ISSUE THREAD

**Issue by exowanderer** [KeplerGO/lightkurve#296]
#### Problem description
After I successfully plot a KeplerLightCurveFile (from_archive), my entire `ipython` session becomes unresponsive. I am forced to close the terminal that the `ipython` session is contained within

#### Example
```python
import lightkurve as lk
import numpy as np
import pandas as pd

from pylab import *;ion()

k201485699 = lk.KeplerLightCurveFile.from_archive('201485699')
k201485699.PDCSAP_FLUX.plot()
```
Then my `ipython` session crashes (stops responding) with no warnings or errors

#### Expected behavior
I would have expected the `matplotlib` window to open, and then I would be able to use my `ipython` session to continue to plot and/or make other code.

#### Environment:
- platform: OSX 10.13.6
- lightkurve version: 1.0b16
- installation method: `pip install lightkurve`

**Comment by christinahedges** [comment]
Hi @exowanderer, thanks for reporting this issue. I can not reproduce the ipython session crashing, but I can confirm that I cannot get a matplotlib window to open. I'll keep digging and try to figure out what's wrong.

In the mean time, you could try updating to the latest version of lightkurve using 
```
pip install lightkurve --upgrade
```

**Comment by barentsen** [comment]
@exowanderer I notice that you are turning interactive mode on using `ion()`.  What happens if you remove that statement, or if you call `ioff()` and call `show()` manually after issuing the plot command?

**Comment by exowanderer** [comment]
Hello all,

I did update my version with `pip install --upgrade lightkurve` (thank you @christinahedges) and now the issue is no longer as big of a deal. It still 'sticks' a little and responds with an error that I failed to capture ("QE...something").  

Additionally, I *then* turned off `plt.ion()` and the behavior stopped altogether; i.e no console interruption at all. (thank you @barentsen)

So both solutions worked. I strongly prefer to use `plt.ion()`; so I will have to suffer with the momentary non-responsivity of my terminal.

Thank you!

**Comment by exowanderer** [comment]
PS: I apologize that this was probably just a 'versioning' issue; I only install `lightkurve` a few days ago (maybe a week); so I assumed that I had the more updated version.

**Comment by barentsen** [comment]
We release a new version every few days now!

**Comment by exowanderer** [comment]
Whoops: I think I spoke too soon. 

I am now on version 1.0b19; and one of out 10 of my trials completely became completely unresponsive.  This is probably not very helpful of an issue; but if someone else tags in later with "same problem here"; then maybe we can diagnose it.

**Comment by exowanderer** [comment]
And now I have the error that is output when it's sticking

```
QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier
QEventDispatcherMac::unregisterSocketNotifier: Tried to unregister a not registered notifier
```
