### ISSUE TITLE
KeplerLightCurveFile.from_archive() will not download K2-33b

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#30]
I want to use K2-33b for a tutorial but `from_archive()` can't find the EPIC ID: 205117205.
![screen shot 2018-02-22 at 5 34 59 pm](https://user-images.githubusercontent.com/14965634/36573640-cb696072-17f6-11e8-90fc-55c41972bda4.png)
It can find it if I use the RA and Dec.

**Comment by barentsen** [comment]
K2-33 i.e. EPIC 205117205 was observed during Campaign 2, for which the official pipeline has not (yet) delivered lightcurves to MAST.  I just verified that it does work for a target pixel file.

(Are you sure you can get the light curve when querying by RA/Dec?  MAST is being very unresponsive so I haven't been able to verify.)

**Comment by barentsen** [comment]
I just verified that `lc = KeplerLightCurveFile.from_archive("242.5614060 -19.3192730")` does not return a lightcurve either, as expected for a Campaign 2 target.  I'm going to close this issue, but do re-open it if you think something is wrong.

**Comment by barentsen** [comment]
Because in the early days of K2, the pipeline was not able to generate lightcurves.  They are being generated now but now at MAST yet.

(We could look into supporting the retrieval of lightcurves from e.g. Vanderburg, but that's not a feature right now.)
