### ISSUE TITLE
Replace `copy.deepcopy(self)` with `self.copy()` across `lightcurve.py`

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#300]
Thanks to #294, the `LightCurve` class now has a `copy()` method.

This means that we can now replace calls to `copy.deepcopy(self)` with `self.copy()` across the module.  

This should be an easy PR for beginners!

**Comment by rra94** [comment]
I can take this.

**Comment by IvanLudvig** [comment]
I think I did it

**Comment by barentsen** [comment]
I am going to pre-emptively close this issue because 3 PRs have already been submitted to resolve it.  We will review them asap.
