### ISSUE TITLE
Bug Report: KeplerTargetPixelFile opens TESS Target Pixel Files 

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#316]
#### Problem description

KeplerTargetPixelFile() opens TESS Target Pixel Files instead of throwing an exception.

#### Example

```python
import lightkurve as lk
# Assume tp.fits is a TESS Target Pixel File
tpf = lk.KeplerTargetPixelFile('tp.fits'). # works without thowing an exception  :-(
```
While you can look at the headers without problem, using the to_lightcurve() function
will fail because channel information is missing.

 ```python
import lightkurve as lk
# Assume tp.fits is a TESS Target Pixel File
tpf = lk.KeplerTargetPixelFile('tp.fits')
tpf.to_lightcurve(). # <--- crashes because tp.fits is not a Kepler Target Pixel File
```
See the attached PNG file to see the gory details.

#### Expected behavior

Using KeplerTargetPixelFile to open a TESS Target Pixel File should fail and throw an exception.

#### Environment:
- platform : Max OS X (High Sierra)
- lightkurve version:  1.0b19
- installation method: GitHub source

![bug_report](https://user-images.githubusercontent.com/17578185/47802468-8fa33d80-dced-11e8-8cb3-a34e1e81b2be.png)

**Comment by barentsen** [comment]
Thanks @KenMighell!  This looks like a bug we should fix!

**Comment by barentsen** [comment]
@nksaunders Do you want to have a look?  

My initial thinking is that we may want to issue a `LightkurveWarning` (using `warnings.warn`, cf.  https://github.com/KeplerGO/lightkurve/pull/298#issuecomment-430282055) if the TPF does not have MISSION=TESS in the header?

**Comment by KenMighell** [comment]
I think that the fact that to_lightcurve() crashes with a TESS TPF warrants an exception and not just a warning.

-Ken

**Comment by barentsen** [comment]
My worry about raising an exception is that it then becomes hard for a home-made target pixel files to be loaded (or perhaps even future versions of official TESS products).

Two additional mitigation actions we can consider:
* We could make `to_lightcurve` more robust to not crash if the CHANNEL keyword is missing from the TPF (which is why it crashed).
* Similar to `astropy.io.fits.open()`, we could add a more simple `lightkurve.targetpixelfile.open()` function which detects the file type and returns the appropriate object. This will help users to avoid making the mistake!

**Comment by KenMighell** [comment]
Ok. Warning it is.

-Ken

**Comment by nksaunders** [comment]
I agree that `to_lightcurve` should be callable without needing Kepler-specific keywords to make home-made tpfs user friendly.

For this specific case, creating a `TessTargetPixelFile` works, and the `to_lightcurve` function will not crash.

Maybe calling `KeplerTargetPixelFile` on an object missing Kepler-specific keywords should return a generic `TargetPixelFile` object with a warning. I think a generic tpf object would make using custom tpfs from fits files easier. Thoughts?

**Comment by barentsen** [comment]
As part of #338, `tpf.to_lightcurve()` will no longer crash if the TPF has no CHANNEL keyword.

**Comment by barentsen** [comment]
With #340 merged, a clear warning message is now raised when opening a TESS product using a Kepler class (though `to_lightcurve()` does work if you wanted to).

![screenshot from 2018-11-20 18-15-15](https://user-images.githubusercontent.com/817669/48814647-65430f80-ecf0-11e8-9dec-4c92c3aadcc9.png)

I believe this resolve this issue.  Thank you for reporting @KenMighell!
