### ISSUE TITLE
Bug Report: TessLightCurveFile() opens TESS Target Pixel Files without throwing an exception

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#318]
#### Problem description

TessLightCurveFile() opens TESS Target Pixel Files without throwing an exception

#### Example

```python
import lightkurve as lk
obj = lk.TessLightCurveFile('tp.fits')  # tp.fits is a TESS Target Pixel File
# ^--- this works instead of throwing an exception
```

#### Expected behavior

It should have thrown an exception (wrong file type) instead of accepting the wrong file type

#### Environment:
- platform: Mac OS X (High Sierra)
- lightkurve version:  1.0b19
- installation method: GitHub source

**Comment by barentsen** [comment]
Thanks to #340, opening a taget pixel file using the light curve file class raises a clear warning message:

![screenshot from 2018-11-20 18-10-55](https://user-images.githubusercontent.com/817669/48814476-bb638300-ecef-11e8-8e7c-de1ba863c884.png)

We opted not to raise an exception for now, to enable creative uses of the class using unofficial data products.

**Comment by barentsen** [comment]
:arrow_up: I believe this resolves the issue, so I'm going to close this.  Thank you for reporting @KenMighell!
