### ISSUE TITLE
Mark known spurious frequencies in a Kepler `Periodogram`?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#324]
The [Kepler Data Characteristics Handbook](https://archive.stsci.edu/kepler/manuals/Data_Characteristics.pdf) contains a wonderful table listing all the known spurious frequencies in Kepler short cadence data (plus explanations).  I wonder if we should provide an easy way to plot them, e.g. `Periodogram.plot(show_spurious=True)`.  Unfortunately this is Kepler-specific so it would make `Periodogram` a lot less generic.

![screenshot from 2018-11-02 17-05-55](https://user-images.githubusercontent.com/817669/47945767-95517c80-dec1-11e8-9558-d85dfc8b8f0d.png)

**Comment by barentsen** [comment]
Slightly different idea: should we emit a warning if e.g. the `estimate_numax()` method returns one of the spurious frequencies?  (Caveat: Periodogram does not know if the data came from Kepler or TESS.)

**Comment by JeffLCoughlin** [comment]
Great idea. Couple caveats / ideas:

- From the footnotes, looks like it likely wasn't updated past Q7, so frequencies have likely shifted / change quarter-to-quarter.

- As you note some of these could be totally different for K2, and campaign-dependant.

- I made a note to ask Doug, Steve et al. how these were calculated back in the day. My guess is based off the PDC CBVs. If so, (or even if they did it another one), one idea is to calculate them for all K2 campaigns based on the CBVs for each, which should capture well characteristic frequencies --- if useful to community, this strikes me as a good project potentially for @KenMighell

**Comment by barentsen** [comment]
I'm going to close this issue for now because it hasn't come up yet as something that is required by an active use case.  We can re-open when a well-identified need for this feature appears!
