### ISSUE TITLE
Implement a transit masking feature

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#327]
Various trend and systematics removal methods will benefit from the ability to mask out known planet transits before "fitting the trend" to be removed.  To make this easy, we should consider:
1. Providing an easy method to generate an appropriate transit mask, e.g. `mask = LightCurve.create_transit_mask(phase, period, duration)`?
2. Have our detrending/correction methods accept such mask, e.g. `LightCurve.flatten(transit_mask=mask)`?  Those methods will then require some interpolation of the trend over the transit points.

Any thoughts on this feature or its ideal design?

For inspiration, Everest implements transit masking as follows: https://rodluger.github.io/everest/using_everest.html#masking-transits

**Comment by nksaunders** [comment]
This is a great idea, and would be very useful for a `PLDCorrector`.

I think the ideal structure would be an array of indices to be masked, which can be passed into the `PLDCorrector` implementation of the `Corrector` class. This would allow users to use `create_transit_mask(phase, period, duration)` to generate a mask, or pass a custom mask (as was the case with Everest).

A useful diagnostic plot would be the light curve with masked indices clearly marked.

**Comment by barentsen** [comment]
Good news: a `LightCurve.create_transit_mask()` method has been added to Lightkurve v2.0 by @nksaunders via #808. Thanks Nick!!

Closing!
