### ISSUE TITLE
`errorbar()` provides incorrect x label for folded light curves

### ISSUE THREAD

**Issue by nksaunders** [KeplerGO/lightkurve#328]
Similar to #6: `errorbar()` returns `Time` instead of `Phase` for folded light curves.

![image](https://user-images.githubusercontent.com/17130840/48085724-ef975980-e1af-11e8-8d9f-e2af3e7c41ce.png)

I believe adding a `FoldedLightCurve.errorbar()` wrapper function similar to the existing `.plot()` and `.scatter()` would resolve this issue.

**Comment by barentsen** [comment]
@christinahedges I believe you may or may not have already fixed this before.  Do you want to have a look and open a PR if needed?
