### ISSUE TITLE
TessTargetPixelFile .interact() throws an exception

### ISSUE THREAD

**Issue by jradavenport** [KeplerGO/lightkurve#333]
Using the example alert data on MAST, TessTargetPixelFile works to read the TPF in, but `.interact()` crashes with the following error message:
````python
from lightkurve.targetpixelfile import TessTargetPixelFile
tpf = TessTargetPixelFile('tess-data-alerts/hlsp_tess-data-alerts_tess_phot_00260304296-s02_tess_v1_tp.fits')

tpf.interact()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-102-7bfcb21a8385> in <module>()
----> 1 tpf.interact()

~/anaconda3/lib/python3.6/site-packages/lightkurve/targetpixelfile.py in interact(self, lc, notebook_url, max_cadences)
    583         from .interact import show_interact_widget
    584         return show_interact_widget(self, lc=lc, notebook_url=notebook_url,
--> 585                                     max_cadences=max_cadences)
    586 
    587 

~/anaconda3/lib/python3.6/site-packages/lightkurve/interact.py in show_interact_widget(tpf, lc, notebook_url, max_cadences)
    408 
    409     output_notebook(verbose=False, hide_banner=True)
--> 410     return show(create_interact_ui, notebook_url=notebook_url)

~/anaconda3/lib/python3.6/site-packages/bokeh/util/api.py in wrapper(*args, **kw)

~/anaconda3/lib/python3.6/site-packages/bokeh/io/showing.py in show(obj, browser, new, notebook_handle, notebook_url)
    124 
    125     if not (isinstance(obj, LayoutDOM) or is_application or callable(obj)):
--> 126         raise ValueError(_BAD_SHOW_MSG)
    127 
    128     # TODO (bev) check callable signature more thoroughly

~/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py in add_root(self, model, setter)
    241 
    242         '''
--> 243         from ..server.callbacks import NextTickCallback
    244         cb = NextTickCallback(self, None)
    245         return self._add_session_callback(cb, callback, one_shot=True, originator=self.add_next_tick_callback)

~/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py in _pop_all_models_freeze(self)
    921         callback_obj._callback = self._wrap_with_self_as_curdoc(actual_callback)
    922         self._session_callbacks.add(callback_obj)
--> 923         self._callback_objs_by_callable[originator][callback].add(callback_obj)
    924 
    925         # emit event so the session is notified of the new callback

~/anaconda3/lib/python3.6/site-packages/bokeh/document/document.py in _recompute_all_models(self)
    929 
    930     def _destructively_move(self, dest_doc):
--> 931         ''' Move all data in this doc to the dest_doc, leaving this doc empty.
    932 
    933         Args:

AttributeError: 'function' object has no attribute 'references'

````

#### Environment:
- MacOS, Python 3.6.6
- lightkurve version 1.0b21
- installation method: pip
- bokeh-1.0.1 updated via conda

**Comment by barentsen** [comment]
Thank you for reporting this issue and providing a detailed stack trace, @jradavenport!

@gully Can you investigate?

**Comment by gully** [comment]
It works for me-- my hunch is that your bokeh version is too new-- 1.0 just came out a few weeks ago and must have some backwards incompatibility changes, which isn't a surprise for a major version release.  I'd recommend pinning bokeh to less than version 1.0, perhaps 0.13 or earlier. 

Note to developers-- let's consider modifying the conda-forge and/or requirements.txt file to pin the bokeh version.

**Comment by barentsen** [comment]
@gully Let's investigate this a bit more.  I am unable to reproduce this issue with bokeh 1.0.1; Linux Python 3.6.6; master branch (which has no changes to interact compared to 1.0b21).  Can you reproduce on your end?

![screenshot from 2018-11-14 08-12-10](https://user-images.githubusercontent.com/817669/48495515-027be080-e7e5-11e8-9ecb-f2b1788b25ac.png)

**Comment by jradavenport** [comment]
OK, I can get the same thing now. Maybe Jupyter was seeing something stale previously.... grumble. Thanks for following up!! 
<img width="1181" alt="screen shot 2018-11-14 at 8 57 32 am" src="https://user-images.githubusercontent.com/3179868/48498757-ba13f100-e7eb-11e8-9369-45ba1b021ed1.png">

**Comment by barentsen** [comment]
@jradavenport Did you make changes to your environment (e.g. `conda update something`) after starting the notebook, and then continue using the notebook without restarting the kernel? That can lead to confusing exceptions with obscure error messages (in this case, Python indicated that the exception occured in a docstring (line 931), which is of course unlikely and can be indicative of this scenario.)

**Comment by jradavenport** [comment]
That must have been what I failed to do yesterday. I did `pip install lightkurve` and then without restarted my kernel it worked A OK! So I forgot to restart it after using `condo install bokeh`.... thumbs down @jradavenport

**Comment by barentsen** [comment]
Thumbs can stay up @jradavenport :+1: -- I have made this mistake many, many times!
