### ISSUE TITLE
Enable `tpf.create_threshold_mask()` to return a contiguous mask

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#337]
### Problem
The `aperture_mask='threshold'` feature of Lightkurve is a bit simplistic in that it returns all pixels above a median flux threshold.  This means that the mask returned is often not contiguous and may include neighbor stars, see e.g. https://github.com/KeplerGO/lightkurve/pull/231#issuecomment-439681783.  Although we could keep this behavior as an option, most of the time users will want a smarter mask.

### Possible solutions
I am aware of four possible ways to make the threshold feature smarter.
It could return the contiguous mask that...
1. contains the center pixel;
2. contains the brightest pixel (in terms of median flux);
3. contains the largest number of pixels; or
4. contains the most flux.

Thoughts?  I wonder if option 4 makes the most sense.

### Example implementation
Here's an example implementation of scenario 2 written by @mrtommyb as part of his original PR [#231]:
```Python
# identify pixel above the threshold and label contiguous regions
threshold_region = np.where(median_image > mad_cut, 1, 0)
labeled_values = label(threshold_region)[0]

# find brightest pixel
brightest_pixel_y, brightest_pixel_x = np.unravel_index(median_image.argmax(), median_image.shape)
region_value = labeled_values[brightest_pixel_y, brightest_pixel_x]
aperture_mask = np.where(labeled_values == region_value, 1, 0)
return aperture_mask.astype(bool)
```

**Comment by mrtommyb** [comment]
Thanks @barentsen. I think this is going to be more important for TESS thanks Kepler due to the greater crowding. The target I was looking at is a pretty good test case. I would guess that you would (almost?) always want the one that includes the central pixel

**Comment by barentsen** [comment]
I suppose that most traditional TPFs, as well as TESS cut-outs, intend to place the target of interest in the center of the TPF.  So I agree we should probably go with "the most central mask".

Possible pseudocode:
```Python
central_pixel_arg = np.argmin(np.hypot(x - center_x, y - center_y))
central_pixel_x, central_pixel_y = x[central_pixel_arg], y[central_pixel_arg]
region_to_use = labeled_values[central_pixel_y, central_pixel_x]
aperture_mask = np.where(labeled_values == region_to_use, 1, 0)
```

**Comment by barentsen** [comment]
@christinahedges Would you be willing to see if the above is easy to implement, and open a PR if so?

**Comment by gully** [comment]
How about using [cluster labels with mahotas](https://mahotas.readthedocs.io/en/latest/labeled.html) for crowded fields?  It's what Ben Montet uses in [f3](https://github.com/benmontet/f3).

**Comment by barentsen** [comment]
I had a quick go at solving this in #345.  It will need testing.
