### ISSUE TITLE
Review installation and quickstart instructions

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#339]
@amcody Can you review the docs at https://docs.lightkurve.org and identify issues that need to be resolved to help brand new users get started, prior to releasing v1.0?  Feel free to open PRs as required.

**Comment by gully** [comment]
See recent updates #245 (closed) and #358 (still open) for some updates to the installation instructions and docs.

**Comment by gully** [comment]
Also #171  is related

**Comment by brennv** [comment]
I tested quickstart and installation for a development setup with no issues. Also #358 got merged.

**Comment by gully** [comment]
Chatting with @amcody about this issue right now--

related themes:
- conda installation hasn't been well-tested
- we're adding more tutorials in #360 
- Consider adding TESS data to the quickstart guide to avoiding having to dig far into the tutorials

**Comment by amcody** [comment]
I hereby confirm that I had no problems (re-)installing lightkurve via conda in a new environment and playing dumb new user. Everything worked as specified. I would just echo the above comment that we need to provide a few more notes about how this works with TESS.

**Comment by amcody** [comment]
(And sorry for the delay on this @barentsen, I just discovered that I had everything *but* the personal mentions set to email me upon new notification. Whoops!! Now fixed. )

**Comment by texadactyl** [comment]
See [http://docs.lightkurve.org/install.html](url)
Installing by name ("lightkurve") is covered for both pip and conda.  But, installing the development version is only covered for pip.

**Comment by texadactyl** [comment]
Okay, I'll answer my own question ..... How do you install the development version into an Anaconda environment which is, by the way, not documented?
```
$ conda uninstall lightkurve # else you will wind up with 2 copies (original:conda-forge, new:default) 
$ git clone https://github.com/KeplerGO/lightkurve.git
$ cd lightkurve
$ python3 setup.py install # I bet it works for Python 2.7 too (clip off the '3')
```
When time permits, please add this to the section dealing with development installs - Anaconda flavour.

**Comment by barentsen** [comment]
Thanks for the feedback everyone!

The installation of the development version is now described in the docs, here: https://docs.lightkurve.org/about/contributing.html

I'm going to close this issue, but feel free to open a new one if further improvements to the docs are needed.  Thanks everyone!
