### ISSUE TITLE
Support for one-fell-swoop masking and user-defined outlier rejection

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#34]
Currently, the `remove_outliers()` method in `lightcurve` does not support user-defined masks.  With some discussion, Geert and I think that we could support direct masking, e.g.:

```python
lc_masked = lc[mask]
```

where mask is a boolean mask.  Geert points out that we'd have to implement dunder methods: 
https://docs.python.org/3/reference/datamodel.html#object.__getitem__

A backup approach could be to support an `input_mask` kwarg in `remove_outliers`:

```python
def remove_outliers(self, sigma=5., return_mask=False, input_mask=None, **kwargs):
        # [...]
        new_lc = copy.copy(self)
        if input_mask is not None:
            outlier_mask = input_mask
            #some checks to make sure the input_mask is the correct shape...
        else:
            outlier_mask = sigma_clip(data=new_lc.flux, sigma=sigma, **kwargs).mask
        new_lc.time = self.time[~outlier_mask]
        new_lc.flux = self.flux[~outlier_mask]
```

**Comment by gully** [comment]
Related problem, a bug actually:

```python
lc.flux.shape, lc.quality.shape
```

yields
`((294,), (435,))`

since `lc.quality` is not masked in remove_outliers

**Comment by barentsen** [comment]
Over in #37 slicing has been implemented using `__getitem__` and `remove_outliers()` has been edited to make use of slicing, which got rid of the big.  Please review and re-open the issue if you have any concerns!

**Comment by barentsen** [comment]
Just for clarity: user-defined masks are now easy to apply, e.g. you can do
`new_lc = lc[np.abs(lc.flux - np.mean(lc.flux)) > 3*np.std(lc.flux)]`
