### ISSUE TITLE
Add aperture_mask as a class attribute to LightCurve

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#341]
The aperture mask is a part of the provenance of any Kepler/K2/TESS lightcurve procured through conventional aperture photometry conducted with pre-defined or custom-specified apertures.  Storing the aperture mask as a piece of lightcurve metadata seems fair, or even natural, to enable the inter-comparison of lightcurves generated through different means.  

Issue #265 revealed a strategy for how to store an optional `aperture_mask` metadata blob:

> All the data written by `LightCurve.to_fits()` are currently stored as class attributes. I think we'll want the same with aperture_mask, *i.e.* I think we'll want `aperture_mask` to become an optional attribute that can be passed to the constructor of `LightCurve`? If set, `to_fits` would then write `self.aperture_mask` as an optional extension.

**Comment by gully** [comment]
Q: will we need to add extra metadata to associate the mask back an origin?  For example, in the TESS era, does the aperture mask refer to the full frame (huge!) or a "postcard", or a 2-minute window?  How would one know without additional metadata?

**Comment by barentsen** [comment]
My recommendation is to add `aperture_mask` as an optional argument of `lc.to_fits()` for now.

I don't think we want to add it as a class attribute right now.  As you point out: it is not clear that an `lc.aperture_mask` attribute is useful without provenance information.

I think we should focus on our immediate goal of adding a "*Save Lightcurve*" button to interact, which allows someone to capture the lightcurve and mask in a single fits file.  This would be enabled in a very simple and effective way by accepting the mask as an optional argument in `to_fits()`.

I think it would be too ambitious for Lightkurve v1.0 to provide deep reproducibility features, which is why I think it's fine to take a pragmatic shortcut here!

**Comment by gully** [comment]
@christinahedges I assigned this issue to you since I think you built `to_fits()`, and you mentioned opinions on whether-to-not to add aperture_mask as a special kwarg in `to_fits()`, as is currently proposed in the Issue and PR linked above.  Geert suggests above the kwarg workaround for now.  What do you think?

**Comment by gully** [comment]
Discussions in #264 shed new light on this Issue.

Derived products usually originate from a data product file, having undergone some number of reduction steps.  This reduction step provenance is generally inaccessible given the `KeplerLightCurve` object alone.  That information loss extends to ignorance of masks: there is presently no way to tell what mask generated a `KeplerLightCurve`.  That ignorance is partly intentional, since `LightCurve` objects may have arisen through any number of means, including point-spread-function photometry, for which the notion of a mask is undefined.  

Some special cases may seem to defy this claim: *e.g.* the `KeplerLightCurveFile.SAP_FLUX` object and their `Tess*` and `*.PDCSAP` counterparts.  In principle, one can reverse engineer the mask from access to the original KeplerLightCurveFile with `(klcf.hdu[2].data & 2) == 2` where `klcf` denotes a local `KeplerLightCurveFile` object.  But once someone does `klc = klcf.SAP_FLUX`, information is presently lost if you have the `klc` alone. 

|lightkurve object| Mask provenance | lightkurve mask access|
| -- | -- | -- | -- |
|`KeplerLightCurve` | unknown | none|
|`TessLightCurve` | unknown  | none|
|`LightCurve` | unknown  | none|

The mere existence of the current Issue hinges on some assumptions, the validity of which should be questioned in light of discussions surrounding programmatic mask access at #264.

1.  Aperture photometry is a common pathway to generating a LightCurve object
2. Knowledge of the aperture mask is important for: 
  - reproducibility 
  - reporting
  - downstream scientific analysis
3. There are many cases in which someone has access to a `*LightCurve` object without its `*TargetPixelFile` or `*LightCurveFile` counterpart, and therefore cannot access the mask; or affiliating these local objects is inconvenient or error-prone.
4. Users will understand that `LightCurve` objects may or may not have an `aperture_mask` attribute, depending on the provenance (i.e. optional attributes are not confusing).
5. Implementing and maintaining this functionality will be straightforward and "easy".

In my experience and intuition, the answer to the first 4 of these is yes ✅✅✅✅, and the final one is a "probably".  Recent discussions at #264 arrive at different answers to these assumptions, so I am encouraging a broader discussion here about these assumptions and the merits of this feature request.

**Comment by gully** [comment]
After a long discussion we all agreed we do not want to add `aperture_mask` as an attribute to `LightCurve` objects.  The reason for not including this attribute is resides in the complexity to maintain an *optional* feature--- not all LightCurve objects were created using aperture photometry, and eventually ground-based lightcurves may have different apertures altogether, so the aperture mask meaning is lost, and maybe even misleading.  The aperture may also lose meaning when referring to non-standardized data products like TESS Cutout TPFs.  KeplerLightCurveFiles on the other hand, are associated with apertures, and already have ways to access their default pipeline masks.  Those access methods may be inconvenient (using `klcf.hdu[-1].data ==3` doesn't roll off the tongue), but they're possible.
