### ISSUE TITLE
[Bug] Calling `.flatten()` on an SFF-corrected lightkurve raises an IndexError

### ISSUE THREAD

**Issue by nksaunders** [KeplerGO/lightkurve#346]
#### Problem description
There seems to be an error with how arrays are being sliced to define new lightcurve parameters. I discovered this issue when trying to find the cdpp of an sff-corrected lightcurve, which raises the error when trying execute the `.flatten()` step. 

#### Example
```python
import lightkurve
lc = lightkurve.search_lightcurvefile(247887989).download().PDCSAP_FLUX
lc.correct().estimate_cdpp()
```
#### Resulting Error
<img width="972" alt="screen shot 2018-11-21 at 11 44 54 am" src="https://user-images.githubusercontent.com/17130840/48865143-84d74800-ed83-11e8-886a-6527e8833166.png">

#### Code Snippet
This section of code is the source of the error.
<img width="639" alt="screen shot 2018-11-21 at 11 46 26 am" src="https://user-images.githubusercontent.com/17130840/48865036-2b6f1900-ed83-11e8-9a0b-1e987e384bc8.png">

**Comment by barentsen** [comment]
I believe PR #347 fixes the issue.  Please review!
