### ISSUE TITLE
Should `lc.fold()` take a `transit_midpoint` or `t0` argument?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#357]
Right now `LightCurve.fold()` takes the arguments `period` and `phase`.  During a heated debate :fire:, we wondered if it would be more useful to have it take `transit_midpoint` instead of `phase`, because `transit_midpoint` is more commonly available (e.g. in the NASA Exoplanet Archive it is available with parameter name `pl_tranmid`).

@christinahedges Would you be willing to prepare a PR?

**Comment by JeffLCoughlin** [comment]
It makes sense to me to use transit midpoint (epoch). Without reading the documentation, just seeing "phase" is ambiguous to me as to what the input is asking for.

**Comment by christinahedges** [comment]
Yep I agree, let's switch it to transit midpoint!
