### ISSUE TITLE
[DOC] Replace phase with transit_midpoint

### ISSUE THREAD

**Issue by brennv** [KeplerGO/lightkurve#364]
#### Problem description
#361 swapped out arg *phase* in favor of *transit_midpoint* for `lc.fold` but the docs still use *phase*

#### Example

Snippet from http://docs.lightkurve.org/tutorials/how-to-recover-the-first-tess-candidate.html gives a TypeError
```python
folded_lc = clipped_lc.fold(period=6.27, phase=0.4)

TypeError: fold() got an unexpected keyword argument 'phase'
```
But this works just fine:
```
folded_lc = clipped_lc.fold(period=6.27, transit_midpoint=0.4)
```

#### Expected behavior

Docs use current args for `lc.fold`

#### Environment:
- platform (e.g. Linux, OSX, Windows): Linux
- lightkurve version (e.g. 1.0b6): [master](https://github.com/KeplerGO/lightkurve/commits/master) [21833db](https://github.com/KeplerGO/lightkurve/commit/21833db522ec7dd010b28589eff0ab48e904ca84) 
- installation method (e.g. pip, conda, source): `pip install -e .`

#### Proposed change
PR #363 

PS Thank you! Great presentation last night! :+1:

**Comment by barentsen** [comment]
#363 has been merged, and the online docs will be updated accordingly in the next 48 hours.

@brennv thank you for this contribution, and @christinahedges thank you for last night's presentation =)
