### ISSUE TITLE
interact() fails on TESScut TPFs

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#373]
`interact()` appears to fail on TESScut TPFs because the CADENCENO column is set to [0, 0, 0, ... 0].

![screenshot from 2018-12-07 14-34-17](https://user-images.githubusercontent.com/817669/49676108-3edddd80-fa2d-11e8-916c-9b54f4f0fd86.png)

Also see https://twitter.com/GeertHub/status/1071172334982094848

**Comment by gully** [comment]
Will investigate.  I suspect a fix to this will require an overhaul of interact, since so much of its indexing relies on the existence of cadences.

**Comment by gully** [comment]
Update: Geert recommends a quick workaround-- arbitrarily assign indices as fake cadence numbers for TESSCut.  Avoids overhauling interact and achieves close to the desired behavior.

**Comment by barentsen** [comment]
This has been resolved as part of #375.  Closing!
