### ISSUE TITLE
TESS Search Won't Find My Target

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#380]
#### Problem description
`lk.search_*` won't find my TESS target given a TIC ID

![image](https://user-images.githubusercontent.com/14965634/49888594-394d1280-fdf4-11e8-8469-de9b25fbc6bd.png)

It does work for some other targets.

This is a real target that MAST recognizes 
![image](https://user-images.githubusercontent.com/14965634/49888610-479b2e80-fdf4-11e8-937e-3ff47fab646b.png)

#### Example

```python
import lightkurve as lk
lk.search_lightcurvefile('TIC 261136679')
```

#### Expected behavior

This LCF should download.
#### Environment:
- platform (e.g. Linux, OSX, Windows): MacOS
- lightkurve version (e.g. 1.0b6): '1.0b24.dev'
- installation method (e.g. pip, conda, source): source

**Comment by christinahedges** [comment]
This was apparently a rather transient problem.

**Comment by barentsen** [comment]
Weird?  Are you saying you can't reproduce the problem?

**Comment by christinahedges** [comment]
I'm saying it was probably my fault....

**Comment by barentsen** [comment]
🙀
