### ISSUE TITLE
Enhancement request: Document how to get the lightkurve version in a Python script.

### ISSUE THREAD

**Issue by texadactyl** [KeplerGO/lightkurve#383]
#### Enhancement request description
Amend documentation to show how to get the lightkurve software version in a Python script.

#### Example
```
from lightkurve import version as lkver
print("lightkurve version =", lkver.__version__)
```

**Comment by barentsen** [comment]
Thanks for the suggestion @texadactyl!

I wonder where this would go.  My first thought it could go either in the installation instructions or on a new FAQ page.

**Comment by texadactyl** [comment]
How about a more formal API and then into the API documentation? Getting the package version could be a utils.py function:
```
def get_version():
     from . import __version__
     return __version__
```

User program snippet:
```
from lightkurve.utils import get_version
print("lightkurve version =", get_version())
```

**Comment by KenMighell** [comment]
In many Python modules, __version__ is a global string (which is why get_version()  works):

So a simpler solution: 

import lightkurve as lk
print lk.__version__

**Comment by KenMighell** [comment]
In many Python modules, `__version__` is a global string (which is why get_version() works):

So... a simpler solution for hacking Python scripts:

`import lightkurve as lk
print lk.__version__`

**Comment by barentsen** [comment]
Our current [installation instructions](https://docs.lightkurve.org/about/install.html) in the online docs demonstrate how to use `lightkurve.__version__` to verify what version of Lightkurve has been installed, so I believe this issue has been resolved! :tada:
