### ISSUE TITLE
lightkurve installation from channel conda-forge causes downgrading

### ISSUE THREAD

**Issue by texadactyl** [KeplerGO/lightkurve#385]
#### Problem description
Currently, lightkurve is not in the default conda channel.  Hence, one follows the documented method of installing lightkurve with conda:

```
conda install --channel conda-forge lightkurve
```

Unfortunately, to push ahead one must accept downgrading of certain packages:

```
The following packages will be DOWNGRADED:

    cryptography:         2.4.2-py27h1ba5d50_0                --> 2.3.1-py27hdffb7b8_0    conda-forge
    curl:                 7.63.0-hbc83047_1000                --> 7.63.0-h74213dd_0       conda-forge
    libarchive:           3.3.3-h5d8350f_5                    --> 3.3.3-h823be47_0        conda-forge
    libcurl:              7.63.0-h20c2e04_1000                --> 7.63.0-hbdb9355_0       conda-forge
    libssh2:              1.8.0-h1ba5d50_4                    --> 1.8.0-h5b517e9_3        conda-forge
    openssl:              1.1.1a-h7b6447c_0                   --> 1.0.2p-h470a237_1       conda-forge
    python:               2.7.15-h9bab390_6                   --> 2.7.15-h33da82c_4       conda-forge
    qt:                   5.9.7-h5867ecd_1                    --> 5.9.6-h8703b6f_2                   
```

There is a similar warning about adds and upgrades.  This could be very undesirable.

#### Environment:
- platform: Xubuntu 18.04.1
- lightkurve version: 1.0b25-py_0
- installation method: conda install --channel conda-forge lightkurve 

#### Desirable solution:
```
conda install lightkurve # i.e. from the default channel
```
#### Did I miss something that could be put in the documentation for conda users?
Is there a way of plucking out only lightkurve from conda-forge and everything else from the default channel?  If I find a way, I'll add a note here for updating the documentation.

**Comment by texadactyl** [comment]
#### Proposed Solution (documentation amendment)

Document that conda users append the default channel entry with conda-forge so that entries (explicitly requested or as an implied dependency) come from the default channel as long as there an entry in the default channel; else conda will continue searching in conda-forge:
```
conda config --append channels conda-forge # one-time operation
```

Then, the following command works without creating downgrading warnings and stays in the default channel whenever possible for the dependencies:
```
conda install lightkurve
```

#### Sample Output
```
## Package Plan ##

  environment location: /home/elkins/anaconda2

  added / updated specs: 
    - lightkurve


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    scipy-1.1.0                |   py27h7c811a0_2        17.6 MB
    astroquery-0.3.9           |          py_1000         2.6 MB  conda-forge
    lightkurve-1.0b25          |             py_0         245 KB  conda-forge
    mkl_random-1.0.2           |   py27hd81dba3_0         383 KB
    astropy-2.0.9              |   py27hdd07704_0         6.8 MB
    mkl_fft-1.0.6              |   py27hd81dba3_0         191 KB
    autograd-1.2               |             py_1          33 KB  conda-forge
    numpy-base-1.15.4          |   py27hde5b4d6_0         4.2 MB
    bokeh-1.0.2                |           py27_0         5.3 MB
    keyring-17.0.0             |           py27_0          48 KB
    oktopus-0.1.2              |             py_0          13 KB  conda-forge
    numpy-1.15.4               |   py27h7e9f1db_0          47 KB
    ------------------------------------------------------------
                                           Total:        37.5 MB

The following NEW packages will be INSTALLED:

    astroquery: 0.3.9-py_1000         conda-forge
    autograd:   1.2-py_1              conda-forge
    keyring:    17.0.0-py27_0                    
    lightkurve: 1.0b25-py_0           conda-forge
    oktopus:    0.1.2-py_0            conda-forge

The following packages will be UPDATED:

    astropy:    2.0.8-py27h035aef0_0              --> 2.0.9-py27hdd07704_0 
    bokeh:      0.13.0-py27_0                     --> 1.0.2-py27_0         
    mkl_fft:    1.0.4-py27h4414c95_1              --> 1.0.6-py27hd81dba3_0 
    mkl_random: 1.0.1-py27h4414c95_1              --> 1.0.2-py27hd81dba3_0 
    numpy:      1.15.1-py27h1d66e8a_0             --> 1.15.4-py27h7e9f1db_0
    numpy-base: 1.15.1-py27h81de0dd_0             --> 1.15.4-py27hde5b4d6_0
    scipy:      1.1.0-py27hfa4b5c9_1              --> 1.1.0-py27h7c811a0_2 

Proceed ([y]/n)? 
```

Of course, if one wants to prioritise using conda-forge ahead of the default channel for whatever reasons, one can prepend it instead:
```
conda config --prepend channels conda-forge
```

**Comment by barentsen** [comment]
@gully Do you think we have narrow constraints on the conda package that could be relaxed to avoi the issue above, or do you think we should update the documentation as per @texadactyl's suggestion?

**Comment by texadactyl** [comment]
Whatever you do, just remember that your users are scientists who will appreciate a low complexity solution.  (=:

**Comment by texadactyl** [comment]
I tried to reproduce this again today.  There were no downgrades.  Given the dynamic nature of the conda-forge channel, perhaps the inadvertent downgrading (mistake?) might be expected from time to time.

I am closing this report so as to not distract the team from priority work (E.g. science).
