### ISSUE TITLE
"ImportError: No module named _bsddb"

### ISSUE THREAD

**Issue by texadactyl** [KeplerGO/lightkurve#386]
#### Problem description
This is not a lightkurve issue but a warning to folks in the documentation would be helpful in avoiding spending a lot of time chasing around.

In some pip/pip3/conda environments, the bsddb package is not yet installed even after lightkurve and astropy are installed.  Technically, bsddb is not a named installation dependency (ouch, it should be somewhere!).  But it is a Python 2.7 shelve dependency and ought to be dragged in along with shelve.

#### Example
```
from lightkurve import KeplerTargetPixelFile
ktpf = "https://archive.stsci.edu/pub/kepler/target_pixel_files/0069/006922244/kplr006922244-2010078095331_lpd-targ.fits.gz"
tpf = KeplerTargetPixelFile(ktpf)
```
will fail and the "ImportError: No module named _bsddb" message will appear if package bsddb is not installed.

#### Expected Action
Update the installation documentation to include a warning that should one ever see this symptom, one remedy is to install the package bsddb.  I have not yet verified this in a Anaconda3 or pip3 Python 3 environment where the problem may not exist or another remedy might be required.

#### Environment:
- platform: Xubuntu 18.04.1, Python 2.7
- lightkurve version: 1.0b25
- installation method: conda

**Comment by barentsen** [comment]
Thank you for reporting this issue @texadactyl!  It is useful to have this documented in our issues.

Would you be willing to copy/paste the full error stack trace?  I'd like to understand exactly when the ImportError occurs, i.e. which line(s) of code depend on having `_bsddb` present.

**Comment by texadactyl** [comment]
Will do.

Also, is there any way that you have discovered to speed up conda's "Solving environment"? Bloody pig!

**Comment by texadactyl** [comment]
Just as I thought the battle was won .....

```
python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lightkurve import KeplerTargetPixelFile
>>> 
>>> TPF_NAME = "https://archive.stsci.edu/pub/kepler/target_pixel_files/0069/006922244/kplr006922244-2010078095331_lpd-targ.fits.gz"
>>> 
>>> tpf = KeplerTargetPixelFile(TPF_NAME)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/lightkurve/targetpixelfile.py", line 675, in __init__
    **kwargs)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/lightkurve/targetpixelfile.py", line 45, in __init__
    self.hdu = fits.open(self.path, **kwargs)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 148, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1006, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/utils/decorators.py", line 508, in wrapper
    return function(*args, **kwargs)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/io/fits/file.py", line 125, in __init__
    self.name = download_file(fileobj, cache=cache)
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/utils/data.py", line 1065, in download_file
    with _open_shelve(urlmapfn, True) as url2hash:
  File "/home/elkins/anaconda2/lib/python2.7/site-packages/astropy/utils/data.py", line 1374, in _open_shelve
    shelf = shelve.open(shelffn, protocol=2)
  File "/home/elkins/anaconda2/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/elkins/anaconda2/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/home/elkins/anaconda2/lib/python2.7/anydbm.py", line 84, in open
    mod = __import__(result)
  File "/home/elkins/anaconda2/lib/python2.7/dbhash.py", line 7, in <module>
    import bsddb
  File "/home/elkins/anaconda2/lib/python2.7/bsddb/__init__.py", line 67, in <module>
    import _bsddb
ImportError: No module named _bsddb
```

**Comment by texadactyl** [comment]
So, then I did this: ```conda install bsddb```
Then, all is well:

```python
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 19:04:19) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from lightkurve import KeplerTargetPixelFile
>>> TPF_NAME = "https://archive.stsci.edu/pub/kepler/target_pixel_files/0069/006922244/kplr006922244-2010078095331_lpd-targ.fits.gz"
>>> tpf = KeplerTargetPixelFile(TPF_NAME)```

**Comment by texadactyl** [comment]
Note that the last package to cause the cascade is astropy/utils/data.py

**Comment by barentsen** [comment]
Aha! This appears to be listed as a known AstroPy issue, see:

http://docs.astropy.org/en/older-docs-archive/v2.0.7/known_issues.html#remote-data-utilities-in-astropy-utils-data-fail-on-some-python-distributions

The issue appears to be specific to Python 2, and so it was only listed as a known issue in AstroPy versions up to 2.0 (hence I am linked to older astropy docs).  AstroPy 3.0 does not mention the issue simply because it no longer supports Python 2.

Anyone encountering this issue with Lightkurve will hopefully find this thread and learn that the solution is to `conda install bsddb`.  Beyond that, I am tempted not to take any further action because Lightkurve itself should drop support for Python 2 in the near future, so that we can take advantage of the new features in AstroPy 3.0.

(Python 2 will cease to receive security and bug patches in less than a year from now, cf. https://pythonclock.org)

**Comment by barentsen** [comment]
If we did want to make life easier for Python 2 users, I suppose one possibility is to wrap every occurrence of `fits.open()` in Lightkurve as follows:

```
try:
   fits.open(...)
Except ImportError:
   if importerror is due to bsddb:
       print helpful error message
```

... but really such a helpful error message should've been part of astropy.

**Comment by barentsen** [comment]
I'm going to close this issue for now, but do feel free to re-open if anyone thinks we should take further action.  This would be the case if e.g. we do see a large number of users struggle with this issue.

**Comment by texadactyl** [comment]
No, do not make code changes.  But, please warn users through documentation that Python 2 users might experience that symptom and the remedy is simply to manually install bsddb.

**Comment by texadactyl** [comment]
I could not reproduce this anomaly under Python 3.  Excellent.
```
apt install python3-pip
pip3 install lightkurve
python3 .....
```

**Comment by texadactyl** [comment]
I could not reproduce this anomaly under Python 3.  Excellent.
```
apt install python3-pip
pip3 install lightkurve
python3 .....
```
