### ISSUE TITLE
There needs to be lightkurve hoodies

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/lightkurve#389]
#### Problem description

I get cold on wintery evenings and I have no lightkurve hoodie to keep me warm.

#### Example
I was cold in Seattle and I hadbl nothing to wear.
#### Expected behavior

I would like a hoodie with a lightkurve logo on the chest. Also a zip.
#### Environment:
Cold evenings. But not too cold.

**Comment by barentsen** [comment]
Thank you for the suggestion @mrtommyb!

I am unable to reproduce your issue because it is never cold in California :sun_with_face:, so it may be best for Lightkurve's east coast office to take the lead on this :snowflake:.  Please re-open this issue when there is progress to report. :nerd_face:
