### ISSUE TITLE
May need to close TPF files after search .download()

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#394]
After downloading thousands of target pixel files with the `search` functionality, I hit some errors that implicated our double-opening of fits files on line ~756 of `search.py`.  @nksaunders and I used a context manager to auto-close the first instance of opening the file, and the error went away.  Here was the change we made:

```
 lightkurve/search.py | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/lightkurve/search.py b/lightkurve/search.py
index 1119ce1..4bda0a5 100644
--- a/lightkurve/search.py
+++ b/lightkurve/search.py
@@ -92,7 +92,7 @@ class SearchResult(object):
         """Returns an array of dec values for targets in search"""
         return self.table['s_dec'].data.data

-    @suppress_stdout
+    #@suppress_stdout
     def download(self, quality_bitmask='default', download_dir=None):
         """Returns a single `KeplerTargetPixelFile` or `KeplerLightCurveFile` object.

@@ -146,6 +146,8 @@ class SearchResult(object):
         path = Observations.download_products(self.table[:1], mrp_only=False,
                                               download_dir=download_dir)['Local Path']

+        print(path)
+
         # open() will determine filetype and return
         return open(path[0], quality_bitmask=quality_bitmask)

@@ -756,7 +758,8 @@ def open(path_or_url, **kwargs):
         >>> tpf = open("mytpf.fits")  # doctest: +SKIP
     """
     # pass header into `detect_filetype()`
-    filetype = detect_filetype(fits.open(path_or_url)[0].header)
+    with fits.open(path_or_url) as temp:
+        filetype = detect_filetype(temp[0].header)
```

I propose we add this context manager to ensure `fits.close()` is executed at least one of the two times.  In general, `fits.close()` cannot be executed for instantiated TargetPixelFile objects, which is a bit of a lightkurve gotcha-- TPF class is, in part, a wrapper around HDUs.  

We could consider adding (seldom-run) performance tests of opening thousands of target pixel files, or the same target pixel file thousands of times, to quantify file I/O weirdness attributable to open fits files.

**Comment by barentsen** [comment]
Indeed, this line in search.py's `open()` function:
```
filetype = detect_filetype(fits.open(path_or_url)[0].header)
```
...opens the FITS file *only* for the sake of determining the file type from the header.  If it makes a memory performance difference, we should definitely ensure that the file is closed again after the file type is detected!

Please go ahead and open a PR!
