### ISSUE TITLE
LightCurveFile repr could be more infomative

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#404]
Currently the `LightCurveFile` and `LightCurve` repr's are very similar and I wonder if this is causing/ will cause a little confusion for people. 

![image](https://user-images.githubusercontent.com/14965634/52016653-017c5600-249a-11e9-8aa6-573be68331cb.png)

I wonder if we should change the `LightCurveFile` repr to something like

![image](https://user-images.githubusercontent.com/14965634/52016662-07723700-249a-11e9-9b3a-1e49ca45d272.png)

Where we could 1) see that it was different to a `LightCurve` and 2) see the extensions that are available.

This would be super easy to implement, but I'm opening an issue because I'd like an opinion from @barentsen before I implement this.

**Comment by barentsen** [comment]
I like this idea a lot. :+1: :+1:

How about something like this, which is a bit more consistent with the reprs in the PRF module:
```
<KeplerLightCurveFile(targetid=123456789)>
provides:
  .SAP_FLUX: <KeplerLightCurve>
  .PDCSAP_FLUX: <KeplerLightCurve>
```

**Comment by barentsen** [comment]
As of Lightkurve v2.x, the `LightCurveFile` class has been removed and the new, `TimeSeries`-based `LightCurve` class has a new fancy repr.  Closing this issue!
