### ISSUE TITLE
Enable easy access to random data

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#413]
It would be nice to have easy access to a random light curve or pixel file, e.g. using `search_targetpixelfile("random")` or `LightCurve.random()`, to make it easier to experiment with random data.

**Comment by mirca** [comment]
This would be awesome, +1.

**Comment by barentsen** [comment]
How to implement? One option could be to have it return a random planet.  That way we can query the exoplanet archive for coordinates without having to store a list of random IDs within Lightkurve.

**Comment by nksaunders** [comment]
Love this idea, I would be happy to work on adding it to the `lightkurve.search` functions!

**Comment by christinahedges** [comment]
I have written up a little function to do this randomization using K2fov. I think it's a faiiirly neat solution that will let you randomly choose a Kepler/K2 target and specify the quarter, campaign, channel. 

https://gist.github.com/christinahedges/d317223d558b5755209df68690ebcd6e

I'm adding it here as a gist. @barentsen @nksaunders @mirca do you have any comments or suggestions? If you don't have any comments/suggested improvements, I'll make a PR with this function in the `search` module and add a load of unit tests.

I'm thinking the call should be

```python
lcf = lk.search_lightcurvefile('random', mission='kepler', quarter=9, ...)
```

**Comment by mirca** [comment]
I like that function a lot @christinahedges!

Regarding the interface, I would suggest the following:
```
lcf = lk.random_lightcurve(mission='kepler', ...)
tpf = lk.random_targetpixelfile(mission='kepler', ...)
```
which essentially would just be wrappers around the function ``random_target`` that you wrote.

**Comment by christinahedges** [comment]
Yeah I actually agree with @mirca nevermind what I said

**Comment by barentsen** [comment]
Just documenting here (for my own memory) that if we *also* wanted a function to return a random confirmed planet system, this Exoplanet archive API query returns RA/Dec of all confirmed Kepler/K2/TESS planet systems:

https://exoplanetarchive.ipac.caltech.edu/cgi-bin/nstedAPI/nph-nstedAPI?table=exoplanets&select=ra,dec&where=pl_facility%20like%20%27%25Kepler%25%27%20OR%20pl_facility%20like%20%27%25K2%25%27%20OR%20pl_facility%20like%20%27%25TESS%25%27

**Comment by barentsen** [comment]
I'm going to close this issue due to lack of activity.  This has not been a high-priority feature request, however Pull Requests to add this functionality remain welcome. :+1:
