### ISSUE TITLE
Replicate all Period04 functionality in Periodogram

### ISSUE THREAD

**Issue by keatonb** [KeplerGO/lightkurve#427]
#### Problem description

Lightkurve is becoming the standard tool for accessing and manipulating light curves for modern data analysis on modern computers. With the recently added periodogram functionality, this could also be a convenient tool for end-to-end analyses of fairly straightforward variable systems, especially for asteroseismology.  For the last 15 years, [Period04](http://adsabs.harvard.edu/abs/2005CoAst.146...53L) has been the standard tool for frequency analysis (amassing over 1000 citations); however, this standalone java program does not mesh with today's software and workflow.  I suggest that all of Period04's major functionality be added to the lightkurve periodogram class, including:

- [ ] Computing signal-to-noise of peaks in a periodogram
- [ ] Automatically selecting signal peaks from a periodogram
- [ ] Interactively selecting peaks of interest from a periodogram
- [ ] Refining signal phase/frequency/amplitude measures from least squares fitting to the time series
- [ ] Including harmonics and combination frequencies with strict arithmetic relationships
- [ ] Prewhitening a set of frequencies and computing a periodogram of the residuals
- [ ] Ability to compute the spectral window

Once this basic functionality is in place, more advanced features could be added like tracking phase/frequency/amplitude variations over long time series.

I believe lightkurve nominally supports ground-based time series observations, for which this functionality would also be widely used.

I would be interested in developing this functionality, but my time to work on this is fairly limited.

**Comment by gully** [comment]
👋 @keatonb let's talk!
I can potentially help.  I've made some prototype interactive harmonic analysis tools.  Here is a demo:

![harmonic_fits](https://user-images.githubusercontent.com/860227/52382192-1ec89b80-2a29-11e9-8d2c-ff34a4268093.gif)

Indeed, our new `interact_bls()` tool could/should have a natural twin "interact_periodic" or something like that, in which the user can carry out period04-like functionality as you describe in a Jupyter notebook with bokeh.

**Comment by keatonb** [comment]
Hey great @gully, that interactive bit is what I could most use help on.  The functionality we would need to replicate should be pretty straightforward.  In Period04, right-clicking somewhere in the periodogram gives two options: 
![screen shot 2019-02-09 at 11 49 59 am](https://user-images.githubusercontent.com/6413923/52519817-676a9980-2c61-11e9-8e2f-a4d6dfc85c4c.png)
Each of which simply passes the frequency under the cursor to one or another function.

Sound doable?

**Comment by danielhey** [comment]
Hi Keaton, I like the idea of this!!

I've previously written a small package (https://github.com/danielhey/balmung) for pre-whitening and least squares fitting of frequencies to time series, which gives (from memory) identical results to Period04. The example.ipynb in the repo is woefully undocumented, but it can also prewhiten harmonics of frequencies and return the residual light curve. It'd be cool if we can port some of this over to lightkurve!

**Comment by keatonb** [comment]
Hey @danielhey, your code looks good for automated prewhitening of the highest peaks, but I'm thinking of something with more interactivity like Period04 has.  I've actually been developing this actively and hope to have something ready to release in the next month or two.  Stay tuned :)

**Comment by barentsen** [comment]
In recent months, @keatonb has done an awesome job replicating Period04 features as part of the new Pyriod package:

https://github.com/keatonb/Pyriod

Hence, I'm inclined to close this issue for now, but we'll of course continue to be open to continue to improve Lightkurve to support brilliant new packages like Pyriod!! :+1:
