### ISSUE TITLE
Problems when installing lightkurve on Windows

### ISSUE THREAD

**Issue by hippke** [KeplerGO/lightkurve#435]
Attempting to install lightkurve on Windows

- Windows 10 latest
- Python 3.5.1, pip 19.0.2
- MSVC Compiler available from Visual Studio 2017

Lightkurve depends on `celerite` which fails `pip install celerite`. It hangs during wheel building in an endless loop without progress bar. Debug logs show that compiling `Eigen` fails using MSVC14 at `Derived=Eigen::Matrix<double,-1,1,0,-1,1>`

[Eigen](http://eigen.tuxfamily.org/index.php?title=Main_Page) claims to compile with MSVC 2012+. I could not find any binaries for installation on their site. Any ideas? I assume most Windows users will not be able to solve this on their own. Windows user may be a considerable fraction of lightkurve users.

**Comment by mirca** [comment]
Hi @hippke, thanks for reporting that. Could you try installing `celerite` with the following command:
`conda install -c conda-forge celerite`? We do test `lightkurve` on `Windows` environments via `AppVeyor`, and in that case `celerite` is being installed via `conda` so I suspect that will do the trick.  Thanks!

**Comment by hippke** [comment]
Thanks, this works:

- Windows 10 Home 1803
- Anaconda3 2018.12 64-bit (Python 3.7.1, conda 4.6.4)

`conda install -c conda-forge celerite`
`pip install lightkurve`

I saw a Twitter discussion a few days ago where somebody had similar trouble. Worth adding to the documentation I think.

**Comment by barentsen** [comment]
Thank you very much for reporting this @hippke!

Only one feature of Lightkurve depends on `celerite` right now (the `PLDCorrector` systematics removal class).  We should not have users encounter resolve compilation issues just for this one feature.

So, to avoid this issue in the future, I propose the following actions:
1. We make `celerite`, `pybind`, `scikit-learn`, and `bokeh` optional dependencies (i.e. we remove them from `requirements.txt` and `setup.py`).  We do keep them as dependencies of our `conda-forge` package because installing them as binary blobs is painless.
2. We edit our installation docs to more strongly encourage the use of `conda` to install Lightkurve, but also provide instructions on how to install the optional dependencies with `pip`.
3. We yield a clear error message in Lightkurve when features are used that require an optional dependency, and point to the online installation docs.

**Comment by barentsen** [comment]
Lightkurve v1.0b28 is now available via pypi.  This version no longer includes `celerite` as a required dependency to simplify installation (cf. #436).

**Comment by hippke** [comment]
Thank you for taking this issue. This is a great step forward. My Windows status is now:

- I can install `Lightkurve v1.0b28` **fully** on Windows using `conda`
- On Windows without 'conda`, I can install `Lightkurve v1.0b28` **partly**, that is: without 'Everest`

Problem:
- When installing `Lightkurve v1.0b28` using pip on Windows without conda, a warning is issued that `everest` could not be installed
- When I try to install `everest`, it fails because of a dependency to `george`. 
- When I try to install `george`, it fails because some C component doesn't compile with MSVC.
- Installing `george` from source fails with `No module named yaml`. I tried `pip install yaml` but no luck. This can also be seen on the AppVeyor status of `george`. I understand that this may be an issue unrelated to `lightkurve` itself. However for now I prefer to refrain from opening issues on these dependencies. They may or may not be interested on functioning on Windows.
- Installing `george` on `conda` works, so it's fine for `conda` users. On a side-note, this required an extra step to get `pybind11` which was not pulled as a dependency by `george`, but was required.

From the log I do not understand why the C part in `george` doesn't compile. This is sometimes tricky to identify for non-C experts. For example, in `batman-package` there was once a code line which referred to the constant `pi`. This compiled with GCC but not with MSVC. Code author Laura Kreidberg took my change request and now it works with all C compilers. But that was easy to see.

**Comment by barentsen** [comment]
@hippke I'm a bit confused because Lightkurve has no dependency on Everest, so `pip` shouldn't even be trying to install it. Would you be willing to share the log of what you see when typing `pip install lightkurve`?

**Comment by hippke** [comment]
Here is the log. The line is toward the end: `everest-pipeline 2.0.11 requires george>=0.2.1, which is not installed.`

```
Microsoft Windows [Version 10.0.17134.523]
(c) 2018 Microsoft Corporation. Alle Rechte vorbehalten.

C:\WINDOWS\system32>pip install lightkurve
Collecting lightkurve
  Downloading https://files.pythonhosted.org/packages/88/a8/aa535da1b54c1181b0feec3d2ac1ec4aac4131140b32e7a2a2998469a80a/lightkurve-1.0b28.tar.gz (450kB)
    100% |################################| 450kB 237kB/s
Requirement already satisfied: numpy>=1.11 in c:\program files\python35\lib\site-packages (from lightkurve) (1.14.2+mkl)
Requirement already satisfied: astropy>=1.3 in c:\program files\python35\lib\site-packages (from lightkurve) (3.1.1)
Collecting scipy>=0.19.0 (from lightkurve)
  Using cached https://files.pythonhosted.org/packages/ac/65/9efc846e049cc219035e3acd33dfe6a8e4b37b16b7fd77cd130d64b3897c/scipy-1.2.1-cp35-cp35m-win_amd64.whl
Requirement already satisfied: matplotlib>=1.5.3 in c:\program files\python35\lib\site-packages (from lightkurve) (2.2.3)
Requirement already satisfied: astroquery>=0.3.9 in c:\program files\python35\lib\site-packages (from lightkurve) (0.3.9)
Collecting oktopus (from lightkurve)
Collecting bs4 (from lightkurve)
Requirement already satisfied: requests in c:\program files\python35\lib\site-packages (from lightkurve) (2.9.1)
Requirement already satisfied: tqdm in c:\program files\python35\lib\site-packages (from lightkurve) (4.29.1)
Requirement already satisfied: pandas in c:\program files\python35\lib\site-packages (from lightkurve) (0.19.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (2.1.10)
Requirement already satisfied: six>=1.10 in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (1.10.0)
Requirement already satisfied: pytz in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (2016.10)
Requirement already satisfied: cycler>=0.10 in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (2.6.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\program files\python35\lib\site-packages (from matplotlib>=1.5.3->lightkurve) (1.0.1)
Requirement already satisfied: beautifulsoup4>=4.3.2 in c:\program files\python35\lib\site-packages (from astroquery>=0.3.9->lightkurve) (4.7.1)
Requirement already satisfied: keyring>=4.0 in c:\program files\python35\lib\site-packages (from astroquery>=0.3.9->lightkurve) (17.1.1)
Requirement already satisfied: html5lib>=0.999 in c:\program files\python35\lib\site-packages (from astroquery>=0.3.9->lightkurve) (1.0.1)
Collecting autograd (from oktopus->lightkurve)
  Using cached https://files.pythonhosted.org/packages/08/7a/1ccee2a929d806ba3dbe632a196ad6a3f1423d6e261ae887e5fef2011420/autograd-1.2.tar.gz
Requirement already satisfied: setuptools in c:\program files\python35\lib\site-packages (from kiwisolver>=1.0.1->matplotlib>=1.5.3->lightkurve) (18.2)
Requirement already satisfied: soupsieve>=1.2 in c:\program files\python35\lib\site-packages (from beautifulsoup4>=4.3.2->astroquery>=0.3.9->lightkurve) (1.6.2)
Requirement already satisfied: pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform == "win32" in c:\program files\python35\lib\site-packages (from keyring>=4.0->astroquery>=0.3.9->lightkurve) (0.2.0)
Requirement already satisfied: entrypoints in c:\program files\python35\lib\site-packages (from keyring>=4.0->astroquery>=0.3.9->lightkurve) (0.3)
Requirement already satisfied: webencodings in c:\program files\python35\lib\site-packages (from html5lib>=0.999->astroquery>=0.3.9->lightkurve) (0.5.1)
Collecting future>=0.15.2 (from autograd->oktopus->lightkurve)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Building wheels for collected packages: lightkurve, autograd, future
  Building wheel for lightkurve (setup.py) ... done
  Stored in directory: C:\Users\Michael\AppData\Local\pip\Cache\wheels\39\35\4a\40926ed25274c6174b731e584641b7349eabfc6054b64d08dd
  Building wheel for autograd (setup.py) ... done
  Stored in directory: C:\Users\Michael\AppData\Local\pip\Cache\wheels\72\6f\c2\40f130cca2c91f31d354bf72de282922479c09ce0b7853c4c5
  Building wheel for future (setup.py) ... done
  Stored in directory: C:\Users\Michael\AppData\Local\pip\Cache\wheels\0c\61\d2\d6b7317325828fbb39ee6ad559dbe4664d0896da4721bf379e
Successfully built lightkurve autograd future
everest-pipeline 2.0.11 requires george>=0.2.1, which is not installed.
Installing collected packages: scipy, future, autograd, oktopus, bs4, lightkurve
  Found existing installation: scipy 0.18.1
    Uninstalling scipy-0.18.1:
      Successfully uninstalled scipy-0.18.1
Successfully installed autograd-1.2 bs4-0.0.1 future-0.17.1 lightkurve-1.0b28 oktopus-0.1.2 scipy-1.2.1
```

**Comment by barentsen** [comment]
That's interesting! @mirca any idea why `everest-pipeline` would pop up in the install log out of nowhere?

I wonder if pip is merely reporting all unmet dependencies in the current environment, regardless of what is being installed right now.

**Comment by hippke** [comment]
Indeed! I cleared pip and now the everest thing is gone. It must have been in the pipeline for some time. So I think `lightkurve` is good!
