### ISSUE TITLE
Consider packaging lightcurve for Debian

### ISSUE THREAD

**Issue by olebole** [KeplerGO/lightkurve#437]
Hi,

I am a member of the [Debian Astro](https://blends.debian.org/astro)  Team. Our aim is to package astronomical software for Debian, from  where it will also migrate to derivative distributions like Ubuntu or  Mint. Would you consider packaging lightcurve for Debian? This would ease  the installation of the software on those systems and help people keeping it updated. So,  it can broaden your user base. 

If you would package it, we would be glad to help you when you run  into problems. Once the package is ready, we could upload it to the  Debian archive. We have a [mailing list](https://lists.debian.org/debian-astro), which I would recommend to subscribe, since this is our main information exchange. Please feel free to contact me on any questions or comments.

Best regards

Ole

**Comment by barentsen** [comment]
Thank you for getting in touch @olebole.  And thank you for your great work on Debian packages! 

Can you provide a pointer to what steps are involved?  We may want to wait for the stable Lightkurve v1.0.0 release, but we expect that will be out soon!

**Comment by gully** [comment]
Ping @olebole we now have a stable version 1.0 release (and beyond).  Do you want to revisit debian packaging for lightkurve?  Is there an automated way to package, similar to the [lightkurve feedstocks](https://github.com/conda-forge/lightkurve-feedstock) for conda?

**Comment by olebole** [comment]
Oh, sorry that I didn't answer before… 
I think lightcurve would be a very useful contribution to Debian Astro! And, since lightcurve is Python, the easiest way would be to follow the [Tutorial](https://wiki.debian.org/DebianAstro/AstropyPackagingTutorial/Preparation) that I wrote for Astropy affiliated packages. It also has a number of pointers. I am always glad to help you if you run into difficulties there -- maybe in this thread, or in our mailing list.

**Comment by barentsen** [comment]
I'm inclined to close this issue because we are running out of resources within the Kepler team to work on Lightkurve.  While I love the idea of having a Debian package, right now we can only afford to maintain the existing Python distribution.
