### ISSUE TITLE
download breaks

### ISSUE THREAD

**Issue by benjaminpope** [KeplerGO/lightkurve#442]
#### Problem description
When I simply try to download a lightcurve from Kepler it breaks!

#### Example

```python
import lightkurve
lcs = lightkurve.search_lightcurvefile(10593626)
lcs.download_all() ...
```

WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-29-e582a1edb470> in <module>()
----> 1 lcs.download_all()

/anaconda3/lib/python3.7/site-packages/lightkurve/utils.py in wrapper(*args, **kwargs)
    451                 return f(*args, **kwargs)
    452             # restore to default
--> 453             finally:
    454                 sys.stdout = old_out
    455     return wrapper

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in download_all(self, quality_bitmask, download_dir)
    202             warnings.warn("Cannot download from an empty search result.",
    203                           LightkurveWarning)
--> 204             return None
    205 
    206         # Make sure astroquery uses the same level of verbosity

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in <listcomp>(.0)
    202             warnings.warn("Cannot download from an empty search result.",
    203                           LightkurveWarning)
--> 204             return None
    205 
    206         # Make sure astroquery uses the same level of verbosity

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in open(path_or_url, **kwargs)
    757         table = ascii.read(os.path.join(PACKAGEDIR, 'data', 'short_cadence_month_lookup.csv'))
    758         # The following line is needed for systems where the default integer type
--> 759         # is int32 (e.g. Windows/Appveyor), the column will then be interpreted
    760         # as string which makes the test fail.
    761         table['StartTime'] = table['StartTime'].astype(str)

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    149 
    150     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
--> 151                             lazy_load_hdus, **kwargs)
    152 
    153 

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    388         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    389                              save_backup=save_backup, cache=cache,
--> 390                              lazy_load_hdus=lazy_load_hdus, **kwargs)
    391 
    392     @classmethod

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
   1062 
   1063         # Make sure at least the PRIMARY HDU can be read
-> 1064         read_one = hdulist._read_next_hdu()
   1065 
   1066         # If we're trying to read only and no header units were found,

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _read_next_hdu(self)
   1137                                 fileobj.seek(offset, os.SEEK_SET)
   1138 
-> 1139                         hdu = _BaseHDU.readfrom(fileobj, **kwargs)
   1140                     except EOFError:
   1141                         self._read_all = True

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in readfrom(cls, fileobj, checksum, ignore_missing_end, **kwargs)
    326         hdu = cls._readfrom_internal(fileobj, checksum=checksum,
    327                                      ignore_missing_end=ignore_missing_end,
--> 328                                      **kwargs)
    329 
    330         # If the checksum had to be checked the data may have already been read

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in _readfrom_internal(cls, data, header, checksum, ignore_missing_end, **kwargs)
    391             if header is None:
    392                 header_offset = data.tell()
--> 393                 header = Header.fromfile(data, endcard=not ignore_missing_end)
    394             hdu_fileobj = data
    395             data_offset = data.tell()  # *after* reading the header

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/header.py in fromfile(cls, fileobj, sep, endcard, padding)
    445 
    446             return cls._from_blocks(block_iter, is_binary, sep, endcard,
--> 447                                     padding)[1]
    448         finally:
    449             if close_file:

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/header.py in _from_blocks(cls, block_iter, is_binary, sep, endcard, padding)
    514             # TODO: Pass this error to validation framework as an ERROR,
    515             # rather than raising an exception
--> 516             raise OSError('Header missing END card.')
    517 
    518         header_str = ''.join(read_blocks)

OSError: Header missing END card.
#### Environment:
-OSX
- lightkurve version 1.0b25:
- installation method: pip

**Comment by barentsen** [comment]
Thank you for reporting this issue @benjaminpope!  I am interested in understanding what happened here.  I do not see this behavior on my own machine (see screenshot below).

Would you be willing to let us know what version of `astroquery` you have installed (`import astroquery; print(astroquery.__version__)`).

Are you able to confirm that you can reproduce this problem at a different time / using a different internet connection?

Thanks++. 

![screenshot from 2019-02-11 23-16-00](https://user-images.githubusercontent.com/817669/52611319-14583880-2e53-11e9-98ab-adbf199b316e.png)

**Comment by benjaminpope** [comment]
Hi Geert,

On my home internet rather than at the office I still get the same problem. astroquery version is 0.3.9

I worried that the lightkurve download cache might have been bad but I deleted it.

I still get 

In [5]: lcs.download_all()
WARNING: non-ASCII characters are present in the FITS file header and have been replaced by "?" characters [astropy.io.fits.util]
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-e582a1edb470> in <module>()
----> 1 lcs.download_all()

/anaconda3/lib/python3.7/site-packages/lightkurve/utils.py in wrapper(*args, **kwargs)
    449             sys.stdout = devnull
    450             try:
--> 451                 return f(*args, **kwargs)
    452             # restore to default
    453             finally:

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in download_all(self, quality_bitmask, download_dir, cutout_size)
    230             return TargetPixelFileCollection([open(p) for p in path])
    231         elif any(e in self.table['productFilename'][0] for e in lcf_extensions):
--> 232             return LightCurveFileCollection([open(p) for p in path])
    233 
    234     def _default_download_dir(self):

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in <listcomp>(.0)
    230             return TargetPixelFileCollection([open(p) for p in path])
    231         elif any(e in self.table['productFilename'][0] for e in lcf_extensions):
--> 232             return LightCurveFileCollection([open(p) for p in path])
    233 
    234     def _default_download_dir(self):

/anaconda3/lib/python3.7/site-packages/lightkurve/search.py in open(path_or_url, **kwargs)
    879     """
    880     # pass header into `detect_filetype()`
--> 881     filetype = detect_filetype(fits.open(path_or_url)[0].header)
    882 
    883     # if the filetype is recognized, instantiate a class of that name

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in fitsopen(name, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    149 
    150     return HDUList.fromfile(name, mode, memmap, save_backup, cache,
--> 151                             lazy_load_hdus, **kwargs)
    152 
    153 

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in fromfile(cls, fileobj, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
    388         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
    389                              save_backup=save_backup, cache=cache,
--> 390                              lazy_load_hdus=lazy_load_hdus, **kwargs)
    391 
    392     @classmethod

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, lazy_load_hdus, **kwargs)
   1062 
   1063         # Make sure at least the PRIMARY HDU can be read
-> 1064         read_one = hdulist._read_next_hdu()
   1065 
   1066         # If we're trying to read only and no header units were found,

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py in _read_next_hdu(self)
   1137                                 fileobj.seek(offset, os.SEEK_SET)
   1138 
-> 1139                         hdu = _BaseHDU.readfrom(fileobj, **kwargs)
   1140                     except EOFError:
   1141                         self._read_all = True

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in readfrom(cls, fileobj, checksum, ignore_missing_end, **kwargs)
    326         hdu = cls._readfrom_internal(fileobj, checksum=checksum,
    327                                      ignore_missing_end=ignore_missing_end,
--> 328                                      **kwargs)
    329 
    330         # If the checksum had to be checked the data may have already been read

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/hdu/base.py in _readfrom_internal(cls, data, header, checksum, ignore_missing_end, **kwargs)
    391             if header is None:
    392                 header_offset = data.tell()
--> 393                 header = Header.fromfile(data, endcard=not ignore_missing_end)
    394             hdu_fileobj = data
    395             data_offset = data.tell()  # *after* reading the header

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/header.py in fromfile(cls, fileobj, sep, endcard, padding)
    445 
    446             return cls._from_blocks(block_iter, is_binary, sep, endcard,
--> 447                                     padding)[1]
    448         finally:
    449             if close_file:

/anaconda3/lib/python3.7/site-packages/astropy/io/fits/header.py in _from_blocks(cls, block_iter, is_binary, sep, endcard, padding)
    514             # TODO: Pass this error to validation framework as an ERROR,
    515             # rather than raising an exception
--> 516             raise OSError('Header missing END card.')
    517 
    518         header_str = ''.join(read_blocks)

OSError: Header missing END card.

**Comment by mirca** [comment]
Hi @benjaminpope, like Geert, I'm unable to reproduce the issue posted. Could you try updating lightkurve?

**Comment by barentsen** [comment]
The error that triggered the crash (`OSError: Header missing END card.`) is typical for a corrupt file (e.g. a partially downloaded file).

My best guess is that the initial download failed, and the error keeps happening because the corrupt file now lives in the cache.  @benjaminpope I know you already tried deleting the download cache, but it may be worth double-checking that there is no `~/.astropy-cache` or `~/.lightkurve-cache` anywhere to be seen, because it is my current best guess for this issue!

**Comment by benjaminpope** [comment]
Ok so I upgraded from astropy 3.1 to 3.1.1 and it's fixed. Weird. Sorry to bother you!

**Comment by barentsen** [comment]
Happy it works again =)
