### ISSUE TITLE
Extend KeplerLightCurveFile and TessLigthCurveFile to support planets metadata

### ISSUE THREAD

**Issue by mirca** [KeplerGO/lightkurve#443]
I think it would be useful if `KeplerLightCurveFile` or `TessLightCurveFile` (or some other derived class) contained information on whether the star hosts planets, and if yes, it could contain some transit properties like period, duration, depth, etc. Maybe this information could be retrieved from the exoplanet archive using https://exoplanetarchive.ipac.caltech.edu/docs/program_interfaces.html? What do y'all think?

**Comment by barentsen** [comment]
Here are my three quick thoughts, but I'd love input from others:
1. For the sake of maintainability and a clean API, I think it would be good to keep Lightkurve's core classes as focused as possible.  For example, a `LightCurveFile` should only have properties and methods that are directly relevant to light curve file operations.
 2. We could think about having *separate* classes, e.g. a `Star` and a `Planet` class, to make working with star and planet parameters easier.  @christinahedges recently implemented such classes as part of the [wellfit package](https://github.com/christinahedges/wellfit), and it includes a nice `Planet.from_nexsci()` convenience method to load planet parameters from Nexsci into a `Planet` object.
3. I'd be open to think about adding those classes to Lightkurve, in which case there could be `LightCurve.star` or `LightCurve.planets` convenience properties to make it easy to access populated `Star` and `list of Planet` objects, whilst keeping the light curve classes themselves focused on light curve operations.

Anyone want to weigh in? Please do!

**Comment by barentsen** [comment]
I'm inclined to close this for now because I'm tempted to say that we should develop e.g. the retrieval of data from the exoplanet archive as a separate package, to enable Lightkurve to focus on the extraction and manipulation of light curves.

I might be wrong, so feel free to re-open or post examples of use cases!
