### ISSUE TITLE
interact() fails with "output_notebook is not defined"

### ISSUE THREAD

**Issue by JeffLCoughlin** [KeplerGO/lightkurve#454]
interact() fails with NameError: name 'output_notebook' is not defined

This is a fresh installation of jupyter, lightkurve, and bokeh via pip using python 3.6 today.

Explicitly specifying from bokeh.plotting import *  (or import outpute_notebook) does not resolve the issue.

`import lightkurve

from lightkurve import KeplerTargetPixelFile

tpf = KeplerTargetPixelFile("ktwo246199087-c19_lpd-targ.fits")

tpf.interact()

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-9-7bfcb21a8385> in <module>
----> 1 tpf.interact()

~/.local/lib/python3.6/site-packages/lightkurve/targetpixelfile.py in interact(self, notebook_url, max_cadences, aperture_mask, exported_filename)
    643                                     max_cadences=max_cadences,
    644                                     aperture_mask=aperture_mask,
--> 645                                     exported_filename=exported_filename)
    646 
    647     def interact_sky(self, notebook_url='localhost:8888', magnitude_limit=18):

~/.local/lib/python3.6/site-packages/lightkurve/interact.py in show_interact_widget(tpf, notebook_url, max_cadences, aperture_mask, exported_filename)
    550         doc.add_root(widgets_and_figures)
    551 
--> 552     output_notebook(verbose=False, hide_banner=True)
    553     return show(create_interact_ui, notebook_url=notebook_url)
    554 

NameError: name 'output_notebook' is not defined

`

#### Environment:
Linux, RHEL 7
- lightkurve version 1.0b29
- installation method pip

**Comment by barentsen** [comment]
@gully Would you be willing to investigate?

**Comment by JeffLCoughlin** [comment]
@KenMighell verbally reports he is getting a similar error on his linux box.

Meanwhile, on my non-NASA linux machine, I have upgraded bokeh and lightkurve to latest versions as of a few minutes ago, and do not get the error.

**Comment by barentsen** [comment]
@gully Would you be willing to look over @KenMighell's shoulder to figure out why it is failing?  It would be particularly important to know Ken's bokeh version -- `from bokeh.io import output_notebook` must be failing quietly for him.

**Comment by gully** [comment]
Will do!  I suspect the answer is in our optional handling of bokeh dependencies.

**Comment by JeffLCoughlin** [comment]
Update, after a laptop restart, and firing up jupyter notebook again, this issue no longer appears. Talking to Ken, this may be an issue with Bokeh when multiple notebooks calling bokeh are open.

Up to @barentsen and @gully , but I think this issue can be closed.

**Comment by barentsen** [comment]
Closing this issue as it appears to have been resolved.  Feel free to reopen if it emerges again!
