### ISSUE TITLE
Can't subtract a lightcurve from a lightcurve

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#456]
Currently I can't subtract a `lightkurve.KeplerLightCurve` from another `lightkurve.KeplerLightCurve`. I think we used to support this?

![image](https://user-images.githubusercontent.com/14965634/53134575-91a73b80-352c-11e9-98c6-7f8193fcf96d.png)

**Comment by gully** [comment]
I think the `-other` is interpretated as a negation operator or something?  Changing the `-other` to `-1*other` makes it work:

```python
    def __sub__(self, other):
        return self.__add__(-1*other)
```

**Comment by gully** [comment]
Question:  Should we support multiplying and dividing by LightCurve objects?

**Comment by barentsen** [comment]
Thanks to #532 being merged, adding/subtracting/multiplying/dividing two LightCurve objects now works instead of raising the weird exception.  I believe this issue can be closed!
