### ISSUE TITLE
Looking for help creating periodograms

### ISSUE THREAD

**Issue by SteveHealt** [KeplerGO/lightkurve#459]
I'm following the workbook from the TESS workshop and when attempting to use the LombScargle method in .to_periodogram I receive TypeError: __init__() got an unexpected keyword argument 'method'  

```
p = lc.remove_nans().to_periodogram(method='Lombscargle')
p.plot()
```

I have also tried
```
p = lc.remove_nans().to_periodogram('Lombscargle')
p.plot()
```
When attempting this I receive KeyError: ' resolvedCoordinate'

I tried using bls as well 
```
p = lc.to_periodogram('bls', duration=0.1)
p.plot()
```
This resulted in TypeError '>' not supported between instances of 'str' and 'int'

I'm fairly new to python and lightkurve, so any help is appreciated.

Thank you

Environment:
- Linux/Windows
- lightkurve version 1.0b25
- installation method - conda

**Comment by barentsen** [comment]
Hello @SteveHealt 👋.  Thank you for trying out Lightkurve! :+1: 

I see that you are using version 1.0b25 of Lightkurve.  The most recent version is 1.0b29, and a lot has changed to the periodograms in the last few releases (they have been under very active development).  Hence, it looks like you are using examples from the documentation which work only in the most recent versions (i.e. released in the last 2-3 weeks).

I see that you used conda to install the package.  Would you be willing to see if the problem goes away after running `conda update lightkurve`?

If the problem re-occurs, please copy/paste the full error message (even if it is very long) and the code that produced it.  Thanks++!

**Comment by SteveHealt** [comment]
Hey Geert,

I've solved the issue by working in the JupyterLab notebooks from the
conference, as everything seems to be up to date in there. I am running
into a different issue now and was wondering if you could provide some
insight.

When trying to pull from the MAST archive it returns, AttributeError:
'NoneType" object has no attribute 'plot'

My entry:

tpf = lk.search_targetpixelfile('TIC 259271401').download()
tpf.plot(aperture_mask=tpf.pipeline_mask)


And here is what it returns:


No data found for target "TIC 259271401".
/opt/conda/lib/python3.6/site-packages/lightkurve/search.py:131:
LightkurveWarning: Cannot download from an empty search result.
  LightkurveWarning)

---------------------------------------------------------------------------AttributeError
                           Traceback (most recent call
last)<ipython-input-125-6ef91540773a> in <module>      2       3 tpf =
lk.search_targetpixelfile('TIC 259271401').download()----> 4
tpf.plot(aperture_mask=tpf.pipeline_mask)
AttributeError: 'NoneType' object has no attribute 'plot'



Does this just mean that there is no data in MAST for this TIC ID?
I've run into this error with a few TIC IDs. Any help is appreciated!


Thank you,

Steve

**Comment by barentsen** [comment]
There does not seem to be any TESS data for this target yet. Likewise, I am unable to see TESS data for this target in the [MAST portal](https://mast.stsci.edu) (which queries the same database):

<img width="1022" alt="screen shot 2019-02-28 at 09 34 38" src="https://user-images.githubusercontent.com/817669/53586027-249f3180-3b3c-11e9-8ecb-90904d10d751.png">

Is this surprising? i.e. is there a reason to expect TIC 259271401 to have been observed?

**Comment by SteveHealt** [comment]
I was doing random researches yesterday in the MAST portal and came across
it. I did a search based on priority and filtered by dwarf and planet
candidates, and it is number 5 on the list. I think I was just confused and
thought planet candidate meant the target had been observed by the
telescope, but no planet had been observed yet. Does 'planetcandidate' just
indicate the possibility of a planet being located in that system and it is
scheduled for observation?

I'll attach a .png of my MAST search.

**Comment by barentsen** [comment]
Closing this issue for now.  Feel free to re-open if you believe an issue remains with the data access!  (Alternatively, the MAST or TESS GI helpdesks may be able to assist there.)
