### ISSUE TITLE
Feature request: interactive slicing of short-cadence TPF with interact()

### ISSUE THREAD

**Issue by ColinLittlefield** [KeplerGO/lightkurve#465]
This is a follow-up to Issue #201, which addressed the difficulty of using interact() on TPFs with more than 30,000 cadences. Although the workaround of slicing the TPF is helpful, I would be interested in the more in-depth solution discussed by @gully in #201: namely, having a range slider that allows the user to update in real-time the window used to slice the TPF.

I've found interact() to be an excellent tool for determining the optimal extraction aperture and for identifying data artifacts. Thanks for all of your work on it!

#### Environment:
- Windows
- lightkurve version 1.0b29
- installation method: pip

**Comment by barentsen** [comment]
Thank you for the feedback @ColinLittlefield!  We will discuss this a bit more and report back!
