### ISSUE TITLE
consider implementing a simpler PLD method

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/lightkurve#467]
@barentsen suggested that I make an issue about implementing a simpler PLD implementation

#### Problem description

I've found that I get better performance in some situations using a different PLD implementation

#### Example
This is the code that I have inside the PLDCorrector class correct method

```python
        if simple_tom:
            if cadence_mask is None:
                cadence_mask = np.where(self.time)

            aperture = self.tpf._parse_aperture_mask(aperture_mask)

            # generate flux light curve from desired pixels
            lc = self.tpf.to_lightcurve(aperture_mask=aperture)
            lc = lc.normalize()
            lc.flux -= 1.0

            # Build the first order PLD basis
            X_pld = np.reshape(self.flux[:, aperture_mask], (len(self.flux), -1))
            X_pld = X_pld / np.sum(self.flux[:, aperture_mask], axis=-1)[:, None]

            # Build the second order PLD basis and run PCA to reduce the number of dimensions
            X2_pld = np.reshape(X_pld[:, None, :] * X_pld[:, :, None], (len(self.flux), -1))
            U, _, _ = np.linalg.svd(X2_pld, full_matrices=False)
            X2_pld = U[:, :X_pld.shape[1]]

            # Construct the design matrix and fit for the PLD model
            X_pld = np.concatenate((np.ones((len(self.flux), 1)), X_pld, X2_pld), axis=-1)
            XTX = np.dot(X_pld[cadence_mask].T, X_pld[cadence_mask])
            w_pld = np.linalg.solve(XTX, np.dot(X_pld[cadence_mask].T, lc.flux[cadence_mask]))
            pld_flux = np.dot(X_pld, w_pld)

            corrected_lc = lc.copy()
            corrected_lc.flux = lc.flux - pld_flux
            return corrected_lc

```

**Comment by barentsen** [comment]
Thanks @mrtommyb. Do you have a specific target ID for which this snippet performed better?

**Comment by mrtommyb** [comment]
Ok, I'll add something. Another thought that I had is that for Kepler short cadence and TESS 2-min data I think we should default to use_gp=False. The code is very slow with the number of data points in short cadence data.

**Comment by nksaunders** [comment]
Hey @mrtommyb, thanks for the feedback. With #470 merged, PLD is _much_ faster for 2nd order even with `use_gp=True`. It also allows you to pass `pld_order` into the `correct` function if you want a very quick 1st order pass, or take it to higher order. I agree that it was pretty broken for TESS 2-min cadence data, so this is a much needed fix!
