### ISSUE TITLE
interrupting a download corrupts all future downloads until kernel is restarted

### ISSUE THREAD

**Issue by darthoctopus** [KeplerGO/lightkurve#483]
#### Problem description

When a TPF file download is interrupted (e.g. KeyboardInterrupt issued), future attempts to download and read TPF files yield FITS header errors until the kernel is restarted. Attempts to read the affected FITS files after the kernel is restarted fail with more corrupted header errors.

#### Example

```python
import lightkurve as lk

tpf = lk.search_targetpixelfile("TIC 140801683", mission="TESS").download_all()
# issue a KeyboardInterrupt while running, and try again
```

#### Expected behavior
Fails gracefully and attempts redownload.

#### Environment:
- Linux
- 1.0b30
- Installed by pip

**Comment by barentsen** [comment]
Thank you for reporting this issue @darthoctopus! :+1:

We will investigate!

**Comment by barentsen** [comment]
At this time I am not sure what we can do to make Lightkurve more robust against interrupted downloads, so I'm going to close this issue for now, but please do re-open if anyone has thoughts/ideas. Thanks everyone!
