### ISSUE TITLE
Feature Request: Querry the TESS Input Catalog from MAST

### ISSUE THREAD

**Issue by tfetherolf** [KeplerGO/lightkurve#484]
#### Feature Request

It would be awesome if I could use lightkurve to also grab information from the TESS Input Catalog! Currently I go about cross-matching my target list on the MAST portal by hand. For example: while the light curve headers have the stellar parameter measurements, I still need to go to the TIC to obtain the errors for the stellar parameters.

**Comment by barentsen** [comment]
Thank you for the suggestion @tfetherolf. Automated access to the TIC is definitely a useful and important feature!

I believe the `astroquery` package already does a pretty good job at allowing one to query the TIC, e.g.:
* see [documentation here](https://astroquery.readthedocs.io/en/latest/mast/mast.html);
* see a nice [TIC query tutorial here](https://github.com/spacetelescope/MAST-API-Notebooks/blob/master/TESS/TessTutorial-DwarfsNearHD209458.ipynb).

Have you had a chance to try accessing the TIC using this package?  Do you think Lightkurve should provide an easier way to access the TIC?  If so, do you want to post a bit of pseudo-code (which doesn't have to work) to illustrate what your dream code/interface would look like?

Again, thanks++ for opening the discussion!

**Comment by barentsen** [comment]
I'm tempted to close this issue for now because `astroquery` already provides this feature.

However, if someone thinks Lightkurve can make people's lives easier by querying the TIC on behalf of the user, then please do re-open the issue with an example!
