### ISSUE TITLE
Should `lc.flatten` be parameterized in time units?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#486]
Proposal: if the value of `window_length` passed to `lc.flatten()` is an AstroPy Quantity in time units, should `flatten()` convert it into cadences itself?  Example:

`lc.flatten(window_length=10*u.hour)`

The rationale for this, is that we could then set `n hours` as the default value for this parameter.  This resolve a current issue, which is that the default parameters for `flatten` are not appropriate for short cadence data.

**Comment by gully** [comment]
Some issues that arise with providing windows---that remain with step windows---is how the fixed-in-time windows will mesh with gaps in the data, or uneven sampled data.  The stingray package provides a rebinning functionality that grapples with uneven bin samples by adding fractional bins:

https://github.com/StingraySoftware/stingray/blob/f9c2b3dfef34fb4f2e48d866fd5218bffc995c7c/stingray/utils.py#L106

The Nadaraya-Watson estimator in Section 8.5 of the [Statistics, Data Mining, and Machine Learning in Astronomy](https://press.princeton.edu/titles/10159.html) book offers some additional discussion about tradeoffs in bandwidth and some strategies for automatically assigning bandwidth.

**Comment by barentsen** [comment]
This is a duplicate of #546.  I am going to close this issue because #546 contains a longer discussion.
