### ISSUE TITLE
Add `Not In Fine Point` to the default quality bitmask?

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#487]
EPIC 212803289 (aka K2-99) from Campaign 6 has a single cadence which shows up as an extreme outlier in its raw aperture light curve (CADENCENO = 113666).  This cadence has quality code 32769 (not in fine point), which is not part of the `default` or `hard` bitmask (it is only part of the `hardest` bitmask).

This large outlier caused our current implementation of `PLDCorrector` to fail, because the Gaussian Process that removes the long-term trend inside `PLDCorrector` was pulled away by the outlier.

Apart from making `PLDCorrector` more robust by using a more robust GP detrender (see #464), we should consider adding `Not In Fine Point` to the default bitmask.  I suspect we did not do this in the past because early Campaigns have a lot of useful cadences with this flag.

We should investigate!

**Comment by barentsen** [comment]
(The above was learned why pair-detrending and planet-fitting with @nksaunders.)

**Comment by JeffLCoughlin** [comment]
Unfortunately there are also many cadences that are marked as 'Not in Fine Point' that are good, valid cadences. Especially starting with C14, Flight OPS changed the way that Not in Fine Point was set, making it very sensitive, in an effort to detect spacecraft pointing issues early as it was possible to run out of fuel then. But many of these cadences have targets completely in the aperture. It's why we decided to not discard cadences marked as Not in Fine Point in the reprocessing.

However, in the reprocessing we are identifying pointing outliers in a more robust way using the subsecond pointing telemetry, and setting the "Spacecraft is in coarse point" flag (QUALITY flag bit #3, decimal=4) when outliers are identified (technically when the target significantly moves out of the aperture during exposure). I confirm that 113666 will be flagged as such when C6 is reprocessed, set to kick off this month. (Specifically, for C6, the cadences 113663--113676, 114415--114420, 112943, 113281, and 113528 will be flagged as Coarse Point.)

My rec. would be to make sure flag 4 is in the defaults, but leave 32769 off and wait for the reproc. data.

**Comment by barentsen** [comment]
Thank you @JeffLCoughlin. :+1:  Your message is *extremely* helpful.   This information convinces me that we should indeed continue to be tolerant of "Not in fine point" cadences, and instead focus on making sure that tools like `PLDCorrector` are robust against occasional outliers appearing in the data. (Not all outliers are due to fine point problems anyway!)

@nksaunders Do you agree?  If so, please close this issue!

**Comment by nksaunders** [comment]
Thanks @JeffLCoughlin! That answers a lot of our questions. I agree with @barentsen that the `Not In Fine Point` cadences should continue to be tolerated by the bitmasks. As we continue working on our Gaussian Process implementation, we can focus on making GPs (i.e. as applied in `PLDCorrector`) robust against outliers. 

I'll close this issue for now.

**Comment by JeffLCoughlin** [comment]
True that outliers could result from something that may not always trigger a flag. Tricky.

Great to hear!
