### ISSUE TITLE
Interact sky improvements

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#492]
I've received some feature requests for `interact_sky()`:

1. Add a save button for the image of interact sky
Perhaps with the TOOLS widget toolbar (e.g. existing wheel_zoom)--- could be as easy as adding the `save` tool.

2. Improve the visibility of the Gaia sources against the dark/light background
Perhaps by adding a distinctive light-colored marker edge color.

3. Python 2 seems to still truncate the full Gaia DR2 Source ID
Make sure the Source ID is being formatted as a string, and not a number.

**Comment by gully** [comment]
Additional user request:
Presently you can *view* the metadata in hover-over-tooltips; is there a way to copy/log the metadata, by say copy-and-paste, or by printing the information to the console.

**Comment by emilygilbert** [comment]
Would it be possible to add the option to overlay the aperture mask like you can in interact()?

**Comment by gully** [comment]
Ping @emilygilbert possibly?  
We've originally considered labeling the gaia DR2 sources on the `interact()` view and decided that the click-able pixels would interfere/overlap with the hover-over tool-tips for the gaia DR2 source circles.  The `.interact_sky()` did not populate the clickable pixels for this reason.  A workaround could be to make the pixels non-clickable, simply an outlined silhoutte.  What is your main use case?  If it's to gauge the contribution to a mask, would it make sense to put Gaia labels in the `.interact()` view?

**Comment by gully** [comment]
More general notes here: it's worth revisiting the mission of `interact_sky()` or getting some feedback on use cases.  It's not clear to me that `interact()` and `interact_sky()` should be different tools.  Currently it seems like `interact_sky()` is nice for checking if there are sources nearby in an image, but not for getting more info on those sources, or adapting your aperture mask pixels based on the locations of nearby sources.  Is there a strong need to merge these two workflows?

**Comment by emilygilbert** [comment]
Hi! Yes, I use it mostly to look at potential background contamination, so a non-clickable outline would be perfect for that!

**Comment by barentsen** [comment]
Although these are excellent ideas, I'm inclined to close this issue because we have run out of person-power to support new features.  If anyone is able to continue working on `interact_sky` in the future, then please do re-open this issue. Thanks everyone! :+1:
