### ISSUE TITLE
Rebinning Lightcurve and propagarting errors

### ISSUE THREAD

**Issue by dagnic** [KeplerGO/lightkurve#500]
Hello

This issue concern the method `bin` of the `Lightcurve` class.

#### Problem description

1) I see in the doc that if there are no `flux_err`, it takes the standard deviation of the data. But the code shows at [lightcurve.py#L640](https://github.com/KeplerGO/lightkurve/blob/2df071163daa272b11c5db8c92e6d021a5102576/lightkurve/lightcurve.py#L640)

```python
    binned_lc.flux_err = np.zeros(len(binned_lc.flux))
```

#### Expected behavior
```python
    binned_lc.flux_err = np.std(binned_lc.flux)
```

**Comment by barentsen** [comment]
Thank you for reporting this @dagnic! :+1: :+1: :+1:

You are absolutely right, this looks like a bug we need to fix!

**Comment by barentsen** [comment]
Thanks again for reporting this issue @dagnic!  The bug has been fixed (cf. #503) and will be part of the next release!
