### ISSUE TITLE
Add a function to convert Kepler electrons/s into Kp magnitude or e.g. Jansky

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#51]
To study e.g. flare energies, users sometimes want to convert Kepler's relative photometry (electrons/s) into absolute fluxes.  Although the literature on Kepler's zeropoint is limited, it would be useful to offer a function to convert fluxes into absolute units (e.g. Kp) using a best-available estimate of the zeropoint.

The GO site has historically listed a flux "zero"-point of 1.74 × 10^5 e-/s for a G2V-type star with Kp=12 (source: https://keplergo.arc.nasa.gov/CalibrationSN.shtml).

**Comment by JeffLCoughlin** [comment]
Another reference (maybe more updated) is the v2 (2016) Kepler Instrument Handbook. I think the right place is page 85 (sec. 7.5), which lists "fKep12 is the benchmark photoelectron current at the 
Kepler focal plane for a 12th magnitude star = 2.1x10E-5 e/s (Bachtell and Peters, 2008)".

**Comment by barentsen** [comment]
Closing this issue due to >12 months of inactivity.  Anyone interested in this feature is very welcome to open a new issue or PR when the need arises.
