### ISSUE TITLE
Folding light curves doesn't work with units

### ISSUE THREAD

**Issue by keatonb** [KeplerGO/lightkurve#520]
#### Problem description
With a TessLightCurve object that has time units, calling the fold method with a period that also has time units does not seem to work.

#### Example

```python
import lightkurve
tlc = lk.TessLightCurveFile(fname).get_lightcurve("PDCSAP_FLUX")
per = tlc.to_periodogram()
folded = tlc.fold(per.period_at_max_power)
```

#### Expected behavior
I expect the light curve folded on the period at max power from the periodogram, but I get an error instead:

> 
> ---------------------------------------------------------------------------
> UnitsError                                Traceback (most recent call last)
> <ipython-input-45-9b87170c32e5> in <module>()
> ----> 1 folded = tlc.fold(per.period_at_max_power)
> 
> /home/bell/anaconda2/lib/python2.7/site-packages/lightkurve/lightcurve.pyc in fold(self, period, t0, transit_midpoint)
>     421                               '(i.e. JD - 2457000).', LightkurveWarning)
>     422         phase = (t0 % period) / period
> --> 423         fold_time = (((self.time - phase * period) / period) % 1)
>     424         # fold time domain from -.5 to .5
>     425         fold_time[fold_time > 0.5] -= 1
> 
> /home/bell/anaconda2/lib/python2.7/site-packages/astropy/units/quantity.pyc in __array_ufunc__(self, function, method, *inputs, **kwargs)
>     619         # consistent units between two inputs (e.g., in np.add) --
>     620         # and the unit of the result (or tuple of units for nout > 1).
> --> 621         converters, unit = converters_and_unit(function, method, *inputs)
>     622 
>     623         out = kwargs.get('out', None)
> 
> /home/bell/anaconda2/lib/python2.7/site-packages/astropy/units/quantity_helper.pyc in converters_and_unit(function, method, *args)
>     491                                      "argument is not a quantity (unless the "
>     492                                      "latter is all zero/infinity/nan)"
> --> 493                                      .format(function.__name__))
>     494             except TypeError:
>     495                 # _can_have_arbitrary_unit failed: arg could not be compared
> 
> UnitsError: Can only apply 'subtract' function to dimensionless quantities when other argument is not a quantity (unless the latter is all zero/infinity/nan)
> 

#### Environment:
- platform (e.g. Linux, OSX, Windows): Linux
- lightkurve version (e.g. 1.0b6): 1.0.1
- installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thank you for reporting this behavior @keatonb!  This is about to be resolved via #520.

**Comment by barentsen** [comment]
@keatonb A fix has been merged!  It might take another week or two for the next Lightkurve version to be released, but if you don't want to wait that long, you should be able to start using the version that includes the fix by installing from GitHub as follows:

```pip install --upgrade git+https://github.com/KeplerGO/lightkurve```

**Comment by keatonb** [comment]
Thanks!  Taking the units off is working great for me for now, but I figured this isn't the ideal behavior.
