### ISSUE TITLE
Rolling band tutorial should include literature references

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#524]
We have an excellent [rolling band tutorial](https://docs.lightkurve.org/tutorials/04-identify-rolling-band.html).  It would be worth extending it slightly to include literature references on the topic, because some of the most important Kepler rolling band papers were published in SPIE, which can be harder for astronomers to discover.

Example: Kolodziejczak et al 2010: https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20100035090.pdf

This is referred to in the Kepler handbook as: `Kolodziejczak, J. J., Caldwell, D. A., Van Cleve, J. E., et al., 2010, Proc. SPIE, Vol. 7742, 77421G`.

...any others?

(We also need to make sure the tutorial links to the most recent version of the Kepler handbook.)

**Comment by JeffLCoughlin** [comment]
Kepler Instrument Handbook, section 6.7.1: http://adsabs.harvard.edu/abs/2016ksci.rept....1V

DR25 Release Notes, section A.1.1: https://archive.stsci.edu/kepler/release_notes/release_notes25/KSCI-19065-002DRN25.pdf

https://ntrs.nasa.gov/archive/nasa/casi.ntrs.nasa.gov/20120002957.pdf  has a real short section.

**Comment by barentsen** [comment]
Thanks @JeffLCoughlin!
