### ISSUE TITLE
Add Seamless Access to Cloud-hosted AWS data sets when on EC2 host

### ISSUE THREAD

**Issue by mustaric** [KeplerGO/lightkurve#526]
#### Problem description
When using lightkurve on an EC2 host, or on the TESS JupyterHub platform, the data is pulled from its home at MAST instead of from the Amazon hosted data site. This is an unnecessary data transfer.

#### Example
Currently this is what I do to retrieve the cloud hosted data. 

```python
from astroquery.mast 
import Observations
from astropy.io import fits
import boto3
obsTable = Observations.query_criteria(obs_id=obs_id_search)
products = Observations.get_product_list(obsTable)
mylc = products[products['productSubGroupDescription'] == 'LC']
Observations.enable_cloud_dataset()
url = Observations.get_cloud_uris(mylc)
s3 = boto3.resource('s3')
bucket = s3.Bucket('stpubdata')

#Remove the beginning of the url
fits_s3_key = url[0].replace("s3://stpubdata/", "")

#Pick a local location for the file.
file_name = url[0].split('/')[-1]
full_path = "/home/jovyan/data/" + file_name

bucket.download_file(fits_s3_key, full_path, ExtraArgs = {"RequestPayer" : "requester"})
fits.info(full_path)
```

#### Expected behavior
This is all too difficult for a user.  There should be one flag that you set to indicate you are running on an EC2 host and then otherwise it should all act the same. We should devise a way to integrate use of the cloud-hosted data with lightkurve.  

It might require some work on MAST's part.

#### Environment:
N/A

**Comment by barentsen** [comment]
I'm tempted to close this issue because we don't have resources left within the Kepler team to work on this, but it is absolutely a good idea which I hope someone will implement in the future!!

**Comment by mustaric** [comment]
There is a good chance I'll find some resources to work on this on my end as we are the ones interested in making this happen.  It is fine to close the issue since I don't know when that will happen.

**Comment by barentsen** [comment]
My goal is to close as many issues as possible in the coming month, to make sure we've dealt with all the major bugs etc.  It would of course be 100% fine to re-open this issue as resources become available!

...and of course this issue will still be searchable, which is good because the cloud access example you posted is a great resource!!
