### ISSUE TITLE
a more convenient WCS for tesscut TPFs?

### ISSUE THREAD

**Issue by zkbt** [KeplerGO/lightkurve#527]
#### Problem description
A TPF downloaded from TESS full frame image with `search_tesscut` has a WCS referenced to the center of the original FFI, using SIP distortion coefficients to account for distortions across the wide field of view. For some uses, it'd be more convenient if this WCS were referenced relative to something like center of the new tiny stamp, and if it didn't use the wide-field distortion coefficients; in particular, astropy's `WCSAxes` can't plot with those distortion coefficients.

#### Example
```python


from lightkurve.search import search_tesscut, search_targetpixelfile
from astropy.coordinates import SkyCoord
from astroquery.mast import Catalogs
import astropy.units as u
import numpy as np
import matplotlib.pyplot as plt

# pick a target 
target = 'LHS 3844'
center = SkyCoord.from_name(target)

# download as a two-minute TPF
tpf_twominute = search_targetpixelfile(center).download()
print(tpf_twominute.wcs)

# download as a tesscut from the FFI
size = tpf_twominute.shape[-1]
tpf_tesscut = search_tesscut(center).download(cutout_size=size)
print(tpf_tesscut.wcs)

# download some stars around the target
radius = size/2.0*20*u.arcsec*1.5
stars = Catalogs.query_object(target, radius=radius, catalog='Gaia')
# (neglecting proper motion between Gaia and TESS)

# define a helper for plotting both
def plot(tpf, gs, frame=0):
    
    # use WCSAxes from astropy to plot with WCS
    ax = plt.subplot(gs, projection=tpf.wcs)
    ax.imshow(tpf.flux[frame])

    # overplot the stars, using the WCS tranform on the axes
    ra, dec = stars['ra'], stars['dec']
    s = np.maximum((17 - stars['phot_g_mean_mag'])*5, 0)
    plt.scatter(ra, dec, s=s, transform=ax.get_transform('icrs'), color='red', zorder=100)

    return ax

# plot the both together
gs = plt.matplotlib.gridspec.GridSpec(1, 2)
plot(tpf_twominute, gs[0])
plt.title('from TPF')
plot(tpf_tesscut, gs[1])
plt.title('from tesscut');
```

![image](https://user-images.githubusercontent.com/4691081/59062777-e4023300-8863-11e9-8fd5-8927afdf19ac.png)

#### Expected behavior
It'd be great if a tesscut TPF had a WCS connected to it that acted like those in "normal" TPFs. I found a nice investigation into this by @ceb8 [here](https://github.com/ceb8/tessworkshop_wcs_hack/blob/master/tesscut_wcs_hack.ipynb), including a sketch of a solution for deriving a new local WCS. Have @ceb or folks here at `lightkurve` have started implementing this at all? Or is it already implemented somewhere? Or, if not, should I try to tackle it? Thanks!

(I'll link to this over at [tesscut](https://github.com/spacetelescope/tesscut) too.)

**Comment by ceb8** [comment]
Hey, this is really convenient timing. I am actually working on adding this functionality to astrocut (the underlying software to tesscut) right now. Once it's implemented there it should flow right through to tesscut and lightkurve.

**Comment by zkbt** [comment]
Ooh, ooh! That would be wonderful! Do you have a rough estimate of when you think that'll be ready?

**Comment by ceb8** [comment]
End of July-ish. Probably.

**Comment by barentsen** [comment]
That would be an awesome feature @ceb8!!  Re-parameterizing the WCS is not trivial, so I'm curious to know how it can be done. Feel free to ping if you need help or a tester!

**Comment by barentsen** [comment]
Also note: we should consider opening an astropy issue regarding the fact that `wcsaxes` ignores the large SIP coefficients without warning the user.  What do y'all think?

**Comment by ceb8** [comment]
@barentsen we're actually remaking the WCS from scratch using matched pixel and world coordinates. It's functionality that will hopefully be in the next release of astropy (see https://github.com/astropy/astropy/pull/7884), but I'll be implementing it early in astrocut.

Also, yes! Thanks for reminding me, I've been meaning to open an astropy issue suggesting that they add a warning about wcsaxes doing wcs_pix2world rather than all_pix2world since I figured out what was going on.

**Comment by zkbt** [comment]
Cool, thanks @ceb8! I really like the idea of rederiving a simple WCS locally; even if there are big distortions in the original global WCS, a tiny local patch should usually be pretty closely approximated by a linear transformation. Thinking about this generally, if possible, it would be great if your code gives a warning if the approximate WCS is likely to be off by more than ~1 pixel across whatever image you're transforming. Thanks, and please let me know how I can help!

**Comment by ceb8** [comment]
@zkbt Yes, that is a good idea. You can start seeing the affects with cutouts on the order of 100-200 pixels, which is not an unreasonable cutout size, so it can definitely become a concern.

**Comment by ceb8** [comment]
This work has been completed and propagated through to the tesscut service, so all cutouts should now have simpler local WCS info attached.

There are also three new header keywords, related to the WCS:
-  **WCS_FFI:** The name of the FFI file used to build the original WCS from which the cutout and cutout WCS were calculated.
-  **WCS_MSEP:** The maximum separation in degrees between the cutout’s linear WCS and the FFI’s full WCS.
-  **WCS_SIG:** The error in the cutout’s linear WCS, calculated as sqrt((dist(Po_ij, Pl_ij)^2) where dist(Po_ij, Pl_ij) is the angular distance in degrees between the sky position of of pixel i,j in the original full WCS and the new linear WCS.

Please let me know if you encounter any problems with this functionality.

**Comment by barentsen** [comment]
I ran the code example which @zkbt posted above and now see the following output:

![Screenshot from 2019-07-17 19-38-50](https://user-images.githubusercontent.com/817669/61425078-94833e00-a8ca-11e9-9f40-c349cf6a8044.png)

This looks much better!!  Awesome job for fixing this @ceb8!!

I think this can be closed.  Feel free to re-open if the issue re-emerges!
