### ISSUE TITLE
tpf.plot(scale='log') has a funny colorbar

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#53]
If `scale="log"` is used in `tpf.plot()`, we should let the ticks in the colorbar use log steps as well. Right now the colorback ticks look funny:

![image](https://user-images.githubusercontent.com/817669/36762289-ac10933c-1bd7-11e8-83cd-be0be542c315.png)

**Comment by mirca** [comment]
This was fixed in #186. Closing in 3, 2, 1, 0, -1, ...
