### ISSUE TITLE
`search_targetpixelfile("EPIC 200164267")` does not return the correct TPF

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#538]
In K2 Campaign 12 we observed TRAPPIST-1 using a custom mask (200164267).  It can successfully be accessed using `lk.search_targetpixelfile(200164267)`:

```python
In [2]: lk.search_targetpixelfile(200164267)                                    
Out[2]: 
SearchResult containing 1 data products.

 target_name           productFilename                        description              distance
------------- ---------------------------------- ------------------------------------- --------
ktwo200164267 ktwo200164267-c12_lpd-targ.fits.gz Target Pixel Long Cadence (KTL) - C12      0.0
```

However, if the prefix "EPIC" is added to the search, i.e. `lk.search_targetpixelfile("EPIC 200164267")`, only the standard mask that was observed at the same location (246199087) is shown instead:

```python
In [3]: lk.search_targetpixelfile("EPIC 200164267")                             
Out[3]: 
SearchResult containing 3 data products.

 target_name           productFilename                        description              distance
------------- ---------------------------------- ------------------------------------- --------
ktwo246199087 ktwo246199087-c12_lpd-targ.fits.gz Target Pixel Long Cadence (KTL) - C12      0.0
ktwo246199087 ktwo246199087-c19_lpd-targ.fits.gz Target Pixel Long Cadence (KTL) - C19      0.0
ktwo246199146 ktwo246199146-c19_lpd-targ.fits.gz Target Pixel Long Cadence (KTL) - C19      0.0
```

This behavior is inconsistent and confusing.  We need to investigate and add a unit test for this example.

**Comment by gully** [comment]
This issue is technically a special case of #499 --- the fact that custom apertures have coordinates that do not match exactly to the EPIC catalog.  I will consider this issue of Trappist-1's custom aperture to therefore be a duplicate and close for now.
