### ISSUE TITLE
Possible bug in lc.plot?

### ISSUE THREAD

**Issue by mirca** [KeplerGO/lightkurve#54]
See the screenshots below:
![screen shot 2018-02-28 at 2 38 34 pm](https://user-images.githubusercontent.com/13077051/36773543-261bb9a0-1c95-11e8-90f4-1a954270d0aa.png)
![screen shot 2018-02-28 at 2 39 37 pm](https://user-images.githubusercontent.com/13077051/36773559-3b5ea4d0-1c95-11e8-8863-553f299a7999.png)

**Comment by christinahedges** [comment]
It's not a bug in the plot. You have normalized the flux somewhere but not normalized the errors. The error bars are ~15 counts.

**Comment by mirca** [comment]
I pull the latest changes and now everything works again! =D
