### ISSUE TITLE
quick fix to unusually large default tpf aperture size

### ISSUE THREAD

**Issue by jpdeleon** [KeplerGO/lightkurve#541]
#### Problem description

Some nearby, bright stars have pipeline-generated (or default?) tpf aperture size that is unusually large, say >100 pixels across on one side.

#### Example

```python
import lightkurve as lk
from astropy.coordinates import SkyCoord

coord=SkyCoord.from_name('alpha Cen B')
tpf = lk.search_targetpixelfile(coord).download()
tpf.flux.shape

(18551, 905, 11)
```

#### Expected behavior

TESS short cadence tpf size is typically ~11x11 pixels. I was hoping to make the default tpf size smaller by simply slicing e.g. tpf.flux[:,:11,:11] but I cannot set attribute. This property is invoked down stream my code such as when using tpf.plot() etc so I prefer to set this attribute if it's possible to do so by other means. 

#### Environment:
- platform (e.g. Linux, OSX, Windows): Linux
- lightkurve version (e.g. 1.0b6): 1.0.1
- installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
Thank you for the report @jpdeleon!

@christinahedges encountered the same problem and decided to develop a `tpf.cutout()` method to solve this exact issue.  The development is taking place over in #537.

If you wanted to try the new feature today, you could check out the PR branch.  Alternatively, I hope we'll have Lightkurve v1.1, including this new feature, out later this week!

**Comment by jpdeleon** [comment]
Hi @barentsen ! Thanks for pointing out this PR. I should have looked at the other branches more thoroughly. I confirm that this method indeed fixes my problem. Cheers!

**Comment by barentsen** [comment]
No worries @jpdeleon! Thank you for trying the new function!!
