### ISSUE TITLE
Centroiding doesn't work very well on faint, highly variable targets.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#542]
The current implementation of centroids can fail really weirdly with some faint targets that are highly variable. In this case, it may be because the tpf background is actually negative.

![image](https://user-images.githubusercontent.com/14965634/60458929-af7c5f80-9bf4-11e9-9e42-7bc709de033c.png)

We should be using @mirca's `muchbettermoments`: https://github.com/mirca/muchbettermoments

![image](https://user-images.githubusercontent.com/14965634/60458937-b2775000-9bf4-11e9-916d-1d2da9ba5e79.png)

**Comment by barentsen** [comment]
Excellent find, thank you @christinahedges!

And thank you @mirca for solving problems before they appear!

**Comment by mirca** [comment]
credits to @dfm 👍

**Comment by barentsen** [comment]
@mirca Do you think it is best to add `muchbettercentroids` as a dependency, or to borrow the function in Lightkurve?  (I'm trying to trade-off having a large number of dependencies vs avoiding code duplication.  I guess either solution is fine though!)

**Comment by mirca** [comment]
@barentsen I think moving the function over to ``lightkurve`` would be much better :)

**Comment by barentsen** [comment]
The quadratic centroiding method from `muchbettermoments` is now available in Lightkurve.

To check whether we can resolve this issue, I tried it on the target discussed at the top (EPIC 203850058).

I find that `method='quadratic'` yields more robust results when using `aperture_mask='all'`, though it is interesting to note that quadratic centroiding correlates in a non-linear way with `pos_corr`:

![quad1](https://user-images.githubusercontent.com/817669/67048785-b074c680-f0e9-11e9-9c17-5bac0a7a0e12.png)

It is also worth nothing that the performance of `methods='moments'` is much better when using the much smaller `aperture_mask='pipeline'`:

![quad2](https://user-images.githubusercontent.com/817669/67048937-fa5dac80-f0e9-11e9-8edb-96e425c8e396.png)

We'll have to gain more experience with quadratic centroiding to see when and where it should be used, but for the time being I think this issue can be closed!

**Comment by mirca** [comment]
wow, thanks for showing this comparison!
