### ISSUE TITLE
Overlapping EPIC and TIC identifiers cause confusion in data searches

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#543]
@MNGuenther reported via e-mail that this query incorrectly returns zero results:

```lk.search_lightcurvefile(220504623, mission='TESS')```

It looks like this behavior is explained by the fact that the MAST name resolver returns the coordinates for "EPIC 220504623" when 220504623 is passed.  Indeed, using `lk.search_lightcurvefile("TIC 220504623", mission='TESS')` resolves the issue.

Conclusion: when integer IDs without prefix are passed, we should encourage users to add the prefix by emitting a `LightkurveWarning`.

**Comment by gully** [comment]
If the mission is user-supplied and the prefix is not supplied---as in the example above---can we pre-pend the default prefix as a string?  So the warning could say instead "we are assuming you want to search for `TIC 220504623`", and the proceed to search for `TIC 220504623`.

The vast majority of the time, a user providing a mission will be assuming that mission's ID system.

**Comment by gully** [comment]
Just realized the proposal above is identical to a discussion elsewhere:
https://github.com/KeplerGO/lightkurve/issues/533#issuecomment-505155418

**Comment by barentsen** [comment]
I believe this issue has been solved in an effective way by #558, which ensures a helpful warning is issued if the ID is ambiguous, so I think this issue can be closed.

(But please do comment or re-open if you think #558 does not solve this adequately!)
