### ISSUE TITLE
`seismology` __repr__ doesnt put the mission identifier before the ID

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#549]
When calling the __repr__ of the seismology module, the ID appears as:

```
Seismology(ID: 441462736)
```

as opposed to the __repr__ for a `periodogram` or `lightcurve` object, that would appear as

```
TessLightCurve(TICID: 441462736)
```

Specifying the mission ID in Seismology would help alleviate some confusion, but it is a minor issue.

**Comment by gully** [comment]
The periodogram class does not appear to state the mission either:

```python
lc = lk.search_targetpixelfile("EPIC 211771334", campaign=18).download().to_lightcurve(aperture_mask='pipeline')
lc
```
yields:
`KeplerLightCurve(ID: 211771334)`

```python
pg = lc.normalize().to_periodogram()
pg
```

yields:
`LombScarglePeriodogram(ID: 211771334)`

**Comment by gully** [comment]
One way to make this change could be to replace the `targetid` with the `label` attribute in repr:

```python
    def __repr__(self):
        return('Periodogram(ID: {})'.format(self.targetid))
```

would become:
```python
    def __repr__(self):
        return('Periodogram(Source: {})'.format(self.label))
```

**Comment by gully** [comment]
The trick is that not all lightcurve objects possess informative content in the label attribute, though they all get init'ed with at least a `None`:

```python
lc_unlabeled = lk.LightCurve(time=lc.time, flux=lc.flux) # Low-frills lightcurve
lc_unlabeled.label is None
```
yields:
`True`

```python
lc_unlabeled.normalize().to_periodogram()
```
Yields:
`LombScarglePeriodogram(Source: None)`

**Comment by gully** [comment]
Ok, I've done the same for Seismology now too:
```python
pg.flatten().to_seismology()
```
yields:
`Seismology(Source: EPIC 211771334) - no values have been computed so far.`

**Comment by barentsen** [comment]
I like this!  We should consistently use the `label` attribute to label data products, even if custom objects may not have it set.

Minor caveat: `LombScarglePeriodogram(Source: None)` suggests that the periodogram contains "no source", so you may want to re-word that slightly, e.g. `ID: None` may be less confusing?

**Comment by gully** [comment]
A bonus here is that users can override the label, so you can do clarify experiments with:
```python
lc_unlabeled.label = 'V827 Tau with 6 pixel aperture'
```
