### ISSUE TITLE
Tutorial plots do not appear due to absent %matplotlib inline

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#55]
I'm finding many of the tutorial plots do not appear on my system, probably due to a missing `%matplotlib inline`.  When I run `%matplotlib inline`, the figures appear inline, as desired.

**Comment by christinahedges** [comment]
I have inline automatically apply to all my notebooks so I don't need it. I can add this back into the tutorials.

**Comment by barentsen** [comment]
I am going to close this issue because it has been inactive for 1 year.  If anyone experiences problems with plots not showing up in tutorial notebooks, then please do open a new issue!
