### ISSUE TITLE
Setting minimum and maximum frequency when calculating a periodogram changes power of modes

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#552]
The amplitude of seismic modes can change when setting minimum and maximum frequency keyword arguments. This is because the frequency array passed into the astropy lombscargle calculation is:

```python3
np.linspace(minimum_frequency, maximum_frequency, frequency_spacing)
```
and by default it is
```python3
np.linspace(frequency_spacing, nyquist, frequency_spacing)
```

This has the impact that the exact frequencies of the bin shift slightly when setting minimum/maximum keyword arguments, as they are no longer exact multiples of the frequency spacing.

We should change this to something that maintains the mode power no matter what kwargs we set, e.g.:

```python3
np.linspace(min - min % bw, max - max % bw, spacing)
```
(where min =minimum_frequency, max = maximum_frequency, bw is frequency_spacing).

**Comment by keatonb** [comment]
Hey @ojhall94, the bin centers are different if a minimum frequency is specified, but is there any reason to think that periodogram samples at exact multiples of ```frequency_spacing``` represent the ("mode"?) power in a frequency range of interest any better than any other set of critically sampled frequencies?  The current behavior is what I would expect as a user.

**Comment by barentsen** [comment]
I'm going to close this issue because the discussion appears to have ended, however please do re-open as needed. Thanks everyone! :+1:
