### ISSUE TITLE
Consider calibrating seismic scaling relations internally with lightkurve

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#553]
The seismic scaling relations rely on solar constants for the large separation (deltanu) and the frequency of maximum power (numax). These values are currently taken from Huber et al. (2011) (iirc). 

Different estimation methods for numax and deltanu can have undetected biases inherent to the method that the estimation of the solar calibration values did not have. One way of overcoming this is by calculating the solar numax and deltanu from solar data with our own tools, and using those as constants in the seismic scaling relations. This is common practice for major asteroseismic pipelines.

We are, of course, not a major asteroseismic pipeline. So I don't think this is a priority issue, only when/if at some point in the future, lightkurve.seismology:
- provides uncertainties on seismic estimates
- provides multiple estimation methods
- is designed to work on stars unsupervised

So I think we can label this as an enhancement and leave it for now. It would make for a good project for a student somewhere :)

**Comment by barentsen** [comment]
That's an interesting insight.  Thanks @ojhall94 !  We may want to think about adding the function used to retrieve the Solar Data as a Lightkurve helper function, to make it easy to repeat, and perhaps to add it as a sanity check/test.

**Comment by barentsen** [comment]
@ojhall94 Is there a standard "light curve of the sun" people use for this?  If so, where can one find it?

**Comment by ojhall94** [comment]
Tbh, I have no idea! I'll go find out.

**Comment by barentsen** [comment]
I am tempted to close this issue for now because it feels like a research project more than an active software issue, however please do re-open or leave a comment if anyone starts working on this!
