### ISSUE TITLE
Support light curves centered around zero

### ISSUE THREAD

**Issue by keatonb** [KeplerGO/lightkurve#569]
#### Problem description

For light curves input by the user, it is not uncommon for the time series flux to be normalized and mean-subtracted so that the relative flux is centered around zero.

This causes problems when lightkurve attempts to re-normalize (often unnecessarily) the flux by dividing the median which is very close or equal to zero.

The minimum thing to add is a warning of possible bad behavior when ```normalize``` is called on a light curve that contains negative values.

We should also remove unnecessary calls to lc.normalize(), such as the one in ```periodogram.from_lightcurve``` that has no practical effect.  I will submit a pull request for this soon.  Perhaps auto-renormalization could also not be the default where it's an option, like in ```lightcurve.plot``` (change default to ```normalize=False```).

Has zero-centered flux been previously considered for the lightkurve internal default?

#### Example

```python
import numpy as np
import lightkurve as lk

time = np.arange(100)
amp = 0.1 #What we want to measure
freq = 0.08412
flux = amp*np.cos(2*np.pi*np.arange(100)*freq)

lc = lk.LightCurve(time,flux)

ls = lc.to_periodogram(normalization='amplitude')
print(ls.max_power)
```
Gives... 23627464 ppm

#### Expected behavior

Expect to measure close to the input amplitude of 1e5 ppm.  Renormalization under the hood (division by small number) causes the variability to blow up.

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX
-  lightkurve version (e.g. 1.0b6): 1.0.1
-  installation method (e.g. pip, conda, source): conda

**Comment by barentsen** [comment]
Thanks @keatonb!  It is certainly true that Lightkurve hasn't been carefully tested to work on zero-centered light curves so far.

PS: Do you have an understanding of the pros-and-cons of using zero-centered vs one-centered normalized light curves?  Do you reckon folks use one or the other as a matter of taste, or is there more to the choice?

**Comment by keatonb** [comment]
Residuals are basically zero-centered, and the analysis of residuals is of standard interest for time series astronomy (e.g., prewhitening of pulsation signals).  Starting zero-centered makes the analysis of residuals consistent with the initial light curve analysis.  

Zero-centered data can also have the same units as the periodogram (parts-per-million or percent or whatever), which is nice and may help us keep track of units consistently through lightkurve.  Perhaps this issue could be stated more broadly, even, as "support relative units for flux."

**Comment by barentsen** [comment]
Lightkurve now issues warnings if `normalize()` is called on a zero-centered light curve (cf. PR #589).  This does not address this issue entirely, but it's hopefully a step in the right direction!

**Comment by keatonb** [comment]
After seeing how units are being handled with #591, it occurs to me that this problem could be solved if the light curve also had a property indicating whether the values are ``relative`` or ``absolute``.   E.g., a flare could increase a star's brightness by 40% (relative), bringing the flux to 140% of the median value (absolute). If we know a light curve is in relative (zero centered) units, we know not to re-divide the median when re-normalizing (e.g., to change flux units).

**Comment by barentsen** [comment]
@keatonb Thanks for this idea!  I like it.

I've been wondering if we can automatically infer whether a light curve is absolute/relative from the new `flux_unit` property introduced by #591, i.e.:
* if `flux_unit` is `ppm`, `ppt`, `percent`, or `dimensionless`, the values are relative;
* if `flux_unit` is `electron/second` or some other unit of flux, the values are absolute.

Two questions remain on my mind:
* Do you think there is an advantage in having an explicit keyword beyond the units?
* If one tries to normalize a light curve that is already in relative units, should it refuse (raise an exception) or simply emit a warning?

Fortunately the underlying issue has been largely addressed by removing the default normalization steps from both `lc.plot()` and `Periodogram` (these changes were made as part of #591).

**Comment by barentsen** [comment]
Oops, on second thought: note that a light curve can be zero-centered but given in absolute flux units (e.g. this is the case for model residuals).

We know that normalizing a light curve that is already in relative units make no sense, but we cannot automatically infer that normalizing a light cure that is in absolute units always makes sense?

**Comment by keatonb** [comment]
> Oops, on second thought: note that a light curve can be zero-centered but given in absolute flux units (e.g. this is the case for model residuals).

Yes, I think the same physical units can apply to both absolute and relative light curves.  That's why we need to keep track of the extra attribute.

> We know that normalizing a light curve that is already in relative units make no sense, but we cannot automatically infer that normalizing a light cure that is in absolute units always makes sense?

I think both can be renormalized, you just need to add the offset back onto a lightcurve in relative units (e.g., add 1e6 to a `relative` light curve in `ppm` units, renormalize, then subtract the new offset off again).  I'd issue a warning when something supposedly in `absolute` units has negative values, but I also see nothing wrong with something like -150% relative brightness in a light curve, as maybe this refers to the time series of the (absolute) difference in flux counts between light curves of different targets.

**Comment by barentsen** [comment]
Ahh, I think we are speaking about slightly different things.  I think of `relative` as a light curve that has been divided by something, but it sounds like you think of `relative` as a light curve that has had something subtracted.

**Comment by keatonb** [comment]
Yes, `relative` and `absolute` may not be the best terms.  I think if you take a light curve in flux units and divide it by the median or mean, this is still representing the `absolute` light curve (maybe `flux` is better that `absolute`).  So the average absolute percentage brightness of a normalized light curve is 100%, with perhaps +/-10% variability.  The `relative` version of that is zero-centered, but with the same +/-10% variability.  If I was labeling y-axes of my light curve plots, I would probably call these "flux" and "relative flux".

**Comment by barentsen** [comment]
Perhaps `mean-subtracted`, `model-subtracted`, or `offset-subtracted` are better terms here, because `relative` could also be interpreted as `normalized` or `fractional`.

Are you suggesting that Lightkurve keeps track of what value was subtracted from a light curve, and automatically adds it back in if `normalize` is called?  That seems tricky because users may also subtract flux just to e.g. remove a flare from a light curve.

*Should Lightkurve default to zero-centered fluxes?*  I am not in favor because the values obtained by e.g. reading in an official light curve file or executing aperture photometry on a TPF are absolute flux values in units electron/second which have not been subtracted or divided.  I think it makes sense for users the see the data in its default form, whatever that form is.

Of course it can be very useful for light curves to be visualized in a zero-centered way.  Right now we support this via `(lc - np.median(lc.flux)).plot()`.  I'd be happy to consider adding an argument to `plot` to make this easier?

(PS: I think the original issues reported at the top of this issue have been addressed, i.e. `plot` and `periodogram` no longer call `normalize` by default, and a warning was added to `normalize` if the median flux is negative or zero.  In the interest of clarity, I suggest we close this issue here, however please do open a new one for additional proposals!)

**Comment by keatonb** [comment]
I don't think lk needs to keep track of what was subtracted off.  If a light curve is normalized, there's no way to get back the original e-/s units, but I think that's okay.

However, a normalized light curve should be re-normalizable, whether it's zero centered or not.  I think this issue, or one with a very similar name, should be open if the new normalization improvements don't allow a zero-centered light curve to be re-normalized (because it will still divide by a near-zero number).

**Comment by barentsen** [comment]
@keatonb On the current master branch, `LightCurve(time=[1,2,3], flux=[0,0,0]).normalize()` will return a light curve of NaN's along with the following warning:

```
LightkurveWarning: The light curve appears to be zero-centered; 
`normalize()` will divide the light curve by zero or a value close to zero.
(median_flux=0.00e+00, std_flux=0.00e+00).
```

The solution here is for a user to call `(lc + offset).normalize()` instead of `lc.normalize()`.  Do you think the behavior should be different?  Can you post an example?

**Comment by keatonb** [comment]
The reason I think this behavior should be different is that the offset you have to manually apply depends on the units, which leaves room for user error (e.g., if units are ppt, then offset = 1e3; if units are ppm, offset is 1e6).  Since we are now keeping track of light curve units, we could handle that offset ourselves if we knew the light curve was zero centered.

I would like to see something like: 
`LightCurve(time=[1,2,3], flux=[-10,0,10], flux_unit='ppt', zero_centered=True).normalize('ppm').flux`
return
`[-1e4,0,1e4] ppm`

or 

`LightCurve(time=[1,2,3], flux=[-10,0,10], flux_unit='ppt', zero_centered=True).normalize('ppm', zero_centered=False).flux`
return
`[-9.9e5,1e6,1.01e6] ppm`

**Comment by keatonb** [comment]
That was basically my suggestion.  Let's table it for now and see if anyone else has need for this.  You're right that this can be done manually as is.

**Comment by barentsen** [comment]
Thanks Keaton!!  Please do keep thinking about this and feel free to open new issues with examples.  I love that you are making us think about this!!

(I'm going to close this issue for clarity, because I think the original problem has been resolved!)
