### ISSUE TITLE
Slicing and Masking for Target Pixel File

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#57]
I'm addicted to slicing and masking in LightCurve objects. Please can we have it in target pixel files too?

**Comment by barentsen** [comment]
:+1:

**Comment by christinahedges** [comment]
This looks like it would only be possible if you first clipped out the flux values from the fits file and reloaded it.

**Comment by barentsen** [comment]
The same feature is requested in #267.  I'm going to close this issue just to avoid duplicate issues.
