### ISSUE TITLE
Feature requests: ylim for tpf.interact()

### ISSUE THREAD

**Issue by MNGuenther** [KeplerGO/lightkurve#577]
I would like to request an "ylim" feature for tpf.interact(), to be passed as an argument when calling the function: currently "ylim" is set using "get_lightcurve_y_limits(lc_source)", which cuts off data points far away from the median. It would be nice to be able to deactivate this, and always see the full range of data. This is particularly important when looking at flares.

**Comment by barentsen** [comment]
Thank you for opening an issue @MNGuenther! :+1:  We should definitely consider this.  @gully do you want to investigate this further?

**Comment by barentsen** [comment]
@MNGuenther Thanks again for the suggestion! :+1:  We merged #600 yesterday into master yesterday, which adds a `ylim_func` argument to `tpf.interact()` to enable you to set custom y limits.  This feature will be part of the upcoming v1.5.0 release.
