### ISSUE TITLE
test_butler.py::test_plot_echelle() passes conflicting parameters to butler.plot_echelle

### ISSUE THREAD

**Issue by texadactyl** [KeplerGO/lightkurve#587]
#### Problem description
Conflict warnings are emitted for passing both a numax value and either a minimum_frequency or maximum_frequency to butler.plot_echelle().  The following are suggested corrections:
```
    # Assert echelle works with minimum limit
    butler.plot_echelle(deltanu, minimum_frequency = numax)
    butler.plot_echelle(deltanu, maximum_frequency = numax)
    butler.plot_echelle(deltanu, minimum_frequency = u.Quantity(numax, 1/u.day))
    butler.plot_echelle(deltanu, maximum_frequency = u.Quantity(numax, 1/u.day))
    butler.plot_echelle(deltanu, minimum_frequency = u.Quantity(numax-deltanu, 1/u.day), maximum_frequency = numax+deltanu)
```
#### Environment

-  platform: Xubuntu 18.04.3
-  lightkurve version: downloaded from github today
-  installation method: downloaded from github today

**Comment by christinahedges** [comment]
Hi @texadactyl thanks for bringing these to our attention! I'll take a look at these issues and see if I can reproduce the error and get a bugfix underway!

**Comment by texadactyl** [comment]
Hi @christinahedges - My concerns were that the tests:

1. were not actually completing in some cases (E.g. due to sqrt() & log() errors in separate issues #585 & #586 )
2. made deprecated procedure calls (issue #585 )
3. emit distracting & unnecessary warnings that could be easily addressed (E.g. this issue)

You folks are busy with science so I understand your priorities.

**Comment by gully** [comment]
Hmm, I tried the code snippet above and it fails because the "butler" requires *some* numax value if it hasn't already been pre-computed with `estimate_numax()`.  I suspect most of the time, a user will first run estimate_numax, so the snippet above would usually work, but not here: running `estimate_numax()` is computationally slow, so we don't want to repeatedly run it in the tests. I think the best way to silence the warnings in the tests would be to directly catch them with the `warnings` module, or place some additional numax checking near line 167 in the `core` seismology module.

It's also worth revisiting if the warning is needed at all, since the docstring notifies users of the kwargs:

>If a numax is passed, a suitable range one FWHM of the mode envelope either side of the will be shown. This is overwritten by custom frequency ranges.

Perhaps make the logging go from warning.warn a warning.info would help?

**Comment by texadactyl** [comment]
I actually edited test_butler.py as suggested above, ran a pytest on it, and the warnings went away.  That effect seems to agree with the intention of the class Seismology :: plot_echelle() source code and comments: either specify numax or frequency boundaries but not both.

**Comment by texadactyl** [comment]
By the way, I saw another warning that I thought could be suppressed:
```
seismology/core.py:60: LightkurveWarning: Seismology received a periodogram which does not appear to have been background-corrected. Please consider calling `periodogram.flatten()` prior to extracting seismological parameters.
    LightkurveWarning)
```

I thought, no worries.  Just add a pg.flatten() call immediately after setting the following in ```test_plot_echelle()```:
```
pg = Periodogram(f*u.microhertz, u.Quantity(p, None))
```

Bad idea!  I started a test that way and it ran for a very long time before I killed it.  So, I have created a separate test_pg_flatten.py source file in the same directory.  Running it now and measuring the elapsed time.  If it doesn't finish by tomorrow morning, it looks like flatten() goes into a closed loop in some cases.

**Comment by texadactyl** [comment]
It is still running after 15+ hours.  I'll try to figure out why.  Source code:
```
import time
import pytest
import numpy as np
from astropy import units as u
from scipy.signal import unit_impulse as deltafn
from ...periodogram import Periodogram

def generate_test_spectrum():
    """Generates a simple solar-like oscillator spectrum of oscillation modes
    """
    f = np.arange(0, 4000., 0.4)
    p = np.ones(len(f))
    nmx = 2500.
    fs = f.max()/len(f)

    s = 0.25*nmx/2.335    #std of the hump
    p *= 10 * np.exp(-0.5*(f-nmx)**2/s**2)  #gaussian profile of the hump

    m = np.zeros(len(f))
    lo = int(np.floor(.5*nmx/fs))
    hi = int(np.floor(1.5*nmx/fs))

    deltanu_true = 0.294 * nmx ** 0.772
    modelocs = np.arange(lo, hi, deltanu_true/2, dtype=int)

    for modeloc in modelocs:
        m += deltafn(len(f), modeloc)
    p *= m
    p += 1
    return f, p, nmx, deltanu_true

def test_pg_flatten(capsys):
    f, p, numax, deltanu = generate_test_spectrum()
    numax *= u.microhertz
    deltanu *= u.microhertz
    with capsys.disabled():
        print("test_pg_flatten: len(f)=len(p)={}, numax={}, deltanu={}".format(len(f), numax, deltanu))

    pg = Periodogram(f*u.microhertz, u.Quantity(p, None))

    t1 = time.time()
    pg.flatten()
    t2 = time.time()
    with capsys.disabled():
        print("Elapsed time for pg.flatten() = {}".format(t2 - t1))
```

**Comment by texadactyl** [comment]
@gully I see what you mean.  I experienced the same "requires some numax value if it hasn't already been pre-computed with estimate_numax()".  My bad.  Cannot figure out why I did not see this yesterday.  Looks like I traded a warning for a failure!
