### ISSUE TITLE
LightCurveFileCollection class appears to be undocumented

### ISSUE THREAD

**Issue by ceb8** [KeplerGO/lightkurve#597]
#### Problem description
After doing a `lightkurve.search_lightcurvefile` `download_all` call I get a LightCurveFileCollection object. I can't find documentation on that object.

#### Example
```python
import lightkurve
lc_filelist = lightkurve.search_lightcurvefile(8607720, cadence='short', quarter=[2,10]).download_all()
lc_filelist

LightCurveFileCollection of 4 objects:
	KIC 8607720 (4 KeplerLightCurveFiles) Quarters: 2,10,10,10
```
#### Expected behavior
I expected this class to appear in the full classes and methods list: https://docs.lightkurve.org/genindex.html

#### Environment

-  platform: n/a
-  lightkurve version (e.g. 1.0b6): looking in online docs, says V1.1
-  installation method (e.g. pip, conda, source): n/a

**Comment by barentsen** [comment]
Ohh, well spotted. Thanks for reporting this @ceb8!  We need to have sphinx index the collection classes.

**Comment by barentsen** [comment]
The collection classes are now documented here:

    https://docs.lightkurve.org/api/collections.html

For future reference, the solution was to add the file called `docs/source/api/collections.rst`.

Thanks again for reporting @ceb8!  We'll have to do some more work to improve the quality of these doc pages, but at least the collection classes have a page on the docs now!

**Comment by ceb8** [comment]
Thanks @barentsen!
