### ISSUE TITLE
The `plot` method returns the wrong xlabel if run on a folded light curve.

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#6]
I'm not sure how to fix this. The plot method has xlabel as a keyword, but the default is Tim - BJDREF. This is usually fine but if you've folded it this should be Phase. 

<img width="427" alt="screen shot 2018-01-26 at 4 02 31 pm" src="https://user-images.githubusercontent.com/14965634/35465634-591a36ee-02b2-11e8-9044-fe5b36314408.png">

The only solution I can think of is to have an attribute which describes the quantity in `flux` and `time` which would then be used as x and y labels in all the plots.

**Comment by barentsen** [comment]
Thinking out loud: this could be a job for the `meta` attribute, i.e. the `fold()` method could set `lc.meta['is_folded`] = True`.

**Comment by christinahedges** [comment]
I think that it might be better to have some description attribute for what's held in flux, flux_err and time. Then when the user prints them it displays that description? The description can update if you run the fold method or flatten method.


e.g. 

flux: 'Flux in counts [e-s-1]

'lc = lc.normalize()'

flux: 'Normalized Flux'

**Comment by barentsen** [comment]
Interesting.  I wonder if we want to keep track of `flux_label` and `flux_units` as attributes or using the `meta` dictionary.

Related note: right now we don't support astropy `Quantity` at all (if flux is a `Quantity` is converted to a simple numpy array in the constructor of `LightCurve`).

**Comment by christinahedges** [comment]
This can be fixed by the user if they pass the xlabel keyword...but we're not doing it. And it's in all our docs and tutorials and gifs.

**Comment by barentsen** [comment]
I've proposed a fix in #64.

**Comment by barentsen** [comment]
#64 has been merged, meaning this issue should be fixed no!
