### ISSUE TITLE
LightCurve objects store differently in numpy arrays following version 1.2

### ISSUE THREAD

**Issue by alexlyttle** [KeplerGO/lightkurve#619]
#### Problem description
LightCurve objects explode into objects for each row in time/flux when being put into numpy arrays in version 1.2 and above. Before they would just be stored as one LightCurve object. Could this be to do with the changes implemented in #532? 

Is there a way to modify my code so that I can store a LightCurve object in a numpy array in the same way as before v1.2? Or, is this a bug / unforeseen impact relating to recent changes to Lightkurve?

#### Example

```python
import numpy as np
import lightkurve as lk

lc = lk.LightCurve(np.linspace(0, 1, 100), np.random.normal(1.0, 0.01, 100))
print(np.array([lc]))
```

This outputs:

```
[[<lightkurve.lightcurve.LightCurve object at 0x102cab490>
 <lightkurve.lightcurve.LightCurve object at 0x102cab690>
 <lightkurve.lightcurve.LightCurve object at 0x102cab890>
 ...
 <lightkurve.lightcurve.LightCurve object at 0x102cb9850>
 <lightkurve.lightcurve.LightCurve object at 0x102cb98d0>
 <lightkurve.lightcurve.LightCurve object at 0x102cb9950>]]
```

(ellipses added in as output is 100 lines long).

#### Expected behavior

Before version 1.2, this would just output the following:

```
[<lightkurve.lightcurve.LightCurve object at 0x7fda3f0b6470>]
```

#### Environment

-  platform: MacOS 10.15 and CentOS Linux 7
-  lightkurve version: 1.2 and 1.3
-  installation method: pip

**Comment by barentsen** [comment]
Ha!  That's interesting!  The behavior appears to have changed because we added the `LightCurve.__len__` method  in #532, which triggers `np.array` to treat a LightCurve as an iterable.

A work-around is to do the following:
```python
ar = np.empty(1, dtype=object)
ar[0] = lc
```

@alexlyttle Can you provide a bit more background as to why you are interested in being able to have numpy arrays contain Lightcurve objects?

**Comment by gully** [comment]
I'd add---we also offer a `LightCurveCollection` class that can store multiple lightcurves.

**Comment by alexlyttle** [comment]
Thanks for the advice!

#### Background:

I am using / testing / breaking the [PBjam](https://github.com/grd349/PBjam) package which is designed to fit the asteroseismic stellar oscillation modes in a given oscillation spectrum. It uses Lightkurve in one of its classes to allow the user to give it a target ID and some prior data and then automate the fitting / peakbagging process from then on. It uses Lightkurve to search for the LightCurveFile for the target and then converts that to a Periodogram for use in its fitting procedure.

However, this particular class (called `session`) stores its variables in a pandas DataFrame, as it is designed to deal with multiple targets in one session. One of those variables is the `timeseries` which is stored as a LightCurve object. Pandas uses numpy to put the object in its DataFrame, since Lightkurve 1.2, this step fails as it is instead stored as an array of LightCurve objects with a length equal to the number of points in the light curve.

I could suggest we re-think storing LightCurves in a DataFrame, as there may not be much advantage to this over a regular dict or list. In the meantime, we could also apply the above fix.

**Comment by barentsen** [comment]
I'm going to close this issue for now because I do not see a good way to resolve this issue via a change to Lightkurve, unless we remove the `LightCurve.__len__` method, which would be a shame.

Please do re-open this issue if anyone disagrees!

**Comment by alexlyttle** [comment]
Hi @barentsen, thanks for your help on this one. In fact, we found a far better way to solve our issue in our code so this is no longer an issue with Lightkurve for us!

> I do not see a good way to resolve this issue via a change to Lightkurve, unless we remove the LightCurve.__len__ method, which would be a shame.

I agree, this was rightly closed in my opinion. `LightCurve.__len__` is very useful!

**Comment by barentsen** [comment]
Thanks @alexlyttle! We appreciate your feedback!! 🙏
