### ISSUE TITLE
`interact_sky` doesn't look aligned correctly with TESSCut data

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#636]
I have the impression that the catalog overlay feature provided by `interact_sky` is not quite aligned with the data correctly.  Example:

```python
pixels = lk.search_tesscut("proxima Centauri")[1].download(cutout_size=(25, 25))
pixels.interact_sky("http://localhost:8889", magnitude_limit=14)
```

![Screenshot from 2019-11-20 12-37-03](https://user-images.githubusercontent.com/817669/69276172-cbc46d00-0b92-11ea-8ec2-42d14d8ec866.png)

@gully Can you have a look?

**Comment by gully** [comment]
It looks like a 1 pixel offset, which could stem from several causes.  My hunch is:

### An off-by-one error in zero indexing in WCS  
In fact we have a note about looking into the zero or one based indexing:
https://github.com/KeplerGO/lightkurve/blob/2e4e852cad98799752792e050eb8d1eeb0b8de28/lightkurve/interact.py#L235-L240

Parallax effects for Proxima Centauri could add an offset when spot-checking this particular nearby source in high resolution imaging data.  We take into account the proper motion, but not time-dependent parallax.  With TESS/Kepler pixels so large on the sky, we would not see this effect by-eye.

**Comment by gully** [comment]
From the `tpf.wcs.all_world2pix` docstring:

> Here, *origin* is the coordinate in the upper left corner of the
    image.  In FITS and Fortran standards, this is 1.  In Numpy and C
    standards this is 0.

The slightly strange thing is that I recall examples of TPFs for which interact-sky delivers better matches, so then those cases will likely become offset.  I will try to find some examples.

**Comment by gully** [comment]
Here is the reviews sky view replicating the original example:

![image](https://user-images.githubusercontent.com/860227/69458518-5b4d5580-0d24-11ea-9d7b-7e82168713d2.png)

**Comment by gully** [comment]
I spot-checked some other K2 sources and find that the PSF masks differences at the 1 pixel level, so I'm happy to toggle the `1` to a `0` and close this issue.  Upon reading the docstring description of *origin*, it seems clear that we're using numpy arrays so it seems like we should use `0`.
