### ISSUE TITLE
"name 'pixels' is not defined" error by tutorials

### ISSUE THREAD

**Issue by ansainbdg** [KeplerGO/lightkurve#637]
#### Problem description
"name 'pixels' is not defined" error by tutorials

#### Example
I tried to run the tutorial code "https://docs.lightkurve.org/tutorials/04-how-to-remove-tess-scattered-light-using-regressioncorrector.html" as is.

#### Expected behavior
It was not output according to the tutorial, and the following error appeared instead.

import matplotlib.pyplot as plt
plt . plot ( pixels [:, : 30 ]);
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-6d1e6aa5f9dc> in <module>
----> 1 plt . plot ( pixels [:, : 30 ]);

NameError: name 'pixels' is not defined

 dm = lk . DesignMatrix ( pixels , name = 'regressors' )
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-12-97ba41c79724> in <module>
----> 1 dm = lk . DesignMatrix ( pixels , name = 'regressors' )

NameError: name 'pixels' is not defined

The tutorial code runs from the beginning up to here.

#### Environment

-  platform ( windows jupiter notebook):
-  lightkurve version (1.5.0):
-  installation method ( pip):

**Comment by barentsen** [comment]
@ansainbdg Thank you so much for taking the time to report this issue! :+1::+1::+1: 

You were absolutely right, the tutorial contained a few mistakes due to the renaming of variables.

We fixed the issue, so you should be able to run the tutorial now!  Please get in touch if you still encounter problems.
