### ISSUE TITLE
Mosaic method for TPF collection?

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#639]
Recently I've experimented with scipy.sparse and, separately, TPF factory.  I realized it'd be conceivable to add a "mosaic" method to a TPF collection object.  The behavior would be similar to [K2mosaic](http://k2mosaic.geert.io/), but returns a normal-looking TPF object.

```python
import lightkurve as lk
tpfs = lk.search_targetpixelfile('IC1613', mission='K2', campaign=8, radius=80).download_all()
tpf_mosaic = tpfs.mosaic() # <--- proposed feature
```

The key implementation breakthrough here is that with lightkurve and scipy.sparse it is possible to condense the code into a few parts:

1. Populate the [x, y] into column vectors of shapes length n_pix, and f(t) into a matrix of shape (n_cadence, n_pix).
2. De-duplicate (x,y) pairs (if any), and filter out all-NaN columns.
3. Use scipy sparse to make the dense image:
```python
from scipy import sparse
mat = sparse.coo_matrix((z_vals, (x_1D, y_1D)),ffi_data.T.shape)
img = mat.A
```

4. Populate the WCS using the FFI
5. Cutout the delivered data cube to the non-zero x,y extents

The main pro of this method is that it helps you build more informative noise models for your pixels of interest.  If you TPF only has a few "background pixels", you may be able to build better background subtraction from adjacent TPFs.  Seeing them on the same screen and gauging the variable background in their native x,y position helps you visualize whether rolling band has gone through, for example.

Another bonus (or half-measure) could be adding support for TargetPixelFileCollection objects as arguments to interact_sky.  I think Jessie Christensen asked for this feature at last year's AAS in Seattle.  Basically you see all the available TPFs around your target-of-interest.  I say half-measure, just because you don't need to populate all n_cad time slices, just the fiducial frame you'll show in the sky view.

Some cons of this method.  It's fairly boutique.  TESS delivered FFIs, so you'd rarely be in a situation of needing to mosaic the postage stamps, except for adjacent short cadence stamps-- a rare corner case.  For Kepler/K2 this approach may be more common, but we already have the Superstamps and the factory for the most common use case-- cluster science.

Maybe a hybrid is to make a tutorial that shows how it's *possible* to "make your own superstamps", illustrating the steps above.

**Comment by gully** [comment]
btw, this idea ties into an overhaul of TPFfactory, which is imminent now that we've split out the factory functions into factory.py.

**Comment by barentsen** [comment]
I think this is a great idea!!

However, given that we're going to have to switch Lightkurve from development to maintenance mode as our Kepler jobs are ending, I'm tempted to assign the label "candidate-feature" and close this issue unless we decide to actively work on this.

The "candidate-feature" label will act as a way for anyone to discover good ideas for new features in the future.  I encourage anyone wishing to work on a "candidate-feature" to re-open the issue!
