### ISSUE TITLE
Importing Lightkurve v1.5 fails to import due to missing `astropy.stats.calculate_bin_edges`

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#644]
In Lightkurve v1.5 (via #629) we added `from astropy.stats import calculate_bin_edges` to `lightcurve.py` to enable custom binning in the `lc.bin()` method.

This is problematic because the `astropy.stats.calculate_bin_edges` function is only available in Astropy >3.1 and >2.10 (both released just ~one year ago), whereas Lightkurve currently only requires `astropy>=1.3`.

As a result, users with slightly older versions of Astropy installed will see the following error:

```python
>>> import lightkurve
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-23246d7cf2d6> in <module>()
----> 1 import lightkurve as lk

~/dev/lightkurve/lightkurve/__init__.py in <module>()
     21 from .version import __version__
     22 from .prf import *
---> 23 from .lightcurve import *
     24 from .lightcurvefile import *
     25 from .correctors import *

~/dev/lightkurve/lightkurve/lightcurve.py in <module>()
     16 from copy import deepcopy
     17 
---> 18 from astropy.stats import sigma_clip, calculate_bin_edges
     19 from astropy.table import Table
     20 from astropy.io import fits

ImportError: cannot import name 'calculate_bin_edges' from 'astropy.stats' (/Users/gbarents/bin/anaconda/lib/python3.7/site-packages/astropy/stats/__init__.py)
```

**Comment by gully** [comment]
Bummer! My approach will be to see if the astropy version of `calculate_bin_edges` is available, and if not, fall back to [the numpy version](https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram_bin_edges.html#numpy.histogram_bin_edges):

**Comment by barentsen** [comment]
@gully Can't we simply always use the `numpy` version in that case?  I'm a bit fearful of having Lightkurve behave differently depending on a very implicit condition (the installed astropy version).

**Comment by gully** [comment]
We can--- they have different support for string inputs, though string input is likely to be a relatively rare use case.

**Comment by gully** [comment]
Numpy version: 
```
‘auto’
Maximum of the ‘sturges’ and ‘fd’ estimators. Provides good all around performance.

‘fd’ (Freedman Diaconis Estimator)
Robust (resilient to outliers) estimator that takes into account data variability and data size.

‘doane’
An improved version of Sturges’ estimator that works better with non-normal datasets.

‘scott’
Less robust estimator that that takes into account data variability and data size.

‘stone’
Estimator based on leave-one-out cross-validation estimate of the integrated squared error. Can be regarded as a generalization of Scott’s rule.

‘rice’
Estimator does not take variability into account, only data size. Commonly overestimates number of bins required.

‘sturges’
R’s default method, only accounts for data size. Only optimal for gaussian data and underestimates number of bins for large non-gaussian datasets.

‘sqrt’
Square root (of data size) estimator, used by Excel and other programs for its speed and simplicity.
```

Astropy version:
```
If ``bins`` is an int, it is the number of bins. If it is a list
        it is taken to be the bin edges. If it is a string, it must be one
        of  'blocks', 'knuth', 'scott' or 'freedman'
```

**Comment by barentsen** [comment]
I think my preferred solution is this:
* If the behavior of numpy's version is more or less identical and requires minimal code changes, use that. (*)
* Otherwise, let's update the minimum astropy version required for installing Lightkurve.

(*) Note: if this is true, then why does astropy have a different version of the same function?

**Comment by gully** [comment]
numpy introduced `histogram_bin_edges` in https://github.com/numpy/numpy/pull/10591, while astropy introduced `calculate_bin_edges`, which executes `histogram_bin_edges`  in https://github.com/astropy/astropy/pull/7991 

I'm not sure why astropy overrides the native numpy support for certain string inputs-- probably more heritage than scientific motivation?  The original code from astropy comes from astroML I believe, and migrated upstream to astropy.

So to address the question-- numpy's version has only been available since 1.15.0, so more recent than our current requirement: `numpy>=1.11`, motivating a move towards the latter option: `let's update the minimum astropy version required for installing Lightkurve.`, except that we'd also have to upgrade numpy to 1.15 or later.  Thoughts?

**Comment by gully** [comment]
By the way-- a plug for why the string input is useful.  Imagine you have a ground-based sparse lightcurve with episodes of dense sampling, followed by months of no data.  A binned lightcurve with fixed bins will result in tons of empty bins, while density-based algorithms will a rebinned lightcurve closer to what a human would want in the first place.

**Comment by barentsen** [comment]
@gully Is the density-based algorithm provided by the astropy implementation alone, and not provided by numpy?

**Comment by gully** [comment]
Hmmm, how about a hybrid approach:
We specify that the `bins=` kwarg requires astropy version `x` or higher.  That way everyone who used `binsize` before can continue without problems, while if you want the additional features of `bins=` you have to install new astropy.

**Comment by gully** [comment]
Is it preferable to require a higher numpy version than a higher astropy version?

**Comment by barentsen** [comment]
I think I don't mind requiring a more recent version of astropy, it will also allow us to simplify code in a few other places.

**Comment by gully** [comment]
Ok, let's merge this bugfix for now, and then the next version of lightkurve can elevate the astropy and numpy requirements?

**Comment by barentsen** [comment]
Although the CI is not set up to do it, it's important that we spot-check regression fixes.  Doing so, I find that the unit tests fail when using branch #644:

```
$ conda create --name astropy305 python=3.7 astropy=3.0.5 numpy scipy pandas
$ conda activate astropy305
$ pytest
E               ImportError: cannot import name 'calculate_bin_edges' from 'astropy.stats' (/home/gb/bin/anaconda/envs/astropy305/lib/python3.7/site-packages/astropy/stats/__init__.py)
$ git checkout issue_644
$ pytest
E               ImportError:  The `bins=` parameter requires astropy >3.1 or >2.10, you currently have astropy version 3.0.5. Update astropy or use the `binsize` kwarg
```

**Comment by gully** [comment]
Right--- we should test that we raise an import error if astropy is an old version.

**Comment by barentsen** [comment]
#646 should have resolved it:

```bash
$ conda create --name astropy305bis python=3.7 astropy=3.0.5 numpy scipy pandas
$ conda activate astropy305bis
$ pytest --remote-data
=================================== 220 passed, 24 skipped, 30 warnings in 951.34 seconds ====================================
```
