### ISSUE TITLE
JD Values

### ISSUE THREAD

**Issue by newxr** [KeplerGO/lightkurve#647]
When extracting time and flux data from lightcurve files is the JD at the start of exposure, mid exposure or end of exposure?

I suspect as usual it is mid exposure but I can't actually find it written down in any documentation.

#### Example

```python
import lightkurve
# In [11]: lc.astropy_time
Out[11]:
<Time object: scale='tdb' format='jd' value=[2458325.30114092 2458325.30252985 2458325.30391877 ... 2458353.17908419
 2458353.18047307 2458353.18186194]>
```

-  platform (e.g. Linux, OSX, Windows):
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by mrtommyb** [comment]
These are mid-points. There is a keyword in the FITS files called TIMEPIXR that is 0, 0.5 or 1 depending on whether the reported time is the beginning, middle and end.

**Comment by barentsen** [comment]
Thanks for pointing to that keyword @mrtommyb !

It appears to be the middle for both TESS and Kepler:
![Screenshot from 2019-12-09 12-31-11](https://user-images.githubusercontent.com/817669/70475255-0b42f280-1a89-11ea-8e66-c16b0d68d402.png)

@newxr I'm going to close this issue, but feel free to reopen if you have any further questions!
