### ISSUE TITLE
show_properties raises ValueError on generic light curves without astropy_time format

### ISSUE THREAD

**Issue by keatonb** [KeplerGO/lightkurve#655]
#### Problem description
User defined light curves often just have numpy times and fluxes.  The show_properties() function raises a value error for these light curves that do not have astropy_time formatted times.

#### Example

```python
import lightkurve as lk
import numpy as np
lc = lk.LightCurve(time=np.arange(10), flux=np.ones(10))
lc.show_properties()
```
returns
> ValueError: To retrieve a `Time` object the `time_format` attribute must be set on the LightCurve object, e.g. `lightcurve.time_format = 'jd'`.

#### Expected behavior

Should print values for all valid attributes, ignoring `astropy_time` when not available.

#### Environment

-  platform (OSX):
-  lightkurve version (e.g. 1.7.dev0):
-  installation method (e.g. source):

**Comment by barentsen** [comment]
Oops!  That looks like a bug!  Thanks @keatonb!  :+1:

**Comment by gully** [comment]
This behavior may change when #604 and linked PRs are merged--- we've streamlined the base classes to hold more attributes and methods that were common among the subclasses.
