### ISSUE TITLE
Zero-centered light curves have a numerical advantage over one-centered light curves

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#659]
At #AAS235, @dfm correctly pointed out that one-centered (normalized) light curves have the disadvantage of wasting digits in the significand part of the floating point.

For example:
* A 1ppm signal in a one-centered normalized light curve will be stored as `flux=1.000001`, requiring 7 digits.
* In a zero-centered light curve, the same signal could be stored as `flux=1e-6`, requiring only 1 digit in the significand.

@dfm reported that the loss of precision in the one-centered case can occasionally lead to problems in e.g. iterative transit-fitting applications.

At this time Lightkurve has been designed without this insight in mind (e.g. the `normalize()` method returns one-centered light curves).  Is there anything we can or should change on this front?  Please leave thoughts below!

**Comment by jcsmithhere** [comment]
I concur with @dfm! Some methods also presume zero-centered light curves. It would probably not be much work to at least have an option when you normalize a light curve to choose zero-centering. 

My methods that I was going to create for cbvcorrector assumes zero-based. Though, it's not much effort to first subtract 1.0 from the lc before proceeding.

**Comment by jcsmithhere** [comment]
Also, the lightcurve.normalize() method performs median normalization. That can be best for many applications, and for visualization, but for some methods, such as PCA, mean normalization can be better. If you median normalize before PCA then you risk introducing artifacts in your basis vectors.

**Comment by keatonb** [comment]
Already some relevant discussion in #569

**Comment by christinahedges** [comment]
The discussion of the zero-centered light curve being more numerically stable than the one-centered light curve is really interesting! I feel that `lightkurve` already has the ability to handle zero-centered light curves in a useful way

e.g.
`zero_centered = (lc - mean)/mean`

I believe it should mostly be up to the user to decide how to/when to use a zero-centered light curve, adding in too much functionality into `lightkurve` will make it more error prone. However, I would like to go through `lightkurve` and create some tests for zero-centered light curves, and check that `lightkurve` produces reasonable error messages. I've opened an issue for this (#674)

**Comment by barentsen** [comment]
Thanks @christinahedges!  I agree with this way forward.  If anyone disagrees, please do reopen the issue and/or leave a comment below!
