### ISSUE TITLE
lk.SFFCorrector should warn users against TESS data

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#660]
Andrew Vanderburg has asked if we could add a warning for users who try to use SFFCorrector on TESS data. The warning should ideally explain that it's not *ideal* for TESS data, and sign post a tutorial discussion on why.

**Comment by barentsen** [comment]
I think this makes sense!

**Comment by barentsen** [comment]
This has been implemented via #676. Closing issue!
