### ISSUE TITLE
Consider adding a `gap` property to `TessLightCurve` objects

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#666]
It is available as a column in TESS Light Curve Files, and they indicate cadences that were gapped by the pipeline analysis (they are not necessarily flagged by quality flags, though they will include all those flagged by relevant flags!)

**Comment by barentsen** [comment]
@jcsmithhere I inspected at TESS light curve file and do not see an extra `GAP` column.  I believe this column is only present in the CBV files, so it probably doesn't make sense to add it as a property of `TessLightCurve`?

```python
>>> import lightkurve as lk
>>> lcf = lk.search_lightcurvefile("Kepler-10", mission='TESS').download()
>>> lcf.hdu[1].data.columns
ColDefs(
    name = 'TIME'; format = 'D'; unit = 'BJD - 2457000, days'; disp = 'D14.7'
    name = 'TIMECORR'; format = 'E'; unit = 'd'; disp = 'E14.7'
    name = 'CADENCENO'; format = 'J'; disp = 'I10'
    name = 'SAP_FLUX'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'SAP_FLUX_ERR'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'SAP_BKG'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'SAP_BKG_ERR'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'PDCSAP_FLUX'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'PDCSAP_FLUX_ERR'; format = 'E'; unit = 'e-/s'; disp = 'E14.7'
    name = 'QUALITY'; format = 'J'; disp = 'B16.16'
    name = 'PSF_CENTR1'; format = 'D'; unit = 'pixel'; disp = 'F10.5'
    name = 'PSF_CENTR1_ERR'; format = 'E'; unit = 'pixel'; disp = 'E14.7'
    name = 'PSF_CENTR2'; format = 'D'; unit = 'pixel'; disp = 'F10.5'
    name = 'PSF_CENTR2_ERR'; format = 'E'; unit = 'pixel'; disp = 'E14.7'
    name = 'MOM_CENTR1'; format = 'D'; unit = 'pixel'; disp = 'F10.5'
    name = 'MOM_CENTR1_ERR'; format = 'E'; unit = 'pixel'; disp = 'E14.7'
    name = 'MOM_CENTR2'; format = 'D'; unit = 'pixel'; disp = 'F10.5'
    name = 'MOM_CENTR2_ERR'; format = 'E'; unit = 'pixel'; disp = 'E14.7'
    name = 'POS_CORR1'; format = 'E'; unit = 'pixels'; disp = 'E14.7'
    name = 'POS_CORR2'; format = 'E'; unit = 'pixels'; disp = 'E14.7'
)
```

**Comment by jcsmithhere** [comment]
@barentsen You're right! The gap indicators are not in the FITS files. There was apparently a decision not to export the gaps. All that is in there is the data quality flags. Which, I'm pretty sure is not synonymous with the gap indicators when "anded" together. OK, I believe it is mostly true that the data quality flags indicate where gaps exist and it's all we got. The FITS files will not change at this point.

OK, the gap field will be specific to just the CBV objects.

**Comment by barentsen** [comment]
Sounds good!  Closing this issue =)
