### ISSUE TITLE
from archive fails when campaign is specified

### ISSUE THREAD

**Issue by jessie-dotson** [KeplerGO/lightkurve#68]
<img width="779" alt="screen shot 2018-03-05 at 11 39 02 am" src="https://user-images.githubusercontent.com/20976560/36987226-db09502a-2069-11e8-828c-05eb4715373f.png">

If you take the campaign specification out, the command works.

**Comment by barentsen** [comment]
Thank you for reporting this issue @jessie-dotson!  This was a genuine bug which has now been fixed.
