### ISSUE TITLE
TESS Quality Bitmasks

### ISSUE THREAD

**Issue by mis-95** [KeplerGO/lightkurve#684]
May be an error or just an issue needing clarification. The documentation for the TESS quality bitmasks appears to be inconsistent. In https://docs.lightkurve.org/api/lightkurve.lightcurvefile.TessLightCurveFile.html, the bitmasks described are the Kepler bitmasks, whereas in https://docs.lightkurve.org/api/lightkurve.utils.TessQualityFlags.html, the TESS bitmasks are listed. Is this a mistake or can lightkurve interpret Kepler bitmasks when representing TESS data?

**Comment by barentsen** [comment]
@mis-95 You are absolutely correct, the docstring of `TessLightCurveFile` was copy-pasted from `KeplerLightCurveFile` and, as a result, contains incorrect integer bitmask values in its description.

We will correct/update this asap!

Thank you for letting us know! :pray:

**Comment by barentsen** [comment]
Lightkurve v1.8.0 was released today.  The documentation includes a fix for this issue!
