### ISSUE TITLE
Look into using `jax.jit`

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#686]
@mrtommyb showed me an example in which a piece of numpy-using code was sped up 100x by doing this:
```
import jax.numpy as np
from jax import jit
jit(some_function_that_uses_numpy_a_lot)
```

Given that Lightkurve relies heavily on numpy, it may be worth investigating if some of our slower functions can benefit from jax!

**Comment by christinahedges** [comment]
I remember learning this at last TESS ninja, it's a great idea. I seem to remember testing some of our functions and it breaking with difficult error messages, but I'd love to see if we could speed up the e.g. fold functions/BLS functions. 

Does having jax as a requirement break anything important for users?

**Comment by barentsen** [comment]
This is being evaluated as part of the work on `SparseDesignMatrix`.  This issue can be closed!
