### ISSUE TITLE
LightCurve.correct() does not work with SciPy 0.17

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#69]
The exception said `scipy.interpolate.BSpline not found`.  Upgrading from scipy 0.17 to scipy 0.19 resolved the problem for the user.

**Comment by mirca** [comment]
That makes sense to me: https://github.com/scipy/scipy/blob/4b6f71ab37bda20687ff493669a53cb15fb0b35f/doc/release/0.19.0-notes.rst#scipy-interpolate-improvements

**Comment by barentsen** [comment]
:+1: Thanks @mirca!  You rule New York!
