### ISSUE TITLE
Downloading certain data products does not work for Kepler and K2

### ISSUE THREAD

**Issue by alexlyttle** [KeplerGO/lightkurve#690]
#### Problem description
`lk.search_lightcurvefile().download_all()` raises a `FileNotFoundError` when specifying a custom `download_dir` **only** when the mission is *Kepler* or K2. On the contrary, a custom `download_dir` works for TESS lightcurve files (see examples below).

#### Example

When downloading *Kepler* lightcurve files to a specified `download_dir` I get the following error, e.g.

```python
import lightkurve as lk

LK_CACHE_DIR = 'test/lightkurve-cache'
ID = 'KIC4448777'
MISSION = 'Kepler'

lcc = lk.search_lightcurvefile(ID, mission=MISSION).download_all(download_dir=LK_CACHE_DIR)
```

```
Traceback (most recent call last):
  File "/Users/ajl573/Repos/alexlyttle/jam-ensemble/test_lk_cache.py", line 7, in <module>
    lcc = lk.search_lightcurvefile(ID, mission=MISSION).download_all(download_dir=LK_CACHE_DIR)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/utils.py", line 473, in wrapper
    return f(*args, **kwargs)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/search.py", line 293, in download_all
    cutout_size=cutout_size))
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/search.py", line 179, in _download_one
    return _open_downloaded_file(path, quality_bitmask=quality_bitmask)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/search.py", line 1013, in _open_downloaded_file
    return open(path, **kwargs)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/search.py", line 997, in open
    raise e
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/lightkurve/search.py", line 990, in open
    with fits.open(path_or_url) as temp:
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 151, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 390, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1039, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/utils/decorators.py", line 521, in wrapper
    return function(*args, **kwargs)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/file.py", line 178, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/file.py", line 555, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/Users/ajl573/.virtualenvs/base/lib/python3.7/site-packages/astropy/io/fits/util.py", line 397, in fileobj_open
    return open(filename, mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: 'test/lightkurve-cache/mastDownload/Kepler/kplr004448777_lc_Q111111111111111111/kplr004448777-2009131105131_llc.fits'
```

and the same error occurs with K2 lightcurve files, e.g.

```python
ID = '220397845'
MISSION = 'K2'
```

Lightkurve creates the download directories but not files are present.

#### Expected behavior

The above works with TESS lightcurves, I expect it to run without exceptions, e.g.

```python
import lightkurve as lk

LK_CACHE_DIR = 'test/lightkurve-cache'
ID = 'TIC146264536'
MISSION = 'TESS'

lcc = lk.search_lightcurvefile(ID, mission=MISSION).download_all(download_dir=LK_CACHE_DIR)
```

This runs fine and I see the cached files under 'test/lightkurve-cache/mastDownload...'.

#### Environment

-  platform: macOS 10.15.3 Catalina
-  lightkurve version: 1.8 (I have tested this on previous versions)
-  installation method: pip

**Comment by ceb8** [comment]
I am seeing this same problem using the default cache location. (I verified that I can download Kepler light curves from MAST directly using Astroquery).

**Environment**

- platform: macOS 10.13.6 High Sierra
- lightkurve version: 1.8 (also encountered this behavior on 1.1.1)
- installation method: pip

**Comment by alexlyttle** [comment]
That's interesting, I didn't think to check the default location because it had worked for me in the past. I'll do some more investigating when I next have time.
________________________________

**Comment by barentsen** [comment]
I confirm there appears to be an issue, which occurs regardless of the download dir chosen (as reported above by @ceb8).

It looks like the download operation failed.  I believe this is an issue on the MAST side, because `astroquery` is reporting the following error:
```
HTTPError: 404 Client Error: Not Found for url: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:Kepler/url/missions/kepler/lightcurves/0042/004245538/kplr004245538-2009166043257_llc.fits
```

For example, this does not appear to work:

```python
>>> from astroquery.mast import Observations
>>> obs = Observations.query_criteria(objectname="KIC4448777", project="Kepler", obs_collection="Kepler")
>>> print(obs['obs_id'][0])
kplr004245538_lc_Q011111111111111111
>>> products = Observations.get_product_list(obs[0])
>>> manifest = Observations.download_products(products[1:2])
>>> print(manifest['Status'])
 ERROR
>>> print(manifest['Message'])
HTTPError: 404 Client Error: Not Found for url: https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:Kepler/url/missions/kepler/lightcurves/0042/004245538/kplr004245538-2009166043257_llc.fits
```

@ceb8 @scfleming @mustaric Any thoughts?

**Comment by ceb8** [comment]
Oh interesting, the random Kepler file I picked to download to test this worked fine, so it must not be all of them.... Will explore.

**Comment by ceb8** [comment]
Problem has been fixed on the MAST end, should be working now.

**Comment by alexlyttle** [comment]
Thanks, that's brilliant! I'm glad this wasn't a lightkurve issue, although might it be worth having a error message to catch this in future, before the file is opened by lightkurve?
________________________________

**Comment by barentsen** [comment]
Thank you @ceb8. I confirm all seems fine again!

@alexlyttle Thank you so much for taking the time to report! :+1:

**Comment by ganesh1076** [comment]
Hi,
I am facing a similar problem with downloading data from K2 with the following:

`lk.search_targetpixelfile('EPIC228164766',mission='K2')`
No data was found for target "EPIC228164766".

The MAST shows that it has an FFI observation for the target at k2-c09 but can't access it through the above line (I couldn't understand clearly from the documentation what one should use for K2)
Thanks
