### ISSUE TITLE
Issue with applying cutouts to a collection of target pixel files

### ISSUE THREAD

**Issue by svaverbe** [KeplerGO/lightkurve#701]
The routine below needs to be adapted to process lightcurves for TESS objects in different sectors. 
I have set cutout_size to 10, but the size of the resulting cutouts is only 4X4(see the output below).  A conflict ensues with the size of the pipeline mask.  Is this a mistake in the routine ? This is lightcurve 1.5.1 on Ubuntu linux installed using conda.

def Cutout_TargetPixelFile_2(tic,sectors):

    print(sectors)
   
    stitched_lc_time=[]
    stitched_lc_flux=[]
    stitched_lc_flux_err=[]
   
    search_result=search_tesscut('TIC'+str(tic),sector=sectors).download_all()
   
    for tpf in search_result:
   
        target_mask=tpf.pipeline_mask
       
#      cutout_size=np.shape(target_mask)[0]
       
        print(cutout_size)
   
        tpf = tpf.cutout(size=cutout_size)
       
        print(tpf.shape)

#        tpf=tpf.download(cutout_size=cutout_size)
   
#        median_image = np.nanmedian(tpf.flux, axis=0)

# Select pixels which are brighter than the 85th percentile of the median image
#        target_mask = median_image > np.nanpercentile(median_image, percentile)

        target_lc = tpf.to_lightcurve(aperture_mask=target_mask).remove_nans()
   
# Make a design matrix and pass it to a linear regression corrector

        dm = lightkurve.DesignMatrix(tpf.flux[:, ~target_mask], name='pixels').pca(ncomp_pca).append_constant()
        rc = lightkurve.RegressionCorrector(target_lc)
        corrected_lc = rc.correct(dm)
   
# Remove the scattered light, allowing for the large offset from scattered light
        corrected_lc = target_lc - rc.model_lc + np.percentile(rc.model_lc.flux, 5)
   
        time=corrected_lc.time
        flux=corrected_lc.flux
        flux_err=corrected_lc.flux_err
   
        centroids_x,centroids_y = tpf.estimate_centroids(aperture_mask=target_mask)
       
        print(time,flux,flux_err)
       
        sys.exit()
   
        with PdfPages('Tesscut_'+str(tic)+'.pdf') as pdf:
   
         plt.figure()
         tpf.plot(aperture_mask=target_mask, mask_color='k')
         pdf.savefig()
         plt.close()
         
         plt.figure()
         plt.plot(time, target_lc.flux/np.median(target_lc.flux), 'r',label='target flux')
         plt.plot(time, rc.model_lc.flux/np.median(rc.model_lc.flux) , 'g',label='background flux')
         plt.plot(time, corrected_lc.flux/np.median(corrected_lc.flux), 'b',label='corrected flux')
         plt.title('detrended fluxes')
         plt.legend(loc='best')
         plt.ylabel('Normalized Flux')
         plt.xlabel('Time')
         pdf.savefig()
         plt.close()

    return time,flux,flux_err,centroids_x,centroids_y

Dit is de uitvoer:

python CARMENES_lightcurves.py
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
298071899 [14 15 20]
Processing TIC 298071899
[14 15 20]
0% (4/1241) of the cadences will be ignored due to the quality mask (quality_bitmask=175).
1% (7/1197) of the cadences will be ignored due to the quality mask (quality_bitmask=175).
0% (5/1188) of the cadences will be ignored due to the quality mask (quality_bitmask=175).
10
0% (4/1241) of the cadences will be ignored due to the quality mask (quality_bitmask=175).
(1237, 4, 4)
Traceback (most recent call last):
  File "CARMENES_lightcurves.py", line 908, in <module>
    time,flux,flux_err,centroids_x,centroids_y=Cutout_TargetPixelFile_2(tic,sectors)
  File "CARMENES_lightcurves.py", line 117, in Cutout_TargetPixelFile_2
    target_lc = tpf.to_lightcurve(aperture_mask=target_mask).remove_nans()
  File "/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/lightkurve/targetpixelfile.py", line 372, in to_lightcurve
    return self.extract_aperture_photometry(**kwargs)
  File "/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/lightkurve/targetpixelfile.py", line 1675, in extract_aperture_photometry
    aperture_mask = self._parse_aperture_mask(aperture_mask)
  File "/home/siegfried/anaconda3/envs/CARMENES/lib/python3.7/site-packages/lightkurve/targetpixelfile.py", line 404, in _parse_aperture_mask
    "".format(aperture_mask.shape, self.flux[0].shape))
ValueError: `aperture_mask` has shape (5, 5), but the flux data has shape (4, 4)

**Comment by barentsen** [comment]
@svaverbe Did you manage to resolve the issue?

I see that you are using the `pipeline_mask` from the original tpf, i.e.:
```python
target_mask=tpf.pipeline_mask
```
The `target_mask` variable in the line above will be a 2D boolean array with the shape of the TPF flux (e.g. 5x5).

...next, I see you reduce the size of the TPF (e.g. to 4x4), and then you try to use that new TPF to create a lightcurve with the old `target_mask`:
```python
tpf = tpf.cutout(size=cutout_size)
target_lc = tpf.to_lightcurve(aperture_mask=target_mask).remove_nans()
```

This doesn't work because `target_mask` still has the shape of the original tpf (5x5), but you created a new (4x4) tpf with the `cutout` command, hence you encounter the error:
```ValueError: aperture_mask has shape (5, 5), but the flux data has shape (4, 4)```

My recommendation is to create a lightcurve using an automated threshold-based aperture mask, i.e. `aperture_mask="threshold"` or `aperture_mask=tpf.create_threshold_mask()`.

Does that make sense?

**Comment by svaverbe** [comment]
I solved the issue by creating my own mask based on the tpf data.  Also, since the FFIs do not have a pipeline mask available(or is there one ?), it could not have worked from the start.

**Comment by barentsen** [comment]
Great!

Indeed, the pipeline mask is empty for FFI cutouts, i.e. it's a mask with zero pixels.

Do open a new issue if you encounter any more issues!
