### ISSUE TITLE
No plots being generated in Pycharm 2019.2.3

### ISSUE THREAD

**Issue by roadtripguyGit** [KeplerGO/lightkurve#703]
#### Problem description
Trying to run the quickstart code in Pycharm with Conda interpreter (Python 3.7) and no plots are being generated. (Note: I am not using a Jupyter Notebook for this process)

#### Example
```
from lightkurve import search_targetpixelfile

pixelfile = search_targetpixelfile('KIC 8462852', quarter=16).download(quality_bitmask='hardest')
pixelfile.plot(frame=1)
lc = pixelfile.to_lightcurve(aperture_mask='all')
print(lc.time, lc.flux)
lc.plot()
```

#### Expected behavior
I expected plots to come up in either a seperate window (similar to matplotlib) or display in the "SciView" section of Pycharm. I am new to this, so not sure if that is what is supposed to happen.

#### Environment
-  platform: Windows 10
-  lightkurve version: 1.9.0
-  installation method: Conda via the terminal in PyCharm with this command:
conda install --channel conda-forge lightkurve

#### Output
Warning: 25% (1042/4203) of the cadences will be ignored due to the quality mask (quality_bitmask=2096639).
[1472.11777934 1472.13821223 1472.15864492 ... 1557.89718798 1557.9380561
 1557.95849016] [258645.03 258660.05 258690.08 ... 258929.86 258884.66 258865.6 ]

Process finished with exit code 0

**Comment by barentsen** [comment]
@roadtripguyGit Thank you for reporting this problem!

I'm not familiar with PyCharm myself, so I'd have to experiment, or ask help from someone more familiar with PyCharm on Windows.

Question: do other matplotlib plots work correctly?  For example, does the following code produce a plot:
```python
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```

A common solution to this type of problem is to call `plt.show()` explicitely.  Does that show a plot?

**Comment by roadtripguyGit** [comment]
@barentsen Thanks for getting back to me.

```
import matplotlib.pyplot as plt
plt.plot([1,2,3])
```
The above code alone does not produce a plot in PyCharm. Adding plt.show() does produce a plot, as you suggested.

Going back to the quickstart code, the following produces an error:
```
from lightkurve import search_targetpixelfile

pixelfile = search_targetpixelfile('KIC 8462852', quarter=16).download(quality_bitmask='hardest')
pixelfile.plot(frame=1)
lc = pixelfile.to_lightcurve(aperture_mask='all')
print(lc.time, lc.flux)
lc.plot()
lc.show()
```

>     lc.show()
> AttributeError: 'KeplerLightCurve' object has no attribute 'show'

How would I go about calling .show() in the quickstart code in the same way as the matplotlib example you gave initially? Do I need to import matplotlib and somehow pass output from Lightkurve to it so that it can draw properly?

**Comment by barentsen** [comment]
@roadtripguyGit Lightkurve uses Matplotlib internally, so you should be able to get things working simply by appending
```python
import matplotlib.pyplot as plt
plt.show()
```
...at the bottom of your Lightkurve-based script/code.

Does that work?

Of course this is not user-friendly at all!  We should figure out how we can avoid this.  Matplotlib can be configured to behave in an "interactive" and "non-interactive" mode, and it looks like in your system/editor behaves in the non-interactive mode.

**Comment by roadtripguyGit** [comment]
@barentsen Yes! That was successful. PyCharm by default (as far as I know) is certainly not interactive with respect to matplotlib. Regardless, your suggestions were correct and I'm now seeing what I expect.
Thank you so much for your help.

**Comment by barentsen** [comment]
@roadtripguyGit Thanks for reporting back!!

We should be able to detect interactive or non-interactive mode.  We could yield a warning when someone calls a `.plot()`. method in non-interactive mode, but then this will be noisy for users who are intentionally doing so.  Hmmm....  Anyone else wants to weigh in?
