### ISSUE TITLE
Issue when using tpf = search_result.download(cutout_size=20)

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#710]
When using the following code.
import lightkurve as lk
search_result = lk.search_tesscut('HAT-P-11', sector=14)
tpf = search_result.download(cutout_size=20)

I get the following error message 

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size)
    150                                                 download_dir,
--> 151                                                 cutout_size)
    152             except Exception as exc:

~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in _fetch_tesscut_path(self, target, sector, download_dir, cutout_size)
    366         sec = TesscutClass().get_sectors(coords)
--> 367         sector_name = sec[sec['sector'] == 1]['sectorName'][0]
    368         if isinstance(cutout_size, int):

astropy/table/_column_mixins.pyx in astropy.table._column_mixins._ColumnGetitemShim.__getitem__()

astropy/table/_column_mixins.pyx in astropy.table._column_mixins.base_getitem()

astropy/table/_column_mixins.pyx in astropy.table._column_mixins.column_getitem()

IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:

SearchError                               Traceback (most recent call last)
<ipython-input-1-590ed5b4510a> in <module>
      1 import lightkurve as lk
      2 search_result = lk.search_tesscut('HAT-P-11', sector=14)
----> 3 tpf = search_result.download(cutout_size=20)

~/Desktop/TESS_LK/lightkurve/lightkurve/utils.py in wrapper(*args, **kwargs)
    471             sys.stdout = devnull
    472             try:
--> 473                 return f(*args, **kwargs)
    474             # restore to default
    475             finally:

~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in download(self, quality_bitmask, download_dir, cutout_size)
    236                                   quality_bitmask=quality_bitmask,
    237                                   download_dir=download_dir,
--> 238                                   cutout_size=cutout_size)
    239 
    240     @suppress_stdout

~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size)
    161                     raise SearchError('Unable to download FFI cutout. Desired target '
    162                                     'coordinates may be too near the edge of the FFI.'
--> 163                                     'Error: {}'.format(exc))
    164 
    165             return _open_downloaded_file(path,

SearchError: Unable to download FFI cutout. Desired target coordinates may be too near the edge of the FFI.Error: index 0 is out of bounds for axis 0 with size 0

**Comment by barentsen** [comment]
@rebekah9969 Weird! Would you be able to let me know your Lightkurve version number (i.e. `print(lk.__version__)`)?

**Comment by rebekah9969** [comment]
1.8.0

**Comment by svaverbe** [comment]
I have seen the same kind of error when upgrading to 1.9.0 this morning.  In version 1.8.0 and earlier it does not appear with me.  It makes all work with search_tesscut impossible because it seems to happen irrespective of the target.

**Comment by barentsen** [comment]
The example posted at the top of this issue is working for me.  Would either of you be willing to try again?

When MAST ingests a new sector of TESS data into the TessCut service, the service occasionally goes down for a limited of time.  The service may also experience load issues at times.  It is therefore important to verify that the issues you both encountered were not transient (which would suggest a server-side rather than a Lightkurve issue).  Thanks++++!

![Screenshot from 2020-03-24 11-39-46](https://user-images.githubusercontent.com/817669/77464335-406b1a80-6dc4-11ea-8cb6-30960c12c5f8.png)

**Comment by rebekah9969** [comment]
Hello Gurt
I  just tried this and got the same error.

---------------------------------------------------------------------------IndexError
                               Traceback (most recent call
last)~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_download_one(self, table, quality_bitmask, download_dir, cutout_size)
   150
download_dir,--> 151
cutout_size)    152             except Exception as exc:
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_fetch_tesscut_path(self, target, sector, download_dir, cutout_size)
 366         sec = TesscutClass().get_sectors(coords)--> 367
sector_name = sec[sec['sector'] == 1]['sectorName'][0]    368
if isinstance(cutout_size, int):
astropy/table/_column_mixins.pyx in
astropy.table._column_mixins._ColumnGetitemShim.__getitem__()
astropy/table/_column_mixins.pyx in astropy.table._column_mixins.base_getitem()
astropy/table/_column_mixins.pyx in
astropy.table._column_mixins.column_getitem()
IndexError: index 0 is out of bounds for axis 0 with size 0

During handling of the above exception, another exception occurred:
SearchError                               Traceback (most recent call
last)<ipython-input-1-8884208c7ff5> in <module>      1 import
lightkurve as lk      2 search_result  = lk.search_tesscut('HAT-P-11',
sector=14)----> 3 tpf = search_result.download(cutout_size=20)
~/Desktop/TESS_LK/lightkurve/lightkurve/utils.py in wrapper(*args,
**kwargs)    471             sys.stdout = devnull    472
try:--> 473                 return f(*args, **kwargs)    474
  # restore to default    475             finally:
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in download(self,
quality_bitmask, download_dir, cutout_size)    236
              quality_bitmask=quality_bitmask,    237
                 download_dir=download_dir,--> 238
              cutout_size=cutout_size)    239     240
@suppress_stdout
~/Desktop/TESS_LK/lightkurve/lightkurve/search.py in
_download_one(self, table, quality_bitmask, download_dir, cutout_size)
   161                     raise SearchError('Unable to download FFI
cutout. Desired target '    162
'coordinates may be too near the edge of the FFI.'--> 163
                       'Error: {}'.format(exc))    164     165
    return _open_downloaded_file(path,
SearchError: Unable to download FFI cutout. Desired target coordinates
may be too near the edge of the FFI.Error: index 0 is out of bounds
for axis 0 with size 0

**Comment by barentsen** [comment]
Weird, it's still working fine for me!

@rebekah9969 Would you be willing to:

1. Re-run the example with debugging output enabled, and post the debug messages on the GitHub issue.  You can use the following snippet to enable debugging messages:
```python
import lightkurve as lk
lk.log.setLevel("DEBUG")
search_result  = lk.search_tesscut('HAT-P-11', sector=14)
tpf = search_result.download(cutout_size=20)
```

The debugging messages should show this:
```
Started querying MAST for observations within 0.0001 arcsec of objectname='HAT-P-11'.
MAST found 5 observations. Now querying MAST for the corresponding data products.
Found 1 matching cutouts.
Started downloading TESSCut for 'HAT-P-11' sector 14.
Finished downloading.
Opening /home/gb/.lightkurve-cache/tesscut/tess-s0014-2-4_297.709364_48.080860_20x20_astrocut.fits.
Detected filetype: 'TessTargetPixelFile'.
0% (4/1241) of the cadences will be ignored due to the quality mask (quality_bitmask=175).
```

It is possible that the debugging messages mention that a cached file is being used on your system.  In that case, deleting the cached file may solve the issue. **However** please save a copy of the cached file before deleting it.  If a corrupt cache file is the culprit, I would love to receive a copy of it to diagnose what went wrong.


2. If the above didn't yield a solution, could you confirm which version of Lightkurve you are using (`print(lk.__version__)`) and verify that you also encounter the issue when using the latest Lightkurve version i.e. v1.9.1.  We had a bug inside `search_tesscut` on the master branch at some point in February, but it was fixed before we released v1.9.0.

**Comment by rebekah9969** [comment]
When I use the debug option you suggested I get the following,

Started querying MAST for observations within 0.0001 arcsec of
objectname='HAT-P-11'.
MAST found 5 observations. Now querying MAST for the corresponding
data products.
Found 1 matching cutouts.
Started downloading TESSCut for 'HAT-P-11' sector 14.


And then the same error

**Comment by rebekah9969** [comment]
I just updated to 1.9.1 and it now seems to work.

**Comment by barentsen** [comment]
Perfect.  Thanks for confirming! :+1:
