### ISSUE TITLE
Set a global cache location

### ISSUE THREAD

**Issue by warrickball** [KeplerGO/lightkurve#711]
It would be convenient to be able to somehow set the default cache directory so that I don't have to retype it myself in each script that I use. There's admittedly limited use for this except that we're expected to analyse a *lot* of TESS data so set up a common location for our caches so that we aren't duplicating data. Another use case would be to put the cache on a different (presumably larger) disk than where the home folder is mounted (e.g. if you have a small SSD and a large optical drive).

This is possibly easy enough to implement that I'd have a go at it myself but I'm not sure what the standard or preferred method for setting global module variables would be. I think all that needs to change is [this line](https://github.com/KeplerGO/lightkurve/blob/master/lightkurve/search.py#L311) in `SearchResult._default_download_dir()`
````Python
        download_dir = os.path.join(os.path.expanduser('~'), '.lightkurve-cache')
````
to use some global variable that is itself by default `~/.lightcurve-cache` but can be read from some configuration file (e.g. `~/.config/lightkurve/lightkurverc`, by analogy with Matplotlib).

It should also be modifiable by some function `e.g. lightcurve.set_default_download_dir(path)` but that's not as useful as setting the global option somewhere that will be read every time.

**Comment by barentsen** [comment]
Thanks for the suggestion @warrickball !

I think my preferred mechanism for this is the use of an environment variable, which feels less error-prone than having to deal with config files.  We could support an environment variable by calling ` os.environ.get("LIGHTKURVECACHE", some_default)`.

Another workaround that would work right away is to symlink `~/.lightkurve-cache`, e.g.
```
ln -s /some/remote/drive ~/.lightkurve-cache
```

**Comment by warrickball** [comment]
> Another workaround that would work right away is to symlink `~/.lightkurve-cache`, ...

Good point. That's a good enough workaround for me, so I'm happy to close this.

**Comment by barentsen** [comment]
Haha, ok! :+1:

Happy to add or merge support for an environment variable if there is more demand tho!  Please re-open this issue as needed.

**Comment by barentsen** [comment]
@warrickball PS: If you use `search_targetpixelfile` or `search_lightcurvefile` a lot, I recommend upgrading to Lightkurve v9.1, where those functions are now 10x faster!
