### ISSUE TITLE
Proper motions should be in deg not in arcsec

### ISSUE THREAD

**Issue by astrobatty** [KeplerGO/lightkurve#726]
#### Problem description
In [interact()](https://github.com/KeplerGO/lightkurve/blob/4c56f010eef0ae087cb79718cb143c7992f64123/lightkurve/interact.py) the proper motions are in arcsec, but `result.RA_ICRS` and `result.DE_ICRS` are in deg. Correcting coordinates using proper motions results in wrong RA,DEC values.

#### Solution
In line [240](https://github.com/KeplerGO/lightkurve/blob/4c56f010eef0ae087cb79718cb143c7992f64123/lightkurve/interact.py) and [241](https://github.com/KeplerGO/lightkurve/blob/4c56f010eef0ae087cb79718cb143c7992f64123/lightkurve/interact.py#L241) `to(u.arcsec).value` should be changed to `to(u.deg).value`.

**Comment by christinahedges** [comment]
Hi! Thanks for the bugfix, good spot! I've opened a PR to fix this.
