### ISSUE TITLE
Incorrect Gaia data star locations in tpf.interact_sky()

### ISSUE THREAD

**Issue by Higgins00** [KeplerGO/lightkurve#735]
#### Problem description
The Gaia positions of stars are shifted .5 in the x and y direction when running the interact_sky function in the tpf class. This is caused by the pixel column number and row numbers being not being centered on the pixel they represent.

#### Example

```python
import lightkurve as lk

search_result = lk.search_targetpixelfile('TIC239678779', mission='TESS', sector=19)#TIC number is not important
tpf = search_result.download(quality_bitmask='default')
tpf.interact_sky()
```

#### Solution:
#734 
I have provided a possible solution here.

#### Environment

-  platform (Windows):
-  lightkurve version ():
-  installation method (pip):

**Comment by barentsen** [comment]
The solution proposed by @Higgins00 over in #734 has been merged: https://github.com/KeplerGO/lightkurve/commit/f1cdedaf65638d0efeb42475d610b6f02d7097c4

Thanks again!!
