### ISSUE TITLE
 Lomb Scargle Periodogram analysis on the light curve,problems arise when the maximum frequency range of 10000 is selected

### ISSUE THREAD

**Issue by zhikai2515** [KeplerGO/lightkurve#747]
#### Problem description
hello,I'm from China,studying in a university,I like your software very much.that's right
 Lomb Scargle Periodogram analysis on the light curve,problems arise when the maximum frequency range of 10000 is selected,8336nuHZ appears in almost every power spectrum,no matter which star is chosen.

#### Example

```python
import lightkurve
pg = lc.to_periodogram(method='lombscargle', normalization='psd', maximum_frequency=10000)
# insert code here ...
```
![image](https://user-images.githubusercontent.com/56070186/83098938-77202280-a0de-11ea-8369-6abc34442468.png)
![image](https://user-images.githubusercontent.com/56070186/83099503-29a4b500-a0e0-11ea-9ca1-043dc1de8e07.png)

#### Expected behavior
I don't know why that is. I want some help

#### Environment

-  platform (e.g. Linux, OSX, Windows):linux
-  lightkurve version (e.g. 1.0b6):
-  installation method (e.g. pip, conda, source):

**Comment by jason-drury** [comment]
For future reference, an MWE (minimum working example) should be included in your bug reports. Something like this - :)

**Example**
```python
import lightkurve as lk
lc = lk.search_lightcurvefile('TIC 349793598').download_all().stitch()
pg = lc.remove_nans().to_periodogram(method='lombscargle', normalization='psd', maximum_frequency=10000)
snr = ps.flatten().plot()
```

**Answer**
This is not a bug in the code but rather a characteristic of the data and the cadence (timing) of the observations. 

The cadence of the targeted TESS observations with postage stamps (as opposed to the full-frame images) is ~2 minutes. This gives a Nyquist frequency at ~4166uHz and aliasing beyond this. 

(For more info on super Nyquist asteroseismology, I recommend these papers - https://arxiv.org/abs/1508.02717, https://arxiv.org/abs/1212.5603. Keep in mind these are not for the same observing cadences so the Nyquist frequency is different.)

This peak is the alias of the low-frequency noise. You don't see the low freq. noise here as you have flattened the power spectrum.

If you look at the documentation for flatten you are dividing by a model of the background that is typically flat beyond low frequencies.

> Estimates the Signal-To-Noise (SNR) spectrum by dividing out an estimate of the noise background.
>This method divides the power spectrum by a background estimated using a moving filter in log10 space by default. For details on the method and filter_width parameters, see Periodogram.smooth()

 You can see this with:
```python
snr, bkg = ps.flatten(return_trend=True)
bkg.plot()
```
The only time you won't see a high peak here is if the light curve has no low frequency (long period) trends.

**Comment by ojhall94** [comment]
Hi @zhikai2515, super happy to hear you're enjoying Lightkurve! @jason-drury nicely sums it up--- this is an issue with the maximum frequency being set beyond the Nyquist frequency. If you want to study the super-Nyquist regime, I would suggest you use the `nyquist_factor` keyword argument when you call `to_periodogram`. I.e. you could use:

```
pg = lc.to_periodogram(method='lombscargle', normalization='psd', nyquist_factor=2)
```

This will set the maximum frequency to 2x the nyquist (in this case ~8300 microhertz). Knowing what multiples of the Nyquist you are plotting will give your plot more context.

You can also access the Nyquist frequency of your `periodogram` object as follows:

```
nyquist = pg.nyquist
```

**Comment by barentsen** [comment]
@jason-drury @ojhall94 Thank you both so much for shining your light! :bulb: :+1: :+1: :+1:

@zhikai2515 Did this answer your question?  Please do re-open this issue if you have any other questions!
