### ISSUE TITLE
Dependency on numba leads to misadventure in some distros

### ISSUE THREAD

**Issue by texadactyl** [KeplerGO/lightkurve#752]
#### Problem description
During the installation of some Linux distributions, the libllvm10 (very new) O/S package is provided.  This has the effect of causing a Python package llvmlite to fail (needs libllvm9 or earlier).  Lightkurve is dependent on Python package numba for JIT which in turn is dependent on llvmlite.

#### Example
```
    Traceback (most recent call last):
      File "/tmp/pip-install-9x2wq1mr/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-9x2wq1mr/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-9x2wq1mr/llvmlite/ffi/build.py", line 143, in main_posix
        raise RuntimeError(msg)
    RuntimeError: Building llvmlite requires LLVM 9.0.x, got '10.0.0'. Be sure to set LLVM_CONFIG to the right executable path.
```
#### Expected behavior
Install without issues as in Lightkurve version 1.1.

#### Environment

-  platform: Raspberry Pi 4 8GB on Manjaro 64-bit ARM Linux
-  lightkurve version: https://github.com/barentsen/lightkurve/tree/timeseries-refactor
-  installation method: python-pip 3.8

#### Recommended Resolution

Amend the documentation to warn users that if this should occur, use the O/S package manager to install libllvm 9 alongside libllvm 10.  Then, the installation of lightkurve, numba, and llvmlite should proceed without further issues.

**Comment by barentsen** [comment]
Thanks for the detailed description @texadactyl!

**Comment by texadactyl** [comment]
I like very much the approach of leveraging the astropy time series.  Pay-offs will come later with initial pain.  No pain, no gain!  (-:
