### ISSUE TITLE
Feature request: add a compass rose tpf.plot() 

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#776]
[mkpy3_tpf_plot_add_compasss_rose_v1_py.txt](https://github.com/KeplerGO/lightkurve/files/4909891/mkpy3_tpf_plot_add_compasss_rose_v1_py.txt)
![mkpy3_spud](https://user-images.githubusercontent.com/17578185/87258960-a6a3a800-c45c-11ea-88fb-a8926f030441.png)

#### Feature description

I have attached a Python3 function that adds a compass rose showing the North and East directions on top of a normal tpf.plot() graph. The long arm of the compass rose points to North (increasing declination).  The short arm points to East (increasing right ascension)

#### Example

```python
import matplotlib.pyplot as plt 
import lightkurve as lk
#
tpf = lk.search_targetpixelfile(target='Kepler-138b',mission='Kepler',quarter=10).download()
#  ---> Exoplanet Kelper-138b is "KIC 7603200"
#
# Plot the 2nd frame of the TPF
ax = tpf.plot(frame=1)
#
# add a compass rose 
mkpy3_tpf_plot_add_compass_rose_v1(ax=ax, tpf=tpf)
#
plot_file = 'mkpy3_spud.png'
plt.savefig(plot_file, bbox_inches="tight")
plt.close()
print(plot_file,' <--- new PNG file written')    
```

produces the attached PNG plot showing a compass rose superimposed on top of the tpf.plot() graph.

#### Comments

The function could be implemented as a method inside the class TargetPixelFile in targetpixelfile.py

While it might be nice to have a compass rose shown in tpf.interact() and tpf.interact_sky(), I suspect that this new function would significantly slow down those two methods.

**Comment by barentsen** [comment]
Thanks very much for the suggestion and code! :+1:

I am inclined to not add a compass rose for now because we do not currently have resources to add and maintain new features.  If this feature is high in demand I would be happy to consider a PR however!

Thanks!
