### ISSUE TITLE
import problem: WARNING: leap-second auto-update failed

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#782]
#### Problem description

An import warning occurs when lightkurve  version 2.0.dev is imported using Python 3.7.3.

#### Example

```
python
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightkurve as lk
WARNING: leap-second auto-update failed due to the following exception: RuntimeError('attempted to use clear_download_cache on the path //anaconda3/lib/python3.7/site-packages/astropy/utils/iers/data/Leap_Second.dat outside the data cache directory /Users/kmighell/.astropy/cache/download/py3') [astropy.time.core]
>>> print(lk.__version__)
2.0.dev
>>> 
```
#### Expected behavior

No import warning should be issued.

#### Environment

-  platform: Mac OS X Mojave (10.14.6)
-  lightkurve version: 2.0.dev
-  installation method:
```
git clone https://github.com/KeplerGO/lightkurve.git
cd lightkurve
pip install -e .
```

**Comment by barentsen** [comment]
Thanks for opening the issue @KenMighell. :+1:

This appears to be a known issue in AstroPy for which a bugfix is about to be merged.

More details are available here: https://github.com/astropy/astropy/issues/10523

I will go ahead and close the issue here. Thanks!
