### ISSUE TITLE
IORegistryError when downloading light curves with Jupyter Notebooks

### ISSUE THREAD

**Issue by ojhall94** [KeplerGO/lightkurve#784]
#### Problem description

I've been getting an issue where I am returned an `IORegistryError` when trying to download a `KeplerLightCurve` with the latest version of Lightkurve available on the `master` branch. 

This issue *only* occurs on Jupyter Notebooks on my local machine (e.g. not with iPython or commandline python).

This error does *not* occur when downloading a `KeplerTargetPixelFile`.

This issue *does* occur when opening the cached file with the `lightkurve.open()` method.

This issue *does* occur when opening other `.fits` light curve files from MAST using the `lightkurve.open()` method.

I get a separate error when downloading a `TessLightCurve` which I've opened a separate issue for (#785)

The issue persists even when Astropy is uninstalled and is re-installed only as a lightkurve dependency.

#### Example

```python
import lightkurve
search_result = lk.search_lightcurve('Kepler 8', quarter=4)
lc = search_result.download()

---------------------------------------------------------------------------
IORegistryError                           Traceback (most recent call last)
<ipython-input-5-08b1b2f01bc3> in <module>
----> 1 lc = search_result.download()

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/utils.py in wrapper(*args, **kwargs)
    476             sys.stdout = devnull
    477             try:
--> 478                 return f(*args, **kwargs)
    479             # restore to default
    480             finally:

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/search.py in download(self, quality_bitmask, download_dir, cutout_size)
    239                                   quality_bitmask=quality_bitmask,
    240                                   download_dir=download_dir,
--> 241                                   cutout_size=cutout_size)
    242 
    243     @suppress_stdout

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/search.py in _download_one(self, table, quality_bitmask, download_dir, cutout_size)
    180             log.debug("Finished downloading.")
    181             # open() will determine filetype and return
--> 182             return _open_downloaded_file(path, quality_bitmask=quality_bitmask)
    183 
    184     @suppress_stdout

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/search.py in _open_downloaded_file(path, **kwargs)
    998     download having been interrupted."""
    999     try:
-> 1000         return read(path, **kwargs)
   1001     except ValueError:
   1002         raise SearchError("Failed to open the downloaded file ({}). "

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/io.py in read(path_or_url, **kwargs)
     81     # if the filetype is recognized, instantiate a class of that name
     82     if filetype is not None:
---> 83         return getattr(__import__('lightkurve'), filetype)(path_or_url, **kwargs)
     84     else:
     85         # if these keywords don't exist, raise `ValueError`

/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve/lightcurve.py in read(cls, *args, **kwargs)
   2036         if kwargs.get("format") is None:
   2037             kwargs['format'] = "kepler"
-> 2038         return super().read(*args, **kwargs)
   2039 
   2040     def to_fits(self, path=None, overwrite=False, flux_column_name='FLUX',

/usr/local/lib/python3.7/site-packages/astropy/timeseries/sampled.py in read(self, filename, time_column, time_format, time_scale, format, *args, **kwargs)
    364 
    365             # First we try the readers defined for the BinnedTimeSeries class
--> 366             return super().read(filename, format=format, *args, **kwargs)
    367 
    368         except TypeError:

/usr/local/lib/python3.7/site-packages/astropy/table/connect.py in __call__(self, *args, **kwargs)
     50     def __call__(self, *args, **kwargs):
     51         cls = self._cls
---> 52         out = registry.read(cls, *args, **kwargs)
     53 
     54         # For some readers (e.g., ascii.ecsv), the returned `out` class is not

/usr/local/lib/python3.7/site-packages/astropy/io/registry.py in read(cls, format, *args, **kwargs)
    520                 'read', cls, path, fileobj, args, kwargs)
    521 
--> 522         reader = get_reader(format, cls)
    523         data = reader(*args, **kwargs)
    524 

/usr/local/lib/python3.7/site-packages/astropy/io/registry.py in get_reader(data_format, data_class)
    453             "No reader defined for format '{}' and class '{}'.\n\nThe "
    454             "available formats are:\n\n{}".format(
--> 455                 data_format, data_class.__name__, format_table_str))
    456 
    457 

IORegistryError: No reader defined for format 'kepler' and class 'KeplerLightCurve'.

The available formats are:

   Format   Read Write Auto-identify
----------- ---- ----- -------------
kepler.fits  Yes    No            No
  tess.fits  Yes    No            No

```

#### Expected behavior

The expected behaviour is for the downloaded .fits file data to be stored as a `KeplerLightCurve` object inheriting from an `Astropy` `Timeseries` object. There seems to be an issue when using the `Astropy` functionality to identify the mission parameters.

#### Environment

-  Platform: macOS Mojave Version 10.14.6
-  Lightkurve version 2.0.dev. -- master branch commit a35460f
-  Installed from a cloned repository using `python3 install setup.py`
- Python version 3.7.4

**Comment by ojhall94** [comment]
A piece in the puzzle here: I tried installing through pip direct from GitHub, using:

```bash
pip3 install git+https://github.com/keplergo/lightkurve.git
```

After doing this, I can't import Lightkurve in Jupyter Notebooks at all. I get the following error:

```python3
import lightkurve as lk
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-23246d7cf2d6> in <module>
----> 1 import lightkurve as lk

/usr/local/lib/python3.7/site-packages/lightkurve/__init__.py in <module>
     24 from .lightcurve import *
     25 from .lightcurvefile import *
---> 26 from .correctors import *
     27 from .targetpixelfile import *
     28 from .utils import *

/usr/local/lib/python3.7/site-packages/lightkurve/correctors/__init__.py in <module>
     15 from .designmatrix import *
     16 
---> 17 from .pldcorrector import *
     18 from .sffcorrector import *
     19 from .cbvcorrector import *

/usr/local/lib/python3.7/site-packages/lightkurve/correctors/pldcorrector.py in <module>
     24 from .designmatrix import create_spline_matrix, create_sparse_spline_matrix
     25 from .. import MPLSTYLE
---> 26 from ..targetpixelfile import KeplerTargetPixelFile
     27 from ..utils import LightkurveDeprecationWarning
     28 

/usr/local/lib/python3.7/site-packages/lightkurve/targetpixelfile.py in <module>
     36                    validate_method, centroid_quadratic, \
     37                    _query_solar_system_objects
---> 38 from .io import detect_filetype
     39 
     40 

ModuleNotFoundError: No module named 'lightkurve.io'
```

Should I gut Jupyter out of my system and retry with a fresh install?

**Comment by barentsen** [comment]
I'm surprised you are seeing a different behavior inside notebooks.  This suggests that notebooks may be importing Lightkurve from a different location than your terminal.

Could you post the output of the following:
```
import lightkurve as lk
print(lk.__path__)
```
...both for a notebook and a traditional python console?  This tell us the path from where Lightkurve is imported.

**Comment by ojhall94** [comment]
I'm having a truly bizarre time.

I checked the path in commandline python3 and ipython3 terminals, and then created a new Jupyter Notebook instance and checked the path there. In all three cases the path was the same, and the error described above did not appear. The path in that instance is the local repository;

```
import lightkurve as lk
print(lk.__path__)
['/Users/Oliver/PhD/Hacks & Packages/lightkurve/lightkurve']
```

I then went back to the Jupyter Notebook that I used to obtain the error messages for this Issue, where it didn't work and I obtained the same error message. The path I get there is:

```
import lightkurve as lk
print(lk.__path__)
['/usr/local/lib/python3.7/site-packages/lightkurve-2.0.dev0-py3.7.egg/lightkurve']
```

Which probably explains the issue. But I'm confused why two separate Jupyter Notebooks are pulling lightkurve from different places.

**Comment by barentsen** [comment]
The two separate notebook servers will reflect the environment at the time they were started. Is there any chance that there may have been changes to $PATH, $PYTHONPATH, or similar between starting the first notebook server and the second?

**Comment by barentsen** [comment]
(One way to check could be `print(sys.path)` in each.)

**Comment by ojhall94** [comment]
Hmm, Ive been consistently restarting the notebooks before testing, or is that not what you mean? I'll check the sys.path in a sec and report back.

**Comment by barentsen** [comment]
I suspect that restarting the notebook *kernel* is not quite the same as restarting the notebook *server*. I believe only the latter will be impacted by different environment variables.

**Comment by ojhall94** [comment]
I've figured this part of it out I think. Everything worked fine when I've been testing because I happened to be opening the sessions from my local Lightkurve repository, so it's been importing the local package directly. When I import Lightkurve through Python's installation library we get the issues described above.

I've installed Lightkurve on my machine direct from the local repository, so it seems like something is going wrong in the installation process.

**Comment by barentsen** [comment]
Thanks for the updates @ojhall94!

Based on this new information, and the error message above, it looks like the new `lightkurve.io` sub-package isn't being installed on your system.  I believe https://github.com/KeplerGO/lightkurve/pull/788 will fix this!

(PS: Can you let me know the exact command you used to install Lightkurve on your machine from the local repository?  I ask because I did not encounter this bug using `python setup.py develop`, I wonder if you used e.g. `python setup.py install` instead, which may explain the different behavior.)

**Comment by ojhall94** [comment]
#788 fixed this problem! Glad we can close the book on this one, thanks @barentsen!

**Comment by barentsen** [comment]
Thanks @ojhall94! Good thing we caught this for sure!
