### ISSUE TITLE
Prototype: Adding support for reading CBV files

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#806]
Over in #672, work is well underway to add a `CBVCorrector` which would use Kepler/TESS Cotrending Basis Vector data to remove systematics from light curves.

A recent change in Lightkurve v2.x is the use of the `astropy.timeseries.TimeSeries` class as a container to hold light curve data. For consistency, it would be good to also use `TimeSeries` objects to store Cotrending Basis Vectors.

I am opening this issue to share a rough prototype of what this implementation could look like.

## Prototype

```python
from astropy.io import fits
from astropy.time import Time
from astropy.table import Table
from astropy.timeseries import TimeSeries

from lightkurve.correctors import DesignMatrix


class CotrendingBasisVectors(TimeSeries):
    """Container class for Kepler/TESS Cotrending Basis Vectors (CBVs).
    
    This is a special case of `TimeSeries` in which columns named `VECTOR_X`
    are used to denote cotrending basis vectors.  X is a positive integer
    starting from 1, consistent with the official Kepler/TESS data products.
    """
    def to_designmatrix(self, vectors=None, name="cbv"):
        """Returns a `DesignMatrix` containing the CBVs."""
        if vectors is None:
            vectors = list(range(1, cbv.meta['TFIELDS']-2))
        return DesignMatrix(self[[f"VECTOR_{idx}" for idx in vectors]].as_array(),
                            name=name)
        
    def plot(self):
        """TODO: A nice plotting function for CBVS."""
        pass
        

def read_cbv_file(filename, ext="CBV.single-scale.1.1"):
    """FITS file reader for official `CotrendingBasisVectors` files."""
    hdulist = fits.open(filename)

    # Read the columns and meta data
    tbl = Table.read(hdulist[ext], format="fits")
    tbl.meta.update(hdulist[0].header)
    tbl.meta.update(hdulist[ext].header)

    # TimeSeries-based objects require a dedicated time column
    t = Time(tbl['TIME'].data, format='btjd')
    tbl.remove_column('TIME')
    return CotrendingBasisVectors(time=t, data=tbl)
```

## Example use:

```python
# Reading a CBV file
url = "https://archive.stsci.edu/missions/tess/ffi/s0017/2019/279/1-1/tess2019279210107-s0017-1-1-0161-s_cbv.fits"
cbv = read_cbv_file(url)

# Accessing meta data
print(cbv.meta['TELESCOP'])
print(cbv.meta['CAMERA'])

# Accessing a single vector
cbv['VECTOR_1'].data

# Convert the CBVs into a `DesignMatrix` object
dm = cbv.to_designmatrix()
```

**Comment by jcsmithhere** [comment]
OK, it makes sense to me that CotrendingBasisVector be a astropy.timeseries.TimeSeries class. I'll look into this. 

Regarding the issue of having two pull requests for the CBV Corrector code: one for retrieving CBVs and another for CBVCorrector. All the code is in a single cbvcorrector module but the CortrendingBasisVectors classes can be used separately from the cbvCorrector class. So, for ease fo merging and procedural reasons I'm fine having two pull requests. However, I think we should have both PRs in LightKurve before we release the code to the public.

**Comment by barentsen** [comment]
@jcsmithhere I urgently need to write up a document that explains these changes in Lightkurve v2.x, but one of the consequences of adopting the `TimeSeries` API is that data is now read in via the `LightCurve.read()` method.

For example, reading in a TESS light curve file is done as follows:
```python
lc = LightCurve.read(filename, format='tess', flux_column="sap_flux", quality_bitmask=123)
```
All the keyword arguments are optional, but one of them (`flux_column`) determines which column should be used to populate `flux`.

Behind the scenes, calling `LightCurve.read` with `format='tess'` calls the `read_tess_lightcurve()` helper function defined in the `lightkurve.io.tess` module:

https://github.com/KeplerGO/lightkurve/blob/dca8de921b7f111c1d38c7b2aba1724e89a565a1/lightkurve/io/tess.py#L8-L33

The `lightkurve.io` sub-package also contains readers for other formats, which allows the `LightCurve` object to support other projects in a more generic way.

**Comment by jcsmithhere** [comment]
Ah, I see! But I don't see a way with `search_lightcurve` to specify which `flux_column` should be used to populate `flux`. In my testing I'm using `search_lightcurve` to get sample targets. As of now, it looks like I have to manually do: 

```
lc['flux'] = lc['sap_flux']
lc['flux_err'] = lc['sap_flux_err']
```

But... Look like you just merged a change to do just this! Never-mind... : )

**Comment by barentsen** [comment]
Yep, you can now do `download(flux_column='sap_flux')` to make this easier!

**Comment by jcsmithhere** [comment]
What I'd like to do here is just place all the CBVCorrector code in a giant comment block. I hope that is an acceptable way to split the pull request into two parts.

**Comment by barentsen** [comment]
I recommend creating a branch from the original PR and use it to open new PRs, so that you keep existing PR for reference, but whatever will work is fine of course!

**Comment by jcsmithhere** [comment]
Yes, I'll create a new PR just for the CBV code. Then a second PR with the CBVCorrector class. 

The original WIP PR #672 will be closed.

**Comment by jcsmithhere** [comment]
Hey @barentsen, I'm almost finished moving my CotrendingBasisVectors class to `astropy.timeseries.TimeSeries` but I'm running into a problem. I can't return a subset of times in the `CBV` object, i.e. cbvs[1:3]. This works for a `lightcurve` object but I get an error when trying to do the same for my `CBV` object. Below is an example of it working for a `lightcurve` object then erring for a `CBV` object. I've tried tracing the code and the error says:

> TypeError: __init__() got an unexpected keyword argument 'masked'

but the `CBV` object has the attribute 'masked' so I can't figure out why it's complaining. Have you ever seen this error before?

Here it it working for a lightcurve object:

```
In[6]: sample_lc
Out[6]: 
<TessLightCurve length=5>
 time    flux  flux_err cadenceno
                                 
object float64 float64    int64  
------ ------- -------- ---------
   1.0     1.0      0.1         1
   2.0     2.0      0.1         2
   3.0     3.0      0.1         3
   4.0     4.0      0.1         4
   6.0     6.0      0.1         6

In[7]: sample_lc[1:3]
Out[7]: 
<TessLightCurve length=2>
 time    flux  flux_err cadenceno
                                 
object float64 float64    int64  
------ ------- -------- ---------
   2.0     2.0      0.1         2
   3.0     3.0      0.1         3
```
But here it is **not** working for a cbv object and the trace:

```
In[8]: cbvs
Out[8]: 
<CotrendingBasisVectors length=5>
 time  CADENCENO  GAP  VECTOR_1
object   int64    bool float64 
------ --------- ----- --------
   1.1         1 False      1.0
   1.2         2  True      2.0
   1.3         3 False      3.0
   1.5         5 False      5.0
   1.6         6 False      6.0

In[9]: cbvs[1:3]
Traceback (most recent call last):
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-e135a251ec91>", line 1, in <module>
    cbvs[1:3]
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/timeseries/sampled.py", line 256, in __getitem__
    return super().__getitem__(item)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/table.py", line 1626, in __getitem__
    return self._new_from_slice(item)
  File "/Users/bohr/opt/anaconda3/envs/lightkurve-env/lib/python3.8/site-packages/astropy/table/table.py", line 1138, in _new_from_slice
    table = self.__class__(masked=self.masked)
TypeError: __init__() got an unexpected keyword argument 'masked'

```

**Comment by barentsen** [comment]
@jcsmithhere I am unable to reproduce this when `CotrendingBasisVectors` is defined using the code snippet posted above.

![Screenshot from 2020-08-28 10-04-18](https://user-images.githubusercontent.com/817669/91593928-df68e500-e915-11ea-9137-18405a52b7e2.png)

I am using the master branch of AstroPy (updated 2-3 days ago) because we encountered a number of minor issues with both `Table` and `TimeSeries` which have only recently been resolved.  It may be that this error is one of those issues.  Hence, the first thing I would try is to `pip install astropy==4.1rc1` or install astropy from the current GitHub master branch.

(Side note: Lightkurve v2.0 will indeed have to have a dependency on AstroPy v4.1.0, which should be released in the very near future.  The TimeSeries functionality is very new...)

**Comment by jcsmithhere** [comment]
Installing astropy 4.1rc1 did not resolve the issue. 

I have my own `__init__` method for `CotrendingBasisVectors` and that is the problem. If I use the default `__init__` in `TimeSeries` then it works. But `LightCurve` also has its own `__init__`, so something must be different between how you use it versus how I do. 

If I have my own `__init__` but all it does is call: 

`super().__init__(data=dataTbl, time=cbvTime)`

then I still get the problem! So there must be something extra in the `LightCurve` `__init__` that I need, or some other extra method in `LightCurve`. Very curious to me!

**Comment by jcsmithhere** [comment]
OK, I found it. I needed the **kwargs. Hopefully I'm now back to work.

```
class CotrendingBasisVectors(TimeSeries):
    def __init__(self, data=None, time=None, **kwargs):
        
...


        super().__init__(data=data, time=time, **kwargs)

...
```

**Comment by jcsmithhere** [comment]
Doh! Looks like I have to put all object attributes in the cbvs.meta dict. Otherwise, operations such as cbvs[0:2] will not preserve the attributes. 
OK, fortunately, one can arbitrarily add fields to the cbvs.meta dict. I have to carry all my extra attributes in this.

**Comment by barentsen** [comment]
@jcsmithhere Yes, that's correct!

**Comment by jcsmithhere** [comment]
@barentsen, I have a syntax question for you. I see in the LightCurve class you create a `time` property with:
```

    @property
    def time(self):
        """The time values."""
        return self['time']
```

This requires the user to still dive into `lc.time.value` to get the numpy array time values. What I set up for my CBV class is:

```
    @property
    def time(self):
        """The time values."""
        return self['time'].value
```

One only needs to call `lc.time` to get the time values. This makes access to the actual values much cleaner in the user's code. If one wants the meta data then they can always get to it with `lc['time']`.

What do you think? Of course, whatever we decide I will pattern my code after the LightCurve convention.

**Comment by barentsen** [comment]
@jcsmithhere Excellent question!

The AstroPy convention is that the `time` column in a `TimeSeries` object is a `Time` object, and I think we should consistently adopt that convention.  For consistency, `TargetPixelFile.time` has been modified in Lightkurve v2.x to return a `Time` object as well.

It is annoying to have to add `.value` every time to access the time values as a numpy array, but this appears to be the price we pay to ensure that the time values always have a time scale and format associated with them.  (Likewise, all other columns are now `Quantity` objects with units associated to them.)

Long-term, the `Time` objects will hopefully improve such that they behave like a numpy array more consistently (some efforts to do this are underway over on the AstroPy issue tracker).  For now, my recommendation is that any `time` property or column ought to return a `Time` object for consistency.  Does that sound reasonable?

**Comment by jcsmithhere** [comment]
I view the `time` property and other like properties as a convenient short-hand to quickly get to the values with as few keystrokes as possible, but I see the logic in returning everything as a `Time` or `Quantity` object. I fully support consistent conventions so if the convention is to always return a `Time` or `Quantity` object then that's what I'll do. 

BTW, the CBV code is very near ready for a PR. Just polishing the last things up (and this was one of the rough spots!).

**Comment by barentsen** [comment]
I hear you! I wish we'd never have to type `time.value`, and hopefully this will no longer be needed in the future, but for now it would be confusing if `time` isn't always a `Time`.

I have various things scheduled in the next 24 hours, but I have time available to review PRs on Wednesday afternoon and across Thursday! :+1:

**Comment by barentsen** [comment]
Closing this issue as it has been superseded by #826!
