### ISSUE TITLE
query_solar_system_objects documentation / api - cadence_mask

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#809]
#### Problem description
The issue concerns the documentation for `query_solar_system_objects()` and possibly some API tweaks.

https://docs.lightkurve.org/api/lightkurve.lightcurve.LightCurve.html#lightkurve.lightcurve.LightCurve.query_solar_system_objects

It states that `cadence_mask` must be str or bool.

But `cadence_mask` could also be a Boolean `numpy.ndarray`, flagging the cadences to be searched.

The same consideration is also applicable to `TargetPixelFile`
1. If the intention is to support arbitrary `cadence_mask`, the documentation needs to be updated.
2. If (1) is true, we might want to consider to support any array-like structure rather than `numpy.ndarray`, to be more in parity with the rest of the API.

#### Example

```python
import lightkurve


# For a given lightkurve, check if there are solar system objects
# in the given time frame, e.g., around a possible transit.
# The codes work on lightkurve v1.11.
df_sso = lc.query_solar_system_objects(cadence_mask=np.logical_and(lc.time >= 2014.1, lc.time <= 2014.9))

```

#### Environment

-  lightkurve version: 1.11

**Comment by barentsen** [comment]
@orionlee Thanks for opening an issue! :+1:

I completely agree with you:
1. The documentation needs to be updated to clarify that `cadence_mask` can indeed be an arbitrary mask (i.e. a boolean array).
2. I'm in favor of supporting any array-like object.  If e.g. a `list` of booleans isn't already supported, we could likely support this by adding `np.atleast_1d(cadence_mask)` somewhere in the implementation to turn a list-like object into a numpy array.
3. It would be good to add an `Examples` section to the docstring to further clarify the use of this function by showing example function calls.

@orionlee Would you be interested in creating a PR to make these changes?  I'd make it a priority to review and merge such PR!

**Comment by orionlee** [comment]
@barentsen I just submitted a minimal PR before noticing your reply. Will take a look at supporting general array-like structure.

**Comment by barentsen** [comment]
@orionlee Awesome!  Ping me when you feel you are done, and I'll review/merge!
