### ISSUE TITLE
`from_archive` doesn't work for C15

### ISSUE THREAD

**Issue by christinahedges** [KeplerGO/lightkurve#81]
![screen shot 2018-03-14 at 12 48 44 pm](https://user-images.githubusercontent.com/14965634/37427251-0e2f803c-2786-11e8-8a63-8f390238d3b5.png)

But it is available at MAST:

<img width="795" alt="screen shot 2018-03-14 at 12 49 01 pm" src="https://user-images.githubusercontent.com/14965634/37427255-171c8884-2786-11e8-9731-3636eaf58f16.png">

**Comment by barentsen** [comment]
I pinged @scfleming about it.  I believe it is simply a matter of the MAST API having to sync up with this brand new data release.

**Comment by scfleming** [comment]
Correct, API will come once data are in Portal.  I usually start the ball rolling on that, it gets done after Randy/Faith get stuff online, and with a different group.  Should be availble via Portal/API early next week.  The Portal goes through weekly patches, so assuming I get C15 ready for Portal update by end of the week (likely) then it should be ready in next week's Portal update.

**Comment by barentsen** [comment]
Many thanks for the clarification @scfleming.  For the next few days users will have to pass the URL of a C15 TPF or LC file directly, which I think is fine!  Closing...
