### ISSUE TITLE
Lightcurve.query_solar_system_objects() documentation - location

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#810]
#### Problem description

In Lightcurve.query_solar_system_objects(), there is an optional `location` argument. It'd be better if the documentation states the default is `Lightcurve.mission`

The documentation was missing in `v1.11`. Here I am referring to what's in the latest `master` v2.0a2.

-  lightkurve version (e.g. 1.0b6): latest `master`, `2.0a2`

**Comment by barentsen** [comment]
Also agreed!  The docstring fails to explain the default behavior of `location`.  This needs to be improved!  Would you be interested in opening a PR to fix this?
