### ISSUE TITLE
Make TargetPixelFile.interact() more reponsive

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#817]
#### Problem description

As stated in the doc, `TargetPixelFile.interact()` could be quite slow / sluggish.

One possibility to make it effectively faster / more responsive is to let user specify a time / cadence range to plot, rather than plotting for the entire file.

**Proposal 1:** Add an optional `cadence_mask` argument to `interact()`, e.g., 

```python
  # handle only 5 days of plot, rather than the entire 20+ days of data
  tpf.interact(cadence_mask=(tpf.time >= 2010) & (tpf.time < 2015))
```

**Proposal 2** Provide a general filter on `TargetPixelFile`, e.g. add a `select(cadence_mask)` method to `TargetPixelFile`

```python
   # a new TPF object with only 5 days of data
   tpf_subset = tpf.select((tpf.time >= 2010) & (tpf.time < 2015))
   tpf_subset.interact()
```

#### Environment

-  lightkurve version: v1.11

**Comment by barentsen** [comment]
I believe we already support this using the following syntax:

```python
tpf[(tpf.time.value >= 2010) & (tpf.time.value < 2015)].interact()
```

This also works for a `LightCurve` object, e.g. you can do `lc[lc.time.value > 2000].plot()`.

However the docstring of `interact()` could certainly be improved by advertising this syntax as a way to speed up the tool!

**Comment by orionlee** [comment]
Ah, so it's a new feature for v2.0 . 
I recalled I wanted to do something like that for `LightCurve` in the past too.

**Comment by barentsen** [comment]
I believe this slicing functionality has been there since Lightkurve v1.0 (or thereabouts), though we haven't advertised it as much as we should!

**Comment by orionlee** [comment]
You're correct - I had a typo in my trial script for v1 lightkurve, mistakenly believing it's not there.

It'd be good to have the feature documented.

**Comment by barentsen** [comment]
Yep.  We'll want to do this using a combination of having more tutorials and having more "Examples" sections in docstrings.

I will go ahead and close this issue, but any and all new issues or PRs related to improving these matters are very welcome!
