### ISSUE TITLE
Is a significant difference of the DesignMatrix of the PLD exist between the latest lightkurve and the version 1.10.0 ?

### ISSUE THREAD

**Issue by exo-hunter** [KeplerGO/lightkurve#822]
Hi everyone,

I found a significant difference in building the DesignMatrix of the PLD between the latest pldcorrector.py and the old one in lightkurve 1.10.0.   During creating the DesignMatrix of each PLD orde,  the for loop seems to start from the first order of PLD in the latest version while that from the second order in the old version.  Is my understanding right?  Should we correct the first index of the for loop from 2 to 1 in lightkurve 1.10.0?  Please see the following parts for the details. 

I prefer the PLD implementation in lightkurve 1.10.0 because of the GPs model for the stellar variability. Thanks.

######################################## The Latest version.
        # Background-subtracted, flux-normalized pixel time series
        regressors = self.tpf.flux[:, pld_aperture_mask].reshape(len(self.tpf.flux), -1)
        regressors = regressors - bkg.flux.reshape(-1,1) * pld_aperture_mask.sum() * u.pixel
        regressors = np.array([r[np.isfinite(r)] for r in regressors])
        regressors = np.array([r / f for r,f in zip(regressors, self.lc.flux.value)])

        # Use the DesignMatrix infrastructure to apply PCA to the regressors.
        with warnings.catch_warnings():
            warnings.filterwarnings('ignore', message='.*low rank.*')
            regressors_dm = DesignMatrix(regressors)
        if isinstance(pca_components, (tuple, list)):
            ncomp = pca_components[0]
        else:
            ncomp = pca_components
        if ncomp > 0:
            regressors_dm = regressors_dm.pca(ncomp)
        regressors_pld = regressors_dm.values

        # Create a DesignMatrix for each PLD order
        all_pld = []
        **for order in range(1, pld_order+1):
            reg_n = np.product(list(multichoose(regressors_pld.T, order)), axis=1).T**
            with warnings.catch_warnings():
                warnings.filterwarnings('ignore', message='.*low rank.*')
                pld_n = DesignMatrix(reg_n)
            # Apply PCA. Check if pca_components has an entry for each order,
            # otherwise use pca_components for PCA of higher order matrices.
#################################

################################# The old version
        # first order PLD design matrix
        pld_flux = flux_crop[:, aperture_crop]
        f1 = np.reshape(pld_flux, (len(pld_flux), -1))
        X1 = f1 / np.nansum(pld_flux, axis=-1)[:, None]
        # No NaN pixels
        X1 = X1[:, np.isfinite(X1).all(axis=0)]

        # higher order PLD design matrices
        **X_sections = [np.ones((len(flux_crop), 1)), X1]
        for i in range(2, pld_order+1):
            f2 = np.product(list(multichoose(X1.T, pld_order)), axis=1).T**
            try:
                # We use an optional dependency for very fast PCA (fbpca).
                # If the import fails we will fall back on using the slower `np.linalg.svd`
                from fbpca import pca
                components, _, _ = pca(f2, n_pca_terms)
            except ImportError:
                log.error("PLD uses the `fbpca` package. You can pip install "
                          "with `pip install fbpca`. Using `np.linalg.svd` "
                          "instead.")
                components, _, _ = np.linalg.svd(f2)
            X_n = components[:, :n_pca_terms]
            X_sections.append(X_n)

        # Create the design matrix X by stacking X1 and higher order components, and
        # adding a column vector of 1s for numerical stability (see Luger et al.).
        # X has shape (n_components_first + n_components_higher_order + 1, n_cadences)
        X = np.concatenate(X_sections, axis=1)

##################################
Best wishes,
Sun

**Comment by barentsen** [comment]
@exo-hunter Thank you for opening an issue!

There have indeed been significant changes to `PLDCorrector` as part of PR #746.

The biggest change is the removal of Gaussian Processes (GPs) in favor of using splines to fit long-term trends.  We decided to start using splines because they are much faster and easier to fit.  We think splines should work equally well, but perhaps the default parameters have not been set correctly yet.  **Would you be willing to post example code for a target that worked much better with GPs than splines?**  That would help us figure out how to do better!

Changing the first index in the pld_order for loop should not make a different. In the past, the first PLD order was created separately, above the for loop, on lines 200-205.  We simplified the code to make these lines part of the for loop, but it should not make a big difference:

https://github.com/KeplerGO/lightkurve/blob/6d602ebf227f2f7398f0b3268c74e1272dd259ef/lightkurve/correctors/pldcorrector.py#L200-L222

**Comment by exo-hunter** [comment]
@barentsen  Thank you for your quick reply.  

You are right. The first-order regressor of PLD  was built separately in the old version.  But I guess that "f2 = np.product(list(multichoose(X1.T, pld_order)), axis=1).T" should be replaced with "f2 = np.product(list(multichoose(X1.T, i)), axis=1).T".   When someone want to employ 3 order PLD instand of the default order (e.g. default pld_order=2) in the old version , the former expression will make a mistake. 

I am a big fan of GPs.  And the nonparametric form and flexibility of GPs are actually suitable for unknown stellar variability.  The celerite Matern-3/2 kernel was implemented in lightkurve 1.10.0, which could be optimized with better hyperparameter estimation by using non-linear optimization algorithms (like L-BFGS-B of scipy.optimize).

Later, I will try to compare the PLD correction results in some specific cases. 

Thanks,
Sun

**Comment by barentsen** [comment]
> in the old version , the former expression will make a mistake.

You're right, it looks like the old version contained a bug when using pld_order > 2!

> I am a big fan of GPs.

So are we, but we struggled to make the GPs fast and robust enough.  We are hoping that splines can offer the same flexibility at a fraction of the speed, albeit without the uncertainty propagation with makes GPs particularly nice.

I'd be very interested to look at specific examples where GPs work and splines don't!

**Comment by barentsen** [comment]
@exo-hunter I'm going to close this issue because there hasn't been any activity for 2 weeks, but feel free to re-open if you come across a good example that we can debug/investigate to make PLDCorrector work better.  I'd be very interested in that any time!  :+1:
