### ISSUE TITLE
PLDCorrector: priors restrict background fitting

### ISSUE THREAD

**Issue by nksaunders** [KeplerGO/lightkurve#824]
#### Problem description

There seems to be an issue with how the `background_model` design matrix is being generated. With the current default priors on `background_model` (line [#231-232 of pldcorrector.py](https://github.com/KeplerGO/lightkurve/blob/728a37f7bead7d87441b31941a8bc64a39d56c9f/lightkurve/correctors/pldcorrector.py#L231-L232)), the background model is flat for seemingly all targets, forcing the `pixel_series` to pick up the background noise. This has detrimental effects on its ability to fully capture the systematic trends.

#### Example

With current priors:
![download](https://user-images.githubusercontent.com/17130840/91925749-60efa880-ec71-11ea-928e-71a1f4ec786f.png)

However, removing these priors causes an unwanted tradeoff between `background_model` and `pixel_series`. 

Without current priors:

![download-1](https://user-images.githubusercontent.com/17130840/91925767-6e0c9780-ec71-11ea-9c1a-ceebd7c7e19a.png)

#### Expected behavior

`background_model` and `pixel_series` should capture distinct sources of noise. This appears to work more consistently for *K2*, where the dominant source of noise is the `pixel_series`, but for TESS, the tradeoff is problematic.

This issue, combined with #822, indicate that there are remaining necessary changes to our `PLDCorrector`.

#### Possible solution
If parameterized carefully, the pixel series, in combination with a spline (or GP) should be able to capture all sources of noise (as demonstrated by EVEREST and our previous implementation). My worry is that by introducing a third design matrix, we've overcomplicated the problem. Evidence of this can be seen in the above plots, showing that the restricted, flat background actually returns a higher precision corrected light curve.

I'll experiment with simplifying our solution, but will not make this a huge priority, as the pixel series tends to do a decent job even without much contribution from the background model.

#### Environment

-  platform: **OSX**
-  lightkurve version: **`2.0a2.dev`**
-  installation method: **source**

**Comment by barentsen** [comment]
First reaction: we may want to have a close look at the pixel data near e.g. BTJD 1379, to understand exactly what the data looks like in those problematic cadences.

**Comment by barentsen** [comment]
@nksaunders It looks to me like the prior is too strict in the first example, and too loose in the second example.  Is the solution simply to have a less-strict prior?  Are we confident that our initialization of the prior is correct, cf. line 230:

https://github.com/KeplerGO/lightkurve/blob/cf5794f3f83bdddcd49d0e4c9456bc273b4f45b4/lightkurve/correctors/pldcorrector.py#L227-L232

**Comment by barentsen** [comment]
I propose closing this issue and use #847 to discuss the topic.
