### ISSUE TITLE
Add support for filtering TESS products on exposure length

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#831]
### Problem description

Currently, all TESS SPOC data products returned by `search_lightcurve()` and `search_targetpixelfile()` are 2-minute cadence products, because that is the only observing mode for which SPOC TPFs and LCs were archived during the prime mission.

This will change very soon! The extended mission includes a new, "fast", 20-second cadence mode. In addition, the SPOC and others will likely start releasing FFI-based TPF and LC products for both the prime (30-minute cadence) and extended mission (10-minute cadence) as HLSPs in the near future.

The search functions currently include a `cadence='long'` and `cadence='short'` option to filter Kepler and K2 data products by exposure length, but this argument is currently ignored for TESS data products.

### Solution

I propose to add support for filtering TESS data products as follows:
* When a numerical value is passed to `cadence`, it will be used to filter the `t_exptime` value in the MAST Portal API.
* When a string is passed to `cadence`, it will be parsed as follows:
  * `cadence='fast'` will map to `t_exptime < 60`
  * `cadence='short'` will map to `60 <= t_exptime < 300`
  * `cadence='long'` or `cadence='ffi'` will map to `t_exptime >= 300`.

Comments or feedback on this proposal are welcome!

### Caveats

* The exact integration time for TESS is slightly shorter than 60, 120, 600, or 1800 seconds, however these are the values we should use because [the MAST portal docs](https://mast.stsci.edu/api/v0/_c_a_o_mfields.html) defines `t_exptime` as the *total exposure length* rather than the *exact integration time*.  This is good because users will want to filter on exposure length, not the exact integration time!
* For Kepler and TESS FFI images, I believe the MAST portal accidentally populated `t_exptime` with *integration time* (e.g. `t_exptime=1425.599379` for FFI images), even though *exposure length* is consistently used for TPF and LC products (e.g. `t_exptime=1800` for Kepler long cadence products).

**Comment by orionlee** [comment]
1. Should such change be made in v2.0 branch or v1.11.x ? The data products from TESS extended mission should be in soon, and this change might be needed sooner than v2.0 time frame.
2. It might be clearer to users if we list out the data products that could return depending on the `cadence`.
3. The current default value for `cadence` is `long`, which will not make sense for TESS.

---
[*] A sample table on the impact of `cadence` on the data products returned for TESS

|   | `fast` | `short` | `long` |
| --- | --- | --- | --- |
|  TESS | none | 2-minute | maybe 30-minute |
|  TESS extended | 20-second | 2-minute | maybe 10-minute |

**Comment by barentsen** [comment]
Thanks @orionlee! 

> 1. Should such changes be made in v2.0 branch or v1.11.x branch?

Excellent question.  We made a lot of changes to the `search` module in v2, so it would be a fair bit of extra work to also implement this new feature in v1.  I'm tempted to add this only to v2 for now because the data products will still be accessible for v1 users, they'll only miss out on the optional cadence filter.  I'm planning a first beta release of v2 this month, so unless there is significant user request to have this feature in v1, I'd just add it to v2.

> 2. It might be clearer to users if we list out the data products that could return depending on the cadence.

Yes!  Thank you for the table!  We can also add Kepler as follows:

|   | `fast` | `short` | `long` |
| --- | --- | --- | --- |
|  Kepler & K2 | none | 1-minute | 30-minute |
|  TESS | none | 2-minute | 30-minute |
|  TESS extended | 20-second | 2-minute | 10-minute |

> 3. The current default value for cadence is long, which will not make sense for TESS.

True!  This might need some more thinking, but I'd be tempted to change the default to `cadence=None` (i.e. no filter) so that all data products show up.  This does have the side effect that old code which relied on `cadence='long'` being the default for Kepler may break, but then v2.x is our chance to revise the API and make such changes.

**Comment by orionlee** [comment]
It looks like even without the change, users can still do their own filtering afterwards:

```python
    # filter to get 2-minute data products only
    SearchResult(search_res.table[search_res.table['t_exptime'] == 120])
```

A small catch is: are supposed to access `search_res.table`? The documentation only indicates `table` is a parameter in creating `SearchResult`:
  https://docs.lightkurve.org/api/lightkurve.search.SearchResult.html

**Comment by barentsen** [comment]
@orionlee Yes, I'm happy for people to access the original MAST records via the `.table` attribute.  You're right, it's not documented! 😨
