### ISSUE TITLE
TESS LightCurve product Search: some results possibly excluded?!

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#837]
#### Problem description
For TIC 219780464, lightkurve's search returned the 3 LC products I accidentally discovered there is an additional one listed in MAST portal, one that spans from sector 14 to 26.

While the additional one is not the usual per-sector LC, it should probably be surfaced in lightkurve's search result.

Another example is TIC 230016502. I believe they are both associated with the same GI program that produced lightcurves spanning multiple sectors.

#### Example

```python
import lightkurve as lk
search_res = lk.search.search_lightcurvefile(f"TIC219780464", mission='TESS')
search_res.table
```

![image](https://user-images.githubusercontent.com/250644/92782665-ff5ac880-f359-11ea-938c-536905a5a7fe.png)

MAST Portal showed there is an additional LC product in addition to the 3 returned by `lightkurve`, an LC spanning from sector 14 to 26:
![image](https://user-images.githubusercontent.com/250644/92782955-3df08300-f35a-11ea-9beb-b5add04f549f.png)

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): 1.11.2
-  installation method (e.g. pip, conda, source): conda

**Comment by orionlee** [comment]
Update: the multiple-sector times series products shown in MASS portal are not exactly time series fits. 
They are data validation time series fits (`_dvt.fits`) associated with some TCEs.

**Comment by barentsen** [comment]
Thanks so much for noticing and digging into this @orionlee!  That's how we find bugs! :+1:

Yep, this is a validation time series.  I don't have a lot of experience with these, but my understanding is that they contain multiple versions of stitched-and-flattened light curves for each planet candidate identified by the pipeline for a given target, i.e. it is high-level data product derived from the original per-sector light curves.

So far Lightkurve does not provide tools for dealing with data products that are specific to planet searches or planet search results, though I'd be interested to hear from users using these products.

Thanks again! :+1:
