### ISSUE TITLE
How to read in kplr001026032-2010265121752_llc.fits ?

### ISSUE THREAD

**Issue by pllim** [KeplerGO/lightkurve#858]
#### Problem description

How do you read a `kplr001026032-2010265121752_llc.fits` from STScI MAST into `lightkurve`? The file is downloaded from http://archive.stsci.edu/kepler/preview.php?dsn=KPLR001026032-2009166043257&type=LC .

I cannot seem to find this info searching the docs. Thanks!

**Comment by pllim** [comment]
7 days on which exoplanet? 😉

**Comment by orionlee** [comment]
See:

https://docs.lightkurve.org/api/lightkurve.search.open.html#lightkurve.search.open

**Comment by pllim** [comment]
p.s. `open` implies there is also a `close`, but does not look like it. Maybe `read` is a bit less misleading. Just a thought. Thanks for the quick reply!

**Comment by orionlee** [comment]
`open` will be deprecated, in favor of `read` in the next major release (2.0).

**Comment by pllim** [comment]
Ah, great. Can I use `read` now? I have 1.11.2

**Comment by orionlee** [comment]
`read` is not available in `v1`.
