### ISSUE TITLE
BLS BoxLeastSquaresPeriodogram 's default yields inaccurate results when transit duration is short

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#859]
#### Problem description

`BoxLeastSquaresPeriodogram` 's `duration` parameter has a lightkurve-specified default of `0.25` (6 hours).

- The result could be quite inaccurate when the actual transit duration is significantly shorter.
- It's also inconsistent with the default in `interact_bls()`, which is `0.05` (1.2 hours)

#### Expected behavior
It'd be great if the default should give more accurate results.

#### Proposal
Change the default `duration` to `[0.05, 0.10, 0.15, 0.20, 0.25, 0.33]` , which is closer to the range typical planetary transit duration.

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): 1.11.2
-  installation method (e.g. pip, conda, source): conda

**Comment by orionlee** [comment]
Use Kepler-10 as an example.  (I've tested on a few other Kepler / TESS lightcurves as well)

The proposed change of default `duration` to `[0.05, 0.10, 0.15, 0.20, 0.25, 0.33]` would
- yield more accurate result
- take a longer time to complete but is still acceptable. 
  - On my machine, the Periodogram running time increased from 0.36s to ~1.7s
- If `0.025` is added to the duration, it could take noticeably to run. On my machine for Kepler-10, it'd take 4s.


```
# lc = search_lightcurve("KIC 11904151", mission='Kepler', quarter=3).download(download_dir='./data') 
lc = lc.remove_nans()
lc = lc.normalize()
ax = lc.scatter();
ax.set_ylim(0.9985, 1.0015)
```

![image](https://user-images.githubusercontent.com/250644/94466701-b6d34580-0176-11eb-8d10-b690fae7625a.png)


---
The default, `lc.to_periodogram(method='bls')`, yields poor result:

![image](https://user-images.githubusercontent.com/250644/94466205-ec2b6380-0175-11eb-84d8-ae165df18eca.png)

---
Use `duration=[0.05, 0.10, 0.15, 0.20, 0.25, 0.33]` yields better result:

![image](https://user-images.githubusercontent.com/250644/94467397-bf784b80-0177-11eb-9fb7-70b0fea75bd2.png)

**Comment by barentsen** [comment]
Thanks so much for the detailed explanation and examples in this thread.  You made a very clear case that the default wasn't very good, even if it was faster.
