### ISSUE TITLE
Issue with lightkurve fill_gaps()

### ISSUE THREAD

**Issue by avanderburg** [KeplerGO/lightkurve#862]
#### Problem description
When following the lightkurve tutorial on improving the S/N of a lomb-scargle periodogram (http://docs.lightkurve.org/tutorials/02-how-to-optimize-periodogram-snr.html), get an error on this line: 
lc = lc.normalize(unit='ppm').remove_nans().remove_outliers().fill_gaps()

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-4-9f747bb60dc5> in <module>
      3 lc = lc.remove_nans()
      4 lc = lc.remove_outliers()
----> 5 lc = lc.fill_gaps()

/anaconda3/lib/python3.7/site-packages/lightkurve/lightcurve.py in fill_gaps(self, method)
    816             old_values = getattr(lc, column)
    817             new_values = np.empty(len(ntime), dtype=old_values.dtype)
--> 818             new_values[~in_original] = np.nan
    819             new_values[in_original] = np.copy(old_values)
    820             setattr(nlc, column, new_values)

ValueError: cannot convert float NaN to integer

It turns out the error is in fill_gaps(). 

#### Example

```python
import lightkurve as lk
import matplotlib.pyplot as plt
import numpy as np
import astropy.units as u

TARGET = "EPIC 211416749"
tpf = lk.search_targetpixelfile(TARGET, campaign=5, cadence='short').download()

lc = tpf.to_lightcurve()
lc = lc.normalize(unit='ppm')
lc = lc.remove_nans()
lc = lc.remove_outliers()
lc = lc.fill_gaps()
```

#### Expected behavior

I assume it should fill the gaps instead of crashing. I can remove the fill_gaps call and it runs successfully (but presumably the S/N of the periodogram is lower). 

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX and WIndows
-  lightkurve version (e.g. 1.0b6): 1.11.2
-  installation method (e.g. pip, conda, source): pip

**Comment by barentsen** [comment]
@avanderburg Thank you for taking the time to open this issue!

The bug has been fixed over in #867.  I released a new version of Lightkurve on pypi tonight which includes the fix (v1.11.3).

Please get in touch if you encounter any other issues! Thanks++!
