### ISSUE TITLE
Issue with lightkurve plots in Google Colab

### ISSUE THREAD

**Issue by avanderburg** [KeplerGO/lightkurve#863]
#### Problem description
Plots from lightkurve do not show up, and matplotlib plots do not show up after lightkurve has been imported (unless matplotlib is imported and used first). 

#### Example
I have created two colabs showing the problem and workaround here: 
Showing the issue: https://colab.research.google.com/drive/10sT-3kK08qERkPDkEgKMxqKA5yfVVvyB?usp=sharing
Showing the workaround: https://colab.research.google.com/drive/130GWUVJ29IahvpdXNHjJcu-_xYEphz5f?usp=sharing

#### Expected behavior
I expected lightkurve plots to show up in Colab without having to import matplotlib and plotting something first. 

#### Environment

-  platform (e.g. Linux, OSX, Windows): Google Colab
-  lightkurve version (e.g. 1.0b6): 1.11.2
-  installation method (e.g. pip, conda, source): pip

PS: I have a bunch of new students, and all of them are using lightkurve to access Kepler and TESS data. It's a great way to introduce them to the datasets and analysis!

**Comment by avanderburg** [comment]
Actually this looks like the same issue DFM noticed - if so disregard!

**Comment by barentsen** [comment]
Thanks @avanderburg!  Yep, this looks like the same issue as #861.  I'm happy you have a temporary workaround, and hope to have a fix available later today!

**Comment by barentsen** [comment]
@avanderburg Thanks again for reporting this issue.  I appreciate your time!

I released a new version of Lightkurve on pypi tonight (v1.11.3) which fixes the issue.

I verified that the Google Colab notebook you shared shows the missing plots now (see screenshot below). 

Don't hesitate to open new issues for any other problems you encounter. Thanks++!

### Screenshot confirming the fix

<img width="808" alt="Screen Shot 2020-10-06 at 22 20 13" src="https://user-images.githubusercontent.com/817669/95290480-340b5400-0822-11eb-96e7-d2760f07d4ab.png">
