### ISSUE TITLE
lc.meta should allow both upper and lower case keys

### ISSUE THREAD

**Issue by mrtommyb** [KeplerGO/lightkurve#872]
#### Problem description
If I want a particular piece for information from the fits header I can do
```python
print(lc.meta['int_time'])
```
but I can't do 
```python
print(lc.meta['INT_TIME'])
```

Even though the correct keyword in the files header is INT_TIME, not int_time. It would be easier if I could access the header information using both lower or upper case keys. The values returned are not all lower case, so I find it a little strange that we convert all keys to be lower case.

I appreciate that this is low priority. There is probably an easier solution than subclassing the a Dict, but that would be a way that would work.

**Comment by barentsen** [comment]
Agreed!  The meta keywords should not be lowercased.

Fortunately, we fixed this three days ago in #864 (authored by the awesome @orionlee).

If you pull the latest version of the master branch, this behavior will have been fixed!

**Comment by barentsen** [comment]
(I should add that we only get rid of the automatic lowercasing.  We did not make `lc.meta` case-insensitive, because it still is a standard `dict`.  I'd like to keep it a standard `dict` unless we have a good reason to add complexity to it.)

**Comment by mrtommyb** [comment]
Thanks Geert.
