### ISSUE TITLE
Lightkurve2 - lc.copy() failed when there are non-numeric columns

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#883]
#### Problem description
`lc.copy()` failed when there are non-numeric columns. It should work.

#### Example

```python
import lightkurve as lk
lc = lk.LightCurve(time=[1,2,3])
lc['col1'] = ['a', 'b', 'c']
lc_copy = lc.copy()
```

Error:
```python
...
c:\dev\lightkurve\lightkurve\lightcurve.py in __init__(self, data, time, flux, flux_err, *args, **kwargs)
    240         for col in self.columns:
    241             if not isinstance(self[col], (Quantity, Time)):
--> 242                 self.replace_column(col, Quantity(self[col], dtype=self[col].dtype))
    243 
    244         # Ensure flux and flux_err have the same units
...
TypeError: The value must be a valid Python or Numpy numeric type.
```

#### Environment

-  lightkurve version (e.g. 1.0b6): `master`, `2.0b3` based
-  installation method (e.g. pip, conda, source): source

**Comment by barentsen** [comment]
After merging #889, I verified that the failing code snippet runs without exception now:
```python
import lightkurve as lk
lc = lk.LightCurve(time=[1,2,3])
lc['col1'] = ['a', 'b', 'c']
lc_copy = lc.copy()
```

A regression test covering this example was added as part of the new `test_support_non_numeric_columns` test which was added via #889, so I think we can close this issue.

Thanks @orionlee!! :+1:
