### ISSUE TITLE
Lightkurve2 - consistent raw value accessor for columns

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#886]
#### Problem description
1. With `LightCurve` objects supporting non-numeric columns (PR #882), some default columns read from TESS / Kepler LC files become `Column` type rather than `Quantity`, e.g., `cadenceno` and `quality`.
The desired behavior is to ensure the resulting column type API as consistent as possible. 
Specifically, raw value access can be achieved via `.value`  (the `Quantity` API).

2. Ensure other generated `LightCurve` objects have the same behavior, e.g. the `LightCurve` objects from `TargetPixelFile.to_lightcurve()` / `get_bkg_lightcurve()`, etc.

Notes:
- The request supercedes earlier proposal of making all numeric columns `Quantity` (that would acheive similar behavior). Making unitless, metadata columns such as `quality` as `Quantity` is not desirable for reasons discussed in https://github.com/astropy/astropy/issues/10958#issuecomment-718131323.

#### Environment

-  lightkurve version (e.g. 1.0b6): `master`, `v2.0b3` based

**Comment by barentsen** [comment]
Just recording here for posterity that AstroPy v4.3 and later will provide `Column.value` as an alias for `Column.data`. 
 Our Pull Request to make this change was merged yesterday, cf. https://github.com/astropy/astropy/pull/10962
