### ISSUE TITLE
TargetPixelFile WCS extraction possibly failed when header is missing

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#892]
The `tpf.wcs` would raise `KeyError` if the requested key (`oldkey`) is missing in the TPF (line 378 below):

https://github.com/KeplerGO/lightkurve/blob/6265d26655f2bc44c5803d6e12501a3a9490d424/lightkurve/targetpixelfile.py#L376-L380

I believe the line is meant to be:
```python
        if (self.hdu[1].header.get(oldkey, None) is not None):
```

Affected version: `master`, Lightkurve 1 (it has the same code upon inspection)

**Comment by barentsen** [comment]
Agreed, the `.get()` syntax is no doubt more robust!
