### ISSUE TITLE
Lightcurve.scatter() : marker appears to be ignored

### ISSUE THREAD

**Issue by orionlee** [KeplerGO/lightkurve#897]
#### Problem description

When one specifies `marker` in `Lightcurve.scatter()`, the supplied marker is ignored. The default marker in [Lightkurve style](https://github.com/KeplerGO/lightkurve/blob/v1.11.x/lightkurve/data/lightkurve.mplstyle) is used instead.

#### Example

```python
lc.scatter(marker='x');
```

![image](https://user-images.githubusercontent.com/250644/98194230-bcd5e800-1ed3-11eb-9777-f6d7b0f5e308.png)

#### Environment

-  platform (e.g. Linux, OSX, Windows): Windows
-  lightkurve version (e.g. 1.0b6): 1.11.3
-  installation method (e.g. pip, conda, source): conda

**Comment by orionlee** [comment]
I considered it might be a matplotlib bug instead. But I could not reproduce it in isolation.

So the issue might be in `Lightkurve`, or it might be a matplotlib bug that only happens in more specific circumstances.

matplotlib correctly honors the supplied `marker` in `scatter()` call, instead of using the one defined the stylesheet (at least when done in isolation):
![image](https://user-images.githubusercontent.com/250644/98194632-b136f100-1ed4-11eb-8cc5-2c7da791f4a5.png)

**Comment by barentsen** [comment]
It looks like the reason for this is that the default marker size is so small that you cannot see the difference between dots and crosses (because `lightkurve.mplstyle` specifies `lines.markersize : 1`).

If you increase the marker size, crosses appear:

```python
lc.scatter(marker='x', s=10)
```

<img width="866" alt="Screen Shot 2020-11-05 at 08 11 41" src="https://user-images.githubusercontent.com/817669/98265964-90a38100-1f3e-11eb-8de7-eb147d471f25.png">


Thank you for opening this issue.  It could well have been a bug!

**Comment by orionlee** [comment]
Ah, I've been wondering why the default scatter looks like using `.` marker while the actual marker used is `o`.

It could be helpful if `lightkurve` issues a warning when users passes a custom `marker` without passing a custom size `s`.

**Comment by barentsen** [comment]
Oh!  Perhaps we should change the defaults in `lightkurve.mplstyle` to use `.` instead of `o`, so that we can increase the default marker size.

On my system, these defaults:

```
scatter.marker : .
lines.markersize : 4
```

...look more or less identical to the current default:
```
scatter.marker : o
lines.markersize : 1
```

**Comment by orionlee** [comment]
> Oh! Perhaps we should change the defaults in lightkurve.mplstyle to use . instead of o, so that we can increase the default marker size.

That sounds like a promising idea! I have 2 concerns:
1. Somehow the marker still looks bigger on my system. See below.
2. Assume (1) is addressed, would the change noticeably impact other setup / use cases? I'm speculating, but the possibilities include: people with different screen size / resolutions, plot to be created for prints, etc.


---
Example:
(Output from Jupyter. I also got the same result if I run Jupyter from Visual Studio Code)

```
style_tweaked = 'lightkurve-tweak.mplstyle' # changed to the scatter.marker: . with lines.markersize: 4

lc.scatter(label='current stylesheet');
lc.scatter(marker='.', s=4, label="custom marker='.' and s=4");  # matches current style

# the dots are still bigger with tweaked stylesheet
# so it seems that `s` parameter above isn't exactly equivalent to `lines.markersize` in stylesheet
lc.scatter(style=style_tweaked, label='tweaked stylesheet');

```
![image](https://user-images.githubusercontent.com/250644/98297363-248a4280-1f69-11eb-9a7e-d485760e59fd.png)

**Comment by orionlee** [comment]
@barentsen I'd like to check when you suggested `lines.markersize: 4`, you do mean it literally rather than specifying `s=4` in the scatter() call.

[matplotlib docs](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.scatter.html) clarify that `s = rcParams['lines.markersize'] ** 2`

> s float or array-like, shape (n, ), optional
> The marker size in points**2. Default is rcParams['lines.markersize'] ** 2.

If you do mean `lines.markersize: 4`, then its effect on my system is different from yours.

**Comment by barentsen** [comment]
Oops, I was using `s=4`, so I guess I should have said `lines.markersize: 2`!

**Comment by orionlee** [comment]
So assuming there is no concern for other use cases (e.g., plots used for printing, etc.), tweaking the default style would address the issue satisfactorily.

```
scatter.marker : .
lines.markersize : 2
```

I tried a few different markers. They look a tad weird with `markersize: 2`, but it's clear that the marker is used, so users can sought to change the size accordingly.

![image](https://user-images.githubusercontent.com/250644/98328419-920a9300-1faa-11eb-9965-c538cdfe58d6.png)

**Comment by barentsen** [comment]
> So assuming there is no concern for other use cases

I can't think of any existing features that would significantly change or break.
