### ISSUE TITLE
LightCurve.plot should have prettier defaults

### ISSUE THREAD

**Issue by mirca** [KeplerGO/lightkurve#9]
That's what I get with the current arguments:
![screen shot 2018-02-01 at 4 34 49 pm](https://user-images.githubusercontent.com/13077051/35710727-d67bddb2-076d-11e8-858f-fea8b3e9cec5.png)

**Comment by gully** [comment]
Look like a main improvement would be scaling the *y-* limits.
Also suppressing the `<matplotlib ... aba8>` text by default would help.
