### ISSUE TITLE
Make CBV corrector compatible with light curves that have missing cadences

### ISSUE THREAD

**Issue by amcody** [KeplerGO/lightkurve#90]
Currently the CBV corrector requires input light curves with the same number of data points as the CBV vectors. This is problematic as some of the light curve data is null and might be removed. We should change the CBV corrector so as to remove points from each vector that correspond to missing light curve data.

**Comment by mirca** [comment]
This is also related to #56 and #46

**Comment by barentsen** [comment]
CBVCorrector is being revised as part of #672!
