### ISSUE TITLE
Shift of the phase from -0.5,+0.5 to 0.0 to 1.0

### ISSUE THREAD

**Issue by MariannaPat** [KeplerGO/lightkurve#901]
I am currently working on extracting lightcurves with lightkurve and since I am mostly interested in the secondary eclipses of some systems I would like to shift the phase from (-0.5, 0.5) which is the default to (0.0, 1.0). Is there a way to do so?

**Comment by orionlee** [comment]
Here I assume you want to shift a folded lightcurve's plot by half a phase: you have done something like the following:
```python
lc_folded = lc.fold(t0=t0, period=period)
lc_folded.scatter()
```

To shift the plot by half a phase, you can adjust the `t0` during folding:
```python
lc_folded = lc.fold(t0=t0 + period / 2, period=period)
lc_folded.scatter()
```

**Comment by MariannaPat** [comment]
actually with this I get:
![WASP-121b (errorbars)](https://user-images.githubusercontent.com/56278591/98661295-90442500-2346-11eb-8610-95a89fa8b09c.png)
What I want is to see the whole lightcurve from 0.0 to 1.0 with both the transit and secondary eclipse. Here I just moved the secondary eclipse to 0.0 while I need it to 0.5.

**Comment by MariannaPat** [comment]
I want to move the x-axis from 0.0 to 1.0 and hence my data, not only my data

**Comment by orionlee** [comment]
Sounds like you want to see both eclipses in the plot, not broken at the edges.

If so, there are two ways. 
1. Move the plot so that both eclipses are off center. So they won't be broken at the edge, e.g., shift the phase by 1/4.

```python
lc_folded = lc.fold(t0=t0 + period / 4, period=period)
lc_folded.scatter()
```

2. Plot 2 cycles rather than 1 cycle. In that way, the primary eclipses will still be at the center.

```python
lc_folded = lc.fold(t0=t0, period=period*2)
lc_folded.scatter()
```

**Comment by MariannaPat** [comment]
![WASP-121b (errorbars)](https://user-images.githubusercontent.com/56278591/98731007-5d794b80-239d-11eb-954f-6ed932cf4803.png)
Indeed I can see both eclipses in the plot without being broken at the edges, but still the x-axis is not in the right form. What I want to achieve is having both eclipses and x-axis from 0.0 to 1.0.

**Comment by MariannaPat** [comment]
In such a way I will see the transit at 0.0 and the secondary eclipse at 0.5 of the phase.

**Comment by orionlee** [comment]
Are you talking about a plot like the one you showed, except relabeling the x-axis such that phase -0.5 becomes phase 0?

![image](https://user-images.githubusercontent.com/250644/98737739-811ba200-235b-11eb-9bdb-4b5d003e2584.png)

If so, you can adjust the `time` in the folded lightcurve with something like `lc_folded.time = lc_folded.time + 0.5` (which makes phase `-0.5` becomes `0`, etc.)

**Comment by MariannaPat** [comment]
I finally solved it!!! Thank you a lot for your help!
