### ISSUE TITLE
Binning function issue

### ISSUE THREAD

**Issue by rebekah9969** [KeplerGO/lightkurve#903]
The binning function does not appear to work as intended, see below.

The problem can be replicated with the code with values in the range 0-1234 to be binned with binsize=100:

import numpy as np
methodf=np._dict_['nanmean']
x=np.arange(1234.)
binsize=100
n_bins=len//binsize
indexes=np.array_split(np.arange(len),n_bins)
binn=np.array([methodf(x[a]) for a in indexes])
for i,ind in enumerate(indexes):
print(i,len(ind),np.mean(ind))

and outputs the following (iteration, binsize, binned point):
0 103 51.0
1 103 154.0
2 103 257.0
3 103 360.0
4 103 463.0
5 103 566.0
6 103 669.0
7 103 772.0
8 103 875.0
9 103 978.0
10 102 1080.5
11 102 1182.5

Note that the bins are of varying sizes instead of the expected ‘100’ and leads to incorrectly binned data (the first bin should have a value of 49.5 as this bin ranges from 0 - 99 as per Python indexing). The issue stems from the np.array_split code which is incorrectly splitting the array by dividing the number of binned points into the total number of points to obtain the binsizes. This can be fixed by introducing a new variable n_points = n_bin * binsize and using that in place of n_bins in subsequent calculations which effectively ‘trims’ off the remaining data points at the end that cannot be used to produce a fully binned point.

Here is an example of working code on this matter:

x=np.arange(1234.)
binsize=100
n_bins=len//binsize
n_points=n_bins*binsize
indexes=np.array_split(np.arange(n_points),n_bins)
bin=np.array([methodf(x[a]) for a in indexes])
for i,ind in enumerate(indexes):
print(i,len(ind),np.mean(ind))

with output:
0 100 49.5
1 100 149.5
2 100 249.5
3 100 349.5
4 100 449.5
5 100 549.5
6 100 649.5
7 100 749.5
8 100 849.5
9 100 949.5
10 100 1049.5
11 100 1149.5
The original code will work correctly if the number of points is equal to a multiple of the binsize, however this breaks down when dealing with different N number of points, as will usually be the case.

**Comment by barentsen** [comment]
Apologies I did not look into this issue yet.  I think it is correct that there are issues with the new `bin()` method, and I am thinking to revert to the original `bin()` method we have in Lightkurve v1.x before releasing v2.0.

**Comment by barentsen** [comment]
@rebekah9969 I'm not entirely sure I understand this issue.  When I do the following in Lightkurve, the output looks correct to me?

<img width="506" alt="Screen Shot 2020-12-02 at 14 02 01" src="https://user-images.githubusercontent.com/817669/100936859-fe43be00-34a6-11eb-81c1-15b8bd92f4de.png">

**Comment by barentsen** [comment]
Closing this issue because a bit more information is needed to understand the issue.

@rebekah9969 Please do re-open if you can clarify!
