### ISSUE TITLE
Problem encountered with installing __version__ = "2.0b3"

### ISSUE THREAD

**Issue by KenMighell** [KeplerGO/lightkurve#908]
#### Problem description

I tried to install __version__ = "2.0b3" but unfortunately the install failed (see log.txt).

The install went back to the previous version: lightkurve-1.11.3

#### Example

```git clone https://github.com/KeplerGO/lightkurve.git
cd lightkurve
pip install -e .
```

#### Expected behavior

I expected a clean stall for __version__ = "2.0b3"

#### Environment

-  platform (e.g. Linux, OSX, Windows): OSX Mojave 10.14.6
-  lightkurve version (e.g. 1.0b6): 2.0b3
-  installation method (e.g. pip, conda, source): pip from GitHub repository

[log.txt](https://github.com/KeplerGO/lightkurve/files/5540106/log.txt)

**Comment by barentsen** [comment]
Thanks for reporting this issue @KenMighell.  This should be fixed on the master branch now!
