### ISSUE TITLE
search_lightcurvefile (and any other search) can only be used once per run

### ISSUE THREAD

**Issue by LucaNap** [KeplerGO/lightkurve#909]
Problem description:
I would like to analyze many light curves at once, but apparently I can only search for a target once per python run.

Example:

```python
import lightkurve as lk
lk.search_lightcurvefile('TOI 509.01',mission='TESS').download()
# Do stuff
lk.search_lightcurvefile('TOI 1258.01',mission='TESS').download()
*** ERROR HERE: I/O operation on closed file
```

Expected behavior:

Find first target --> do what you need to do
Find second target .... and so on

Environment

-  platform: latest windows
-  lightkurve version: latest version
-  installation method: conda

**Comment by barentsen** [comment]
@LucaNap Thank you for opening the issue!

I am unable to reproduce this issue on osx (see log below).  Would you be willing to copy/paste the full error message you are encountering?

One potential cause is that your local astropy cache contains a partially downloaded (i.e. corrupt) file for `TOI 1258.01`.   In this scenario, downloading the light curve of other targets should still work.

```python
$ python -m venv issue909
$ source issue909/bin/activate
$ python -m pip install lightkurve
$ python
Python 3.9.0 (default, Oct 27 2020, 14:15:17)
[Clang 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightkurve as lk
>>> lk.search_lightcurvefile('TOI 509.01',mission='TESS').download()
TessLightCurveFile(TICID: 453211454)
>>> lk.search_lightcurvefile('TOI 1258.01',mission='TESS').download()
/Users/gb/tmp/issue909/lib/python3.9/site-packages/lightkurve/search.py:228: LightkurveWarning: Warning: 4 files available to download. Only the first file has been downloaded. Please use `download_all()` or specify additional criteria (e.g. quarter, campaign, or sector) to limit your search.
  warnings.warn('Warning: {} files available to download. '
TessLightCurveFile(TICID: 288132261)
```

**Comment by LucaNap** [comment]
Thank you for answering so quickly. 

The error message is long but apparently all starts from here: 
_File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 147, in isatty
    return file.isatty()_

I have been able to bypass the error and have the expected result by modifying astropy\utils\console.py as follows:
    _if hasattr(file, 'isatty'):
        return False #instead of return file.isatty()_

Apparently this is an issue with astropy rather than lightkurve, or maybe with Anaconda?

**Comment by barentsen** [comment]
@LucaNap Would you be able to copy/paste the entire error message in this thread?  (Don't worry if the entire error is many dozens or even hundreds of lines, that's fine!  It always contains helpful debugging information.)

**Comment by LucaNap** [comment]
By the way, is it normal that certain TOIs are not found as targets? (ex: 851.01, 980.01 1187.01...)

@barentsen Yes, sorry. Here it is:

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\astroquery\query.py", line 383, in _download_file
    pb.update(bytes_read if bytes_read <= length else
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 1043, in update
    next(self._iter)
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 966, in _silent_iterator
    color_print(self._msg, self._color, file=self._file, end='')
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 356, in color_print
    file = kwargs.get('file', _get_stdout())
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 125, in _get_stdout
    if ipyio_stream is not None and isatty(ipyio_stream):
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 147, in isatty
    return file.isatty()
ValueError: I/O operation on closed file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python38\test GAPS\light.py", line 14, in <module>
    lc = lk.search_lightcurvefile(target,mission='TESS').download_all(download_dir='data/'+target).PDCSAP_FLUX.stitch()
  File "D:\Anaconda3\lib\site-packages\lightkurve\utils.py", line 479, in wrapper
    return f(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\lightkurve\search.py", line 290, in download_all
    products.append(self._download_one(table=self.table[idx:idx+1],
  File "D:\Anaconda3\lib\site-packages\lightkurve\search.py", line 175, in _download_one
    path = Observations.download_products(table[:1], mrp_only=False,
  File "D:\Anaconda3\lib\site-packages\astroquery\mast\observations.py", line 699, in download_products
    manifest = self._download_files(products, base_dir, cache, cloud_only)
  File "D:\Anaconda3\lib\site-packages\astroquery\mast\observations.py", line 574, in _download_files
    self._download_file(data_url, local_path,
  File "D:\Anaconda3\lib\site-packages\astroquery\query.py", line 386, in _download_file
    pb.update(bytes_read)
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 1035, in __exit__
    return self._obj.__exit__(exc_type, exc_value, traceback)
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 962, in __exit__
    color_print(' [Failed]', 'red', file=file)
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 356, in color_print
    file = kwargs.get('file', _get_stdout())
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 125, in _get_stdout
    if ipyio_stream is not None and isatty(ipyio_stream):
  File "D:\Anaconda3\lib\site-packages\astropy\utils\console.py", line 147, in isatty
    return file.isatty()
ValueError: I/O operation on closed file
>>>

**Comment by barentsen** [comment]
I'm afraid I'm struggling to understand the cause of this issue at this time.

I'm hoping other Windows users may be able to jump in to help reproduce and/or debug this problem.

**Comment by Mark-citizenscientist** [comment]
Hi All,

If it helps, this Windows user got this code to work.  The 'TOI xxx' as a target parameter does not work in this usage however.  Cheers, Mark

import matplotlib.pyplot as plt
import lightkurve as lk

#target = "TOI 509.01"
target = "TIC 453211454"
lc = lk.search_lightcurvefile(target,mission='TESS').download_all().PDCSAP_FLUX.stitch()
lc.plot()

#target = "TOI 1258.01"
target = "TIC 288132261"
lc = lk.search_lightcurvefile(target,mission='TESS').download_all().PDCSAP_FLUX.stitch()
lc.plot()

plt.show()

**Comment by LucaNap** [comment]
I just want to add that this issue is very much present in version 2.0b3. It's actually worse; I can't even find a single target. 
I am not even sure if the trick I posted in this thread is working in that version.

**Comment by Mark-citizenscientist** [comment]
Maybe try updating your installed python packages or install the previous
version of numpy for example.  After trying this I got part of your code
sample to work with my regular or standard python 3.8.5 install, and it
also works with my installed Anaconda python 3.8.3.

import matplotlib.pyplot as plt
import lightkurve as lk

target = "TOI 509.01"
#target = "TIC 453211454"
lc =
lk.search_lightcurvefile(target,mission='TESS').download_all(download_dir='data/'+target).PDCSAP_FLUX.stitch()
lc.plot()

target = "TOI 1258.01"
#target = "TIC 288132261"
lc =
lk.search_lightcurvefile(target,mission='TESS').download_all(download_dir='data/'+target).PDCSAP_FLUX.stitch()
lc.plot()

plt.show()

**Comment by Mark-citizenscientist** [comment]
p.s. I am using Lightkurve 1.11.3

**Comment by LucaNap** [comment]
Hey @Mark-citizenscientist , thanks. Reinstalling the packages didn't help, the issue is still there.
However I am using lightkurve just fine with the trick I described earlier in the thread.

**Comment by barentsen** [comment]
@LucaNap Would you be willing to try the code you posted above again, but with `lk.log.setLevel("DEBUG")` added at the top?  This will print a bunch of interesting messages revealing what is going on behind the scenes.  This may provide clues.

When I do this, I see the following information:

<img width="1171" alt="Screen Shot 2020-12-03 at 20 02 04" src="https://user-images.githubusercontent.com/817669/101120478-9b375180-35a2-11eb-84d3-f7586130e8c2.png">

**Comment by LucaNap** [comment]
Thanks for the tip! 

Fortunately today I had to reinstall anaconda (for different reasons) and suddenly the issue is no longer present in Lightkurve v2.0b3. Since nobody else encountered it in v1.1.3, I think you can close this issue as it was probably linked to a new version of some dependency which has recently been fixed. However if I'll have time to play with Lightkurve 1.1.3, I'll let you know if I find this problem again.

**Comment by barentsen** [comment]
@LucaNap Interesting! Thanks for the report. My best guess is that your reinstall may have resulted in a newer version of `astroquery` being installed, which may have resolved the problem. Either way, it'll be good to keep an eye open for other users reporting this problem.

I strongly encourage anyone who also runs into this problem to comment below or open a new issue! 👍
