### ISSUE TITLE
Add a Jupyter notebook widget to inspect a TargetPixelFile

### ISSUE THREAD

**Issue by barentsen** [KeplerGO/lightkurve#91]
I propose we add a Jupyter notebook widget to lightkurve that allows a Target Pixel File to be inspected in detail.  The principal use case is to enable users to investigate why certain cadences appear as outliers in a lightcurve. @gully seems interested in working on this!

Proposed specifications:
* The widget shall allow the user to select a cadence using e.g. a scrollbar and an input box.
* For the selected cadence, the widget shall display the pixel data as an image.
* The widget shall also display the lightcurve and highlight the data point that corresponds to the user-select cadence.
* The widget shall display the list of quality flags set for the user-selected cadence (by calling `KeplerQualityFlags.decode()`).

Stretch goals (less important):
* The user shall be able to select to display FLUX, FLUX_BKG, RAW_CNTS (e.g. using a dropdown).
* The user shall be able to play the entire target pixel file as a movie using "play" and "pause" buttons.
* The user shall be able to interactively change the aperture mask to understand how it changes the lightcurve in real time.

@gully Feel free to think about and edit the specs!  The best way to start may be to mock up a non-functional prototype interface that enables a discussion about the exact UI and features.

**Comment by barentsen** [comment]
This is now being discussed over in #98.    I'll close this issue because it's a duplicate!

**Comment by gully** [comment]
whoops, I missed this when I opened the other issue!
