### ISSUE TITLE
'mask_color' is not working

### ISSUE THREAD

**Issue by rrpastro** [KeplerGO/lightkurve#92]
When I tried to use this command:
tpf.plot(frame=970, aperture_mask=tpf.pipeline_mask,mask_color='red')

I see the following errror:

AttributeError: Unknown property mask_color

Would you please look at it.

**Comment by barentsen** [comment]
@rrpastro Thank you for reporting this issue!

@amcody would you like to investigate if there is an easy fix for this?

**Comment by amcody** [comment]
Looking into it!

**Comment by amcody** [comment]
Hmm, I am not actually getting this bug. What version of matplotlib are you using?
![image](https://user-images.githubusercontent.com/10542558/37789664-c685c812-2dc1-11e8-943c-383b869c9054.png)

**Comment by mirca** [comment]
hey @rrpastro, it looks like you are using an older version of `lightkurve`. Please do upgrade to fresh `1.0` :)

**Comment by rrpastro** [comment]
@barentsen, @amcody, @mirca : Thank you for your help. I have no issue regarding 'mask_color' now.
