### ISSUE TITLE
Exception when search called within a function

### ISSUE THREAD

**Issue by sourestdeeds** [KeplerGO/lightkurve#921]
#### Problem description
I'm having an issue trying to gracefully exit a program containing the MAST search. Is there any identifier or exception handling I can use to detect when a requested target search has no data entries and exit when this is returned?
#### Example

```
lcfs = search_lightcurvefile('WASP-181 b', mission='TESS')
if lcfs == 'No data found for target "WASP-181 b".':
            exit('gracefully exit')
```

**Comment by sourestdeeds** [comment]
I solved this by taking lcfs.table.to_pandas() and checking if the table has any entries.

**Comment by barentsen** [comment]
@sourestdeeds Thank you for opening the issue. I'm happy to hear you found a solution!

An alternative solution would be use `len(lcfs)`, i.e.:
```
if len(lcfs) == 0:
    # No data found....
```
