### ISSUE TITLE
Feature request: aperture photometry with medians

### ISSUE THREAD

**Issue by avanderburg** [KeplerGO/lightkurve#924]
#### Problem description
I would like to request a feature that I don't think currently exists in lightkurve. In the "extract_aperture_photometry" method, I would like for there to be an option to take the median value of each pixel within the aperture, rather than summing the pixel values within the aperture. This will mainly be useful when extracting sky background light curves, and (for example) an asteroid passes nearby the star. When the background is calculated with a sum, that can artificially increase the measured background, and introduce transit-like dips into the target light curve. But a median will usually avoid this problem. I hope this is the right place to submit this request! 

https://docs.lightkurve.org/api/lightkurve.targetpixelfile.TessTargetPixelFile.html#lightkurve.targetpixelfile.TessTargetPixelFile.extract_aperture_photometry

#### Example
N/A

I think all that would need to be added would be a line here (if a certain keyword is given) to replace np.nansum with np.nanmedian 
https://github.com/KeplerGO/lightkurve/blob/9b36c395d1524127cc94e83d775575a7ab229301/lightkurve/targetpixelfile.py#L795

#### Expected behavior
N/A

#### Environment
N/A

**Comment by barentsen** [comment]
Thank you for the request @avanderburg! :pray:

I think this is an excellent idea!  Stay tuned...

**Comment by rebekah9969** [comment]
Hello @avanderburg 

Thank you for your inquiry. We have now incorporated a flux_method function into Lightkurve version 2.0.
This allows the user to specify if they want the sum, median, or mean flux of an aperture. 
You would use it in a method similar to that shown below, 

`lc =  tpf.to_lightcurve(aperture_mask=aper, flux_method="mean")`

The default is set to sum the flux in the aperture if you did not want to specify the method. 

Thank you for request.

**Comment by avanderburg** [comment]
Thanks so much!!

**Comment by barentsen** [comment]
Thanks again for the suggestion @avanderburg! 🙏 

This feature is part of the 2.0beta5 release of Lightkurve.  You can try it out using `pip install lightkurve --pre --upgrade` (the `--pre` flag is essential to get a beta version).

There are a bunch of other changes in 2.0 however.  These will be summarized in a What's New guide which I expect to be available next week, so you may prefer to wait for that. 

Thanks again!
