### ISSUE TITLE
astroseismology code not working for tess data 

### ISSUE THREAD

**Issue by sanu-cpu** [KeplerGO/lightkurve#936]
hello sir
for lightkurve, there is a asteroseismology page this not work properly because they show wrong  nu max and delta nu  and also echelle diagram can you help me? how can i get right data. problem link attached below   
https://docs.lightkurve.org/tutorials/02-asteroseismology.html

**Comment by barentsen** [comment]
@sanu-cpu Thank you for your question.  We are in the process of updating the tutorials as part of the v2.0 release.  I recommend waiting 1-2 weeks until v2.0 is out to get started, but you can find a preview of those tutorials here:

https://github.com/KeplerGO/lightkurve/blob/master/docs/source/tutorials/3-science-examples/asteroseismology-estimating-mass-and-radius.ipynb
https://github.com/KeplerGO/lightkurve/blob/master/docs/source/tutorials/3-science-examples/asteroseismology-oscillating-star-periodogram.ipynb

Let us know if you have any further questions.  Thanks!

**Comment by sanu-cpu** [comment]
Hello mam
I am internship student and my internship close into first week of February
can you send early for me plz for Tess astroseismology tutorial

With regards
Sonam

**Comment by sanu-cpu** [comment]
Hello mam

https://github.com/KeplerGO/lightkurve/blob/master/docs/source/tutorials/3-science-examples/asteroseismology-estimating-mass-and-radius.ipynb

Mam this code working for Tess ?

**Comment by sanu-cpu** [comment]
If this code working for Tess then can you send me that code? I am using
tess data so I need tess tutorial plz plz mam

**Comment by sanu-cpu** [comment]
hello mam
your code not working properly
see pic that i attach below

**Comment by barentsen** [comment]
@sanu-cpu Unfortunately the photo you attached does not show up on GitHub.  Please post it directly on the GitHub thread at https://github.com/KeplerGO/lightkurve/issues/936 if possible. Thanks!
