### ISSUE TITLE
Improve layout of API documentation on lightkurve.keplerscience.org

### ISSUE THREAD

**Issue by amcody** [KeplerGO/lightkurve#96]
Consider making a [clickable?] menu of all methods and attributes at the top of the page. 
I was looking for wcs and it did not appear in the table at the top, so I gave up and had to ask Christina.

**Comment by barentsen** [comment]
We have now switched to using the `sphinx_automodapi` extension which has improved the layout of the API documentation pages significantly (cf. ##153).  I am going to close this issue for now, but feel free to re-open if documentation formatting issues pop up again!
