### ISSUE TITLE
A quicklook tool, with interactive targetpixel image registered to selected position in lightcurve

### ISSUE THREAD

**Issue by gully** [KeplerGO/lightkurve#98]
We propose a long-awaited feature: the ability to inspect the target-pixel file (TPF) at a cadence-of-interest, identified interactively from inspection of the associated lightcurve.

The **motivation for this feature** arises in many scenarios: "*Is this blip I see in my lightcurve astrophysical or some instrumental noise source?*" may be the most common.  Inspecting the cause of centroid shifts may be another niche, but powerful application-- did a supernova go off in the outskirts of your galaxy's target pixel postage stamp?  If so, you may witness a spatially segregated temporal rise in flux that pulls the centroid location away from the galaxy center and towards the supernova-- a sure sign that you have discovered a genuine transient.  A similar centroid-offset phenomenon can distinguish unresolved background eclipsing binaries from singleton transiting-planet-host stars.  Finally, the effortless feedback of pixel data instills an intuitive feel for the connection of lightcurve and pixels, perhaps even more-so than the existing [k2flix](https://github.com/KeplerGO/k2flix) gif-animations, that are not seemlessly registered to their associated lightcurves.

The successful design of this feature hinges upon the TPF image being displayed effortlessly and instantly.  That is: latency is near-zero---much less than human reaction time--- and no typing or clicking-through is needed.  We also demand interactivity:  a user may wish to zoom in on a region of interest while maintaining the linked, high-performance display.  

These user experience objectives drove us to select a design that adopts the javascript framework `bokeh`.  We investigated a matplotlib design, but we observed much higher latency, with less customization out-of-the-box.

The baseline design is simple.  The setting is a Jupyter notebook.  The user executes:

```python
tpf.quick_look()
```

which yields a lightcurve plot that is wider than it is tall, adjacent to a nominally square image window for the TPF.  A slider for cadence sits below the lightcurve window.  The slider instantly updates a vertical bar on the lightcurve window, and updates the pixel image in the TPF window.

The design offers many **avenues for additional functionality** and custom behavior.

First, the baseline design automatically computes the default (raw, simple aperture photometery [SAP]) flux using a bare `to_lightcurve()` method.  This SAP lightcurve may be adequate for some purposes, but likely the y-range will be overly large, and astrophysical signals of interest may be lost beneath the large motion-induced noise.  Instead, the user may instruct the use of a pre-processed lightcurve that has already dropped outliers and/or applied motion-detrending and custom background subtraction:

```python
lc_raw = tpf.to_lightcurve()
lc_cln = my_custom_cleaning_function(lc_raw)
# lc_cln may have fewer elements than lc_raw!
tpf.quick_look(lc=lc_cln)
```

In this case, the user will witness a nice, cleaned lightcurve with the raw pixel-level data on its right.  Sliding the toolbar over missing cadences may simply jump over those cadences in the TPF, or show them anyway.  We haven't decided what the default behavior should be, but probably the former?

**Comment by gully** [comment]
⬆️ a prototype of the quicklook tool.

A few recommended upgrades:
- [ ] All the normal stylistic features-- axes labels, titles, distinctive fonts and colors, etc.
- [ ] A *longer* slider bar, ideally the same with as lightcurve window.  The steps jump by more than 1, so a given pixel cannot be "dialed into".

Bonus goal:
- [ ] Option for interactively updating the Screen Stretch on the TPF image.

**Comment by barentsen** [comment]
I'd like to suggest tooltips as an important extra feature.  The tooltip should provide the user access to the cadence number, the index number, the exact time value, the exact flux value, and the quality flags raised for the cadence.

**Comment by gully** [comment]
Updates from a discussion with Geert:

- add tooltips!
- use [1%, 95%] log stretch by default
- try aperture mask clicking feature
- see if we can just have `[Play/Pause] [Previous Frame] [Next Frame]` buttons

**Comment by gully** [comment]
![lightkurve_interact_2sliders](https://user-images.githubusercontent.com/860227/38585992-b96a1ab6-3cd0-11e8-9699-7c124ee69e33.gif)

**Comment by gully** [comment]
Now with screen stretch slider on log scale, and support for single increment steps using left arrow ◀️ and right arrow ▶️ keys.

**Comment by gully** [comment]
![lightkurve_interact_tooltips](https://user-images.githubusercontent.com/860227/38589598-c6355796-3ce0-11e8-81b8-0244d704b8e9.gif)

**Comment by gully** [comment]
Now with hover-over tool-tips that indicate quality flags, flux, cadence number, time.
